// Public Tenki SSH gateway protocol subset, preserving the published wire fields.
// Source: https://github.com/LuxorLabs/tenki-sdk-go/tree/sandbox/v1.2.0
// Copyright (c) 2026 TenkiCloud. MIT license; see LICENSE in this directory.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: internal/providers/tenki/proto/ssh_gateway.proto

package tenkiproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueSandboxSSHCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSandboxSSHCertRequest) Reset() {
	*x = IssueSandboxSSHCertRequest{}
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSandboxSSHCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSandboxSSHCertRequest) ProtoMessage() {}

func (x *IssueSandboxSSHCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSandboxSSHCertRequest.ProtoReflect.Descriptor instead.
func (*IssueSandboxSSHCertRequest) Descriptor() ([]byte, []int) {
	return file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *IssueSandboxSSHCertRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IssueSandboxSSHCertRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type IssueSandboxSSHCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SshCert       string                 `protobuf:"bytes,1,opt,name=ssh_cert,json=sshCert,proto3" json:"ssh_cert,omitempty"`
	CaPub         string                 `protobuf:"bytes,2,opt,name=ca_pub,json=caPub,proto3" json:"ca_pub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSandboxSSHCertResponse) Reset() {
	*x = IssueSandboxSSHCertResponse{}
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSandboxSSHCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSandboxSSHCertResponse) ProtoMessage() {}

func (x *IssueSandboxSSHCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSandboxSSHCertResponse.ProtoReflect.Descriptor instead.
func (*IssueSandboxSSHCertResponse) Descriptor() ([]byte, []int) {
	return file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *IssueSandboxSSHCertResponse) GetSshCert() string {
	if x != nil {
		return x.SshCert
	}
	return ""
}

func (x *IssueSandboxSSHCertResponse) GetCaPub() string {
	if x != nil {
		return x.CaPub
	}
	return ""
}

type ListActiveSSHGatewaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSSHGatewaysRequest) Reset() {
	*x = ListActiveSSHGatewaysRequest{}
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSSHGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSSHGatewaysRequest) ProtoMessage() {}

func (x *ListActiveSSHGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSSHGatewaysRequest.ProtoReflect.Descriptor instead.
func (*ListActiveSSHGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ListActiveSSHGatewaysRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListActiveSSHGatewaysRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListActiveSSHGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*ActiveSSHGateway    `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSSHGatewaysResponse) Reset() {
	*x = ListActiveSSHGatewaysResponse{}
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSSHGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSSHGatewaysResponse) ProtoMessage() {}

func (x *ListActiveSSHGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSSHGatewaysResponse.ProtoReflect.Descriptor instead.
func (*ListActiveSSHGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ListActiveSSHGatewaysResponse) GetGateways() []*ActiveSSHGateway {
	if x != nil {
		return x.Gateways
	}
	return nil
}

type ActiveSSHGateway struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GatewayId        string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	PublicEndpoint   string                 `protobuf:"bytes,3,opt,name=public_endpoint,json=publicEndpoint,proto3" json:"public_endpoint,omitempty"`
	Healthy          bool                   `protobuf:"varint,6,opt,name=healthy,proto3" json:"healthy,omitempty"`
	WsBridgeEndpoint string                 `protobuf:"bytes,7,opt,name=ws_bridge_endpoint,json=wsBridgeEndpoint,proto3" json:"ws_bridge_endpoint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActiveSSHGateway) Reset() {
	*x = ActiveSSHGateway{}
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSSHGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSSHGateway) ProtoMessage() {}

func (x *ActiveSSHGateway) ProtoReflect() protoreflect.Message {
	mi := &file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSSHGateway.ProtoReflect.Descriptor instead.
func (*ActiveSSHGateway) Descriptor() ([]byte, []int) {
	return file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ActiveSSHGateway) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ActiveSSHGateway) GetPublicEndpoint() string {
	if x != nil {
		return x.PublicEndpoint
	}
	return ""
}

func (x *ActiveSSHGateway) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ActiveSSHGateway) GetWsBridgeEndpoint() string {
	if x != nil {
		return x.WsBridgeEndpoint
	}
	return ""
}

var File_internal_providers_tenki_proto_ssh_gateway_proto protoreflect.FileDescriptor

const file_internal_providers_tenki_proto_ssh_gateway_proto_rawDesc = "" +
	"\n" +
	"0internal/providers/tenki/proto/ssh_gateway.proto\x12\x10tenki.sandbox.v1\"Z\n" +
	"\x1aIssueSandboxSSHCertRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"O\n" +
	"\x1bIssueSandboxSSHCertResponse\x12\x19\n" +
	"\bssh_cert\x18\x01 \x01(\tR\asshCert\x12\x15\n" +
	"\x06ca_pub\x18\x02 \x01(\tR\x05caPub\"U\n" +
	"\x1cListActiveSSHGatewaysRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"_\n" +
	"\x1dListActiveSSHGatewaysResponse\x12>\n" +
	"\bgateways\x18\x01 \x03(\v2\".tenki.sandbox.v1.ActiveSSHGatewayR\bgateways\"\xa2\x01\n" +
	"\x10ActiveSSHGateway\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12'\n" +
	"\x0fpublic_endpoint\x18\x03 \x01(\tR\x0epublicEndpoint\x12\x18\n" +
	"\ahealthy\x18\x06 \x01(\bR\ahealthy\x12,\n" +
	"\x12ws_bridge_endpoint\x18\a \x01(\tR\x10wsBridgeEndpointBGZEgithub.com/openclaw/crabbox/internal/providers/tenki/proto;tenkiprotob\x06proto3"

var (
	file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescOnce sync.Once
	file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescData []byte
)

func file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescGZIP() []byte {
	file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescOnce.Do(func() {
		file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_providers_tenki_proto_ssh_gateway_proto_rawDesc), len(file_internal_providers_tenki_proto_ssh_gateway_proto_rawDesc)))
	})
	return file_internal_providers_tenki_proto_ssh_gateway_proto_rawDescData
}

var file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_providers_tenki_proto_ssh_gateway_proto_goTypes = []any{
	(*IssueSandboxSSHCertRequest)(nil),    // 0: tenki.sandbox.v1.IssueSandboxSSHCertRequest
	(*IssueSandboxSSHCertResponse)(nil),   // 1: tenki.sandbox.v1.IssueSandboxSSHCertResponse
	(*ListActiveSSHGatewaysRequest)(nil),  // 2: tenki.sandbox.v1.ListActiveSSHGatewaysRequest
	(*ListActiveSSHGatewaysResponse)(nil), // 3: tenki.sandbox.v1.ListActiveSSHGatewaysResponse
	(*ActiveSSHGateway)(nil),              // 4: tenki.sandbox.v1.ActiveSSHGateway
}
var file_internal_providers_tenki_proto_ssh_gateway_proto_depIdxs = []int32{
	4, // 0: tenki.sandbox.v1.ListActiveSSHGatewaysResponse.gateways:type_name -> tenki.sandbox.v1.ActiveSSHGateway
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_providers_tenki_proto_ssh_gateway_proto_init() }
func file_internal_providers_tenki_proto_ssh_gateway_proto_init() {
	if File_internal_providers_tenki_proto_ssh_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_providers_tenki_proto_ssh_gateway_proto_rawDesc), len(file_internal_providers_tenki_proto_ssh_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_providers_tenki_proto_ssh_gateway_proto_goTypes,
		DependencyIndexes: file_internal_providers_tenki_proto_ssh_gateway_proto_depIdxs,
		MessageInfos:      file_internal_providers_tenki_proto_ssh_gateway_proto_msgTypes,
	}.Build()
	File_internal_providers_tenki_proto_ssh_gateway_proto = out.File
	file_internal_providers_tenki_proto_ssh_gateway_proto_goTypes = nil
	file_internal_providers_tenki_proto_ssh_gateway_proto_depIdxs = nil
}
