//go:build linux

// The initializer is delivered over Kubernetes exec, never over untrusted SSH.
// Its payload is generated by the runtime packaging step for the target arch.
package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha256"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"golang.org/x/crypto/ssh"
)

//go:embed payload.tar.gz
var payload []byte

const runtimeParent = "/opt/crabbox-runtime"
const stateParent = "/var/lib/crabbox-ssh"

type request struct {
	LeaseID         string `json:"lease_id"`
	PublicKey       string `json:"public_key"`
	ExpectedHostKey string `json:"expected_host_key"`
	ExpectedPort    string `json:"expected_port"`
}

func main() {
	if err := initialize(os.Stdin, os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, "agent-sandbox-ssh initializer:", err)
		os.Exit(1)
	}
}

func initialize(input io.Reader, output io.Writer) error {
	r, err := decodeRequest(input)
	if err != nil {
		return err
	}
	if os.Geteuid() != 0 || os.Getuid() != 0 {
		return errors.New("requires a root Linux container; no accounts or existing tools will be changed")
	}
	if err := validateRootAccount(); err != nil {
		return err
	}
	if err := secureDirectory(runtimeParent, 0755); err != nil {
		return err
	}
	lock, err := privateFile(filepath.Join(runtimeParent, ".initialize.lock"), os.O_RDWR|os.O_CREATE, 0600)
	if err != nil {
		return err
	}
	defer lock.Close()
	if err := syscall.Flock(int(lock.Fd()), syscall.LOCK_EX); err != nil {
		return fmt.Errorf("lock initialization: %w", err)
	}
	defer syscall.Flock(int(lock.Fd()), syscall.LOCK_UN)
	runtimeRoot, err := installRuntime()
	if err != nil {
		return err
	}
	if err := secureDirectory(stateParent, 0700); err != nil {
		return err
	}
	state := filepath.Join(stateParent, r.LeaseID)
	if err := secureDirectory(state, 0700); err != nil {
		return err
	}
	environment := daemonEnvironment()
	if err := installTools(runtimeRoot, state, environment); err != nil {
		return err
	}
	hostKey, err := prepareHostKey(runtimeRoot, state, r.ExpectedHostKey)
	if err != nil {
		return err
	}
	if err := ensurePrivateContents(filepath.Join(state, "authorized_keys"), []byte(r.PublicKey+"\n")); err != nil {
		return err
	}
	port, err := startDaemon(runtimeRoot, state, hostKey, r.ExpectedPort, environment)
	if err != nil {
		return err
	}
	_, err = fmt.Fprintf(output, "CRABBOX_SSH_USER=root\nCRABBOX_SSH_HOST_KEY=%s\nCRABBOX_SSH_PORT=%s\n", hostKey, port)
	return err
}

func decodeRequest(input io.Reader) (request, error) {
	var r request
	data, err := io.ReadAll(io.LimitReader(input, 16385))
	if err != nil {
		return r, err
	}
	if len(data) > 16384 {
		return r, errors.New("initialization JSON exceeds 16 KiB")
	}
	// Decode fields individually to reject duplicate keys as well as unknown ones.
	d := json.NewDecoder(bytes.NewReader(data))
	token, err := d.Token()
	if err != nil || token != json.Delim('{') {
		return r, errors.New("expected one initialization JSON object")
	}
	seen := make(map[string]bool)
	for d.More() {
		token, err := d.Token()
		if err != nil {
			return r, err
		}
		name, ok := token.(string)
		if !ok || seen[name] {
			return r, errors.New("duplicate or invalid initialization field")
		}
		seen[name] = true
		var destination *string
		switch name {
		case "lease_id":
			destination = &r.LeaseID
		case "public_key":
			destination = &r.PublicKey
		case "expected_host_key":
			destination = &r.ExpectedHostKey
		case "expected_port":
			destination = &r.ExpectedPort
		default:
			return r, fmt.Errorf("unknown initialization field %q", name)
		}
		var value any
		if err := d.Decode(&value); err != nil {
			return r, err
		}
		text, ok := value.(string)
		if !ok {
			return r, fmt.Errorf("initialization field %s must be a string", name)
		}
		*destination = text
	}
	if _, err := d.Token(); err != nil {
		return r, err
	}
	if _, err := d.Token(); err != io.EOF {
		return r, errors.New("trailing initialization JSON")
	}
	if len(r.LeaseID) == 0 || len(r.LeaseID) > 128 || strings.Trim(r.LeaseID, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-") != "" {
		return r, errors.New("invalid lease_id")
	}
	r.PublicKey, err = canonicalKey(r.PublicKey)
	if err != nil {
		return r, fmt.Errorf("public_key: %w", err)
	}
	if r.ExpectedHostKey != "" {
		r.ExpectedHostKey, err = canonicalKey(r.ExpectedHostKey)
		if err != nil {
			return r, fmt.Errorf("expected_host_key: %w", err)
		}
	}
	if r.ExpectedPort != "" && !validPort(r.ExpectedPort) {
		return r, errors.New("expected_port must be canonical decimal 1024..65535")
	}
	if (r.ExpectedHostKey == "") != (r.ExpectedPort == "") {
		return r, errors.New("expected_host_key and expected_port must be provided together")
	}
	return r, nil
}

func canonicalKey(value string) (string, error) {
	if strings.ContainsAny(value, "\r\n\x00") {
		return "", errors.New("key must be a single authorized-key line")
	}
	key, _, options, rest, err := ssh.ParseAuthorizedKey([]byte(value))
	if err != nil || len(options) != 0 || len(bytes.TrimSpace(rest)) != 0 {
		return "", errors.New("invalid authorized key or unexpected key options")
	}
	if key.Type() != ssh.KeyAlgoED25519 {
		return "", errors.New("only ssh-ed25519 keys are supported")
	}
	return strings.TrimSpace(string(ssh.MarshalAuthorizedKey(key))), nil
}

func validPort(value string) bool {
	port, err := strconv.Atoi(value)
	return err == nil && port >= 1024 && port <= 65535 && strconv.Itoa(port) == value
}

func validateRootAccount() error {
	data, err := os.ReadFile("/etc/passwd")
	if err != nil {
		return fmt.Errorf("read existing root account: %w", err)
	}
	shell := ""
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Split(line, ":")
		if len(fields) != 7 || fields[0] != "root" {
			continue
		}
		if fields[2] != "0" {
			return errors.New("existing root account must have UID 0")
		}
		if shell != "" {
			return errors.New("duplicate root accounts in /etc/passwd")
		}
		shell = fields[6]
		if shell == "" {
			shell = "/bin/sh"
		}
	}
	if shell == "" {
		return errors.New("existing root account is required; /etc/passwd will not be modified")
	}
	if filepath.Base(shell) == "false" || filepath.Base(shell) == "nologin" {
		return fmt.Errorf("root login shell %s rejects sessions; account files will not be modified", shell)
	}
	if !filepath.IsAbs(shell) {
		return errors.New("root login shell must be an absolute executable path")
	}
	if _, err := executable(shell); err != nil {
		return fmt.Errorf("root login shell: %w", err)
	}
	return nil
}

// Private runtime/state ancestors must be real root-owned directories. Unlike
// executable aliases, private paths never traverse a symlink into another tree.
func secureDirectory(directory string, mode os.FileMode) error {
	directory = filepath.Clean(directory)
	if !filepath.IsAbs(directory) {
		return fmt.Errorf("nonabsolute private directory %s", directory)
	}
	if directory != "/" {
		if err := secureDirectory(filepath.Dir(directory), 0755); err != nil {
			return err
		}
	}
	info, err := os.Lstat(directory)
	if os.IsNotExist(err) {
		if err := os.Mkdir(directory, mode); err != nil && !os.IsExist(err) {
			return fmt.Errorf("create %s: %w", directory, err)
		}
		info, err = os.Lstat(directory)
	}
	if err != nil {
		return err
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok || stat.Uid != 0 || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 || info.Mode().Perm()&0022 != 0 {
		return fmt.Errorf("%s must be a real root-owned directory without group/world write permission", directory)
	}
	if mode == 0700 && info.Mode().Perm()&0077 != 0 {
		return fmt.Errorf("private directory %s must have mode 0700; refusing to alter existing permissions", directory)
	}
	return nil
}

func privateFile(name string, flags int, mode os.FileMode) (*os.File, error) {
	fd, err := syscall.Open(name, flags|syscall.O_NOFOLLOW|syscall.O_CLOEXEC, uint32(mode))
	if err != nil {
		return nil, fmt.Errorf("open private file %s: %w", name, err)
	}
	f := os.NewFile(uintptr(fd), name)
	info, err := f.Stat()
	if err == nil {
		stat, ok := info.Sys().(*syscall.Stat_t)
		if !ok || stat.Uid != 0 || !info.Mode().IsRegular() || info.Mode().Perm()&0077 != 0 || stat.Nlink != 1 {
			err = fmt.Errorf("%s must be a private root-owned regular file with one link", name)
		}
	}
	if err != nil {
		f.Close()
		return nil, err
	}
	return f, nil
}

func privateRead(name string) ([]byte, error) {
	f, err := privateFile(name, os.O_RDONLY, 0600)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	data, err := io.ReadAll(io.LimitReader(f, 16385))
	if len(data) > 16384 {
		return nil, fmt.Errorf("private file %s is too large", name)
	}
	return data, err
}

func atomicPrivate(name string, data []byte) error {
	if _, err := privateRead(name); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	f, err := os.CreateTemp(filepath.Dir(name), ".write-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	if _, err := f.Write(data); err != nil {
		f.Close()
		return err
	}
	if err := f.Sync(); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(f.Name(), name)
}

func ensurePrivateContents(name string, data []byte) error {
	existing, err := privateRead(name)
	if err == nil {
		if !bytes.Equal(existing, data) {
			return fmt.Errorf("existing private identity %s differs; refusing to replace", name)
		}
		return nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return atomicPrivate(name, data)
}

type archiveLink struct{ name, target string }

func installRuntime() (string, error) {
	digest := sha256.Sum256(payload)
	root := filepath.Join(runtimeParent, fmt.Sprintf("%x", digest))
	if _, err := os.Lstat(root); err == nil {
		if err := secureDirectory(root, 0755); err != nil {
			return "", err
		}
		if err := unpackRuntime(root, true); err != nil {
			return "", fmt.Errorf("existing runtime failed payload verification: %w", err)
		}
		return root, nil
	} else if !os.IsNotExist(err) {
		return "", err
	}
	stage, err := os.MkdirTemp(runtimeParent, ".stage-*")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(stage)
	if err := unpackRuntime(stage, false); err != nil {
		return "", err
	}
	if err := os.Chmod(stage, 0755); err != nil {
		return "", err
	}
	if err := os.Rename(stage, root); err != nil {
		return "", err
	}
	return root, nil
}

// Payload aliases are deferred until all writes finish, so even a malformed
// embedded archive cannot redirect extraction through one of its own symlinks.
func unpackRuntime(root string, verify bool) error {
	z, err := gzip.NewReader(bytes.NewReader(payload))
	if err != nil {
		return fmt.Errorf("open embedded payload: %w", err)
	}
	defer z.Close()
	t := tar.NewReader(z)
	seen := make(map[string]bool)
	var links []archiveLink
	for {
		header, err := t.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		name := strings.TrimPrefix(header.Name, "./")
		if name == "" || name == "." {
			if header.Typeflag == tar.TypeDir {
				continue
			}
			return errors.New("invalid payload root entry")
		}
		name = strings.TrimSuffix(name, "/")
		if name != path.Clean(name) || path.IsAbs(name) || name == ".." || strings.HasPrefix(name, "../") || strings.ContainsAny(name, "\\\x00") {
			return fmt.Errorf("unsafe payload path %q", header.Name)
		}
		if seen[name] {
			return fmt.Errorf("duplicate payload entry %s", name)
		}
		seen[name] = true
		destination := filepath.Join(root, filepath.FromSlash(name))
		switch header.Typeflag {
		case tar.TypeDir:
			if err := payloadDirectory(root, destination, verify); err != nil {
				return err
			}
		case tar.TypeReg, tar.TypeRegA:
			if header.Size < 0 || header.Size > 512<<20 {
				return fmt.Errorf("invalid payload size for %s", name)
			}
			if err := payloadDirectory(root, filepath.Dir(destination), verify); err != nil {
				return err
			}
			mode := os.FileMode(0444)
			if header.Mode&0111 != 0 {
				mode = 0555
			}
			if verify {
				info, err := os.Lstat(destination)
				if err != nil {
					return err
				}
				stat, ok := info.Sys().(*syscall.Stat_t)
				if !ok || stat.Uid != 0 || !info.Mode().IsRegular() || info.Mode().Perm() != mode || info.Size() != header.Size {
					return fmt.Errorf("payload file metadata changed: %s", destination)
				}
				f, err := os.Open(destination)
				if err != nil {
					return err
				}
				actual := sha256.New()
				_, err = io.Copy(actual, f)
				f.Close()
				if err != nil {
					return err
				}
				expected := sha256.New()
				if _, err := io.Copy(expected, t); err != nil {
					return err
				}
				if !bytes.Equal(actual.Sum(nil), expected.Sum(nil)) {
					return fmt.Errorf("payload file digest changed: %s", destination)
				}
			} else {
				f, err := os.OpenFile(destination, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
				if err != nil {
					return err
				}
				_, copyErr := io.Copy(f, t)
				chmodErr := f.Chmod(mode)
				closeErr := f.Close()
				if err := errors.Join(copyErr, chmodErr, closeErr); err != nil {
					return err
				}
			}
		case tar.TypeSymlink:
			if path.IsAbs(header.Linkname) || strings.ContainsAny(header.Linkname, "\\\x00") || header.Linkname == "" {
				return fmt.Errorf("unsafe payload symlink %s", name)
			}
			resolved := path.Clean(path.Join(path.Dir(name), header.Linkname))
			if resolved == ".." || strings.HasPrefix(resolved, "../") {
				return fmt.Errorf("escaping payload symlink %s", name)
			}
			links = append(links, archiveLink{name, header.Linkname})
		default:
			return fmt.Errorf("unsupported payload entry type %d: %s", header.Typeflag, name)
		}
	}
	// Consume the gzip trailer too; tar EOF alone need not verify its checksum.
	if _, err := io.Copy(io.Discard, z); err != nil {
		return err
	}
	for _, link := range links {
		name := filepath.Join(root, link.name)
		if err := payloadDirectory(root, filepath.Dir(name), verify); err != nil {
			return err
		}
		if verify {
			target, err := os.Readlink(name)
			if err != nil || target != link.target {
				return fmt.Errorf("payload alias changed: %s", name)
			}
		} else if err := os.Symlink(link.target, name); err != nil {
			return err
		}
	}
	for _, link := range links {
		resolved, err := filepath.EvalSymlinks(filepath.Join(root, link.name))
		if err != nil || !strings.HasPrefix(resolved, root+"/") {
			return fmt.Errorf("payload alias has an invalid target: %s", link.name)
		}
	}
	if len(seen) == 0 {
		return errors.New("embedded runtime payload is empty")
	}
	return nil
}

func payloadDirectory(root, directory string, verify bool) error {
	if directory == root {
		return nil
	}
	if !strings.HasPrefix(directory, root+"/") {
		return fmt.Errorf("payload directory escapes runtime: %s", directory)
	}
	if err := payloadDirectory(root, filepath.Dir(directory), verify); err != nil {
		return err
	}
	info, err := os.Lstat(directory)
	if os.IsNotExist(err) && !verify {
		if err := os.Mkdir(directory, 0755); err != nil {
			return err
		}
		return nil
	}
	if err != nil {
		return err
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok || stat.Uid != 0 || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 || info.Mode().Perm()&0022 != 0 {
		return fmt.Errorf("unsafe payload directory %s", directory)
	}
	return nil
}

func daemonEnvironment() []string {
	// Preserve the pod-exec environment, not the client's local environment.
	// Append conventional paths rather than shadowing any existing image tools.
	env := os.Environ()
	value := os.Getenv("PATH")
	for _, directory := range []string{"/usr/bin", "/bin"} {
		found := false
		for _, existing := range filepath.SplitList(value) {
			if existing == directory {
				found = true
			}
		}
		if !found {
			if value != "" {
				value += ":"
			}
			value += directory
		}
	}
	for i, item := range env {
		if strings.HasPrefix(item, "PATH=") {
			env[i] = "PATH=" + value
			return env
		}
	}
	return append(env, "PATH="+value)
}

func executable(name string) (string, error) {
	resolved, err := filepath.EvalSymlinks(name)
	if err != nil {
		return "", fmt.Errorf("existing executable %s cannot resolve: %w", name, err)
	}
	info, err := os.Stat(resolved)
	if err != nil {
		return "", err
	}
	if !info.Mode().IsRegular() || info.Mode().Perm()&0111 == 0 {
		return "", fmt.Errorf("existing path %s is not an executable regular file", name)
	}
	return resolved, nil
}

type toolLink struct{ source, destination string }

func installTools(root, state string, environment []string) error {
	names := strings.Fields("sh bash git rsync tar gzip flock ps python3 find xargs grep sed awk env cat mkdir rm rmdir mv cp mktemp chmod chown stat date sleep base64 wc tr cut cmp sort uniq comm head tail tee touch readlink realpath dirname basename sha256sum dd ln id true false printf nohup timeout")
	planned := make([]toolLink, 0, len(names)*2)
	probed := make(map[string]bool)
	for _, name := range names {
		source := ""
		// Check what the unchanged image PATH actually selects first. An existing
		// incompatible implementation is an error, not grounds for substitution.
		for _, directory := range filepath.SplitList(os.Getenv("PATH")) {
			if directory == "" || !filepath.IsAbs(directory) {
				return errors.New("image PATH must contain only nonempty absolute directories")
			}
			candidate := filepath.Join(directory, name)
			if _, err := os.Lstat(candidate); err == nil {
				source = candidate
				break
			} else if !os.IsNotExist(err) {
				return err
			}
		}
		destinations := []string{filepath.Join("/usr/bin", name), filepath.Join("/bin", name)}
		for _, destination := range destinations {
			if _, err := os.Lstat(destination); err == nil {
				if source == "" {
					source = destination
				}
				if err := probeTool(name, destination, state, environment, probed); err != nil {
					return err
				}
			} else if !os.IsNotExist(err) {
				return err
			}
		}
		if source == "" {
			source = filepath.Join(root, "bin", name)
		}
		if err := probeTool(name, source, state, environment, probed); err != nil {
			return err
		}
		// Keep argv[0] as an applet's path: a multicall binary may implement many
		// tools via symlinks. Resolving to its underlying executable loses that.
		for _, destination := range destinations {
			if _, err := os.Lstat(destination); os.IsNotExist(err) {
				planned = append(planned, toolLink{source, destination})
			} else if err != nil {
				return err
			}
		}
	}
	for _, helper := range []toolLink{
		{filepath.Join(root, "bin/sftp-server"), "/usr/libexec/crabbox-sftp-server"},
		{filepath.Join(root, "libexec/git-core"), "/usr/libexec/crabbox-git-core"},
	} {
		if _, err := os.Stat(helper.source); err != nil {
			return fmt.Errorf("missing bundled helper %s: %w", helper.source, err)
		}
		if _, err := os.Lstat(helper.destination); err == nil {
			existing, err := filepath.EvalSymlinks(helper.destination)
			if err != nil || existing != helper.source {
				return fmt.Errorf("existing helper path %s conflicts with this runtime; refusing to replace", helper.destination)
			}
		} else if os.IsNotExist(err) {
			planned = append(planned, helper)
		} else {
			return err
		}
	}
	// All existing executable conflicts are checked before any global alias is
	// installed. Files added by this initializer survive until the Pod is removed.
	for _, link := range planned {
		parent := filepath.Dir(link.destination)
		if err := ensureExecutableParent(parent); err != nil {
			return err
		}
		if err := os.Symlink(link.source, link.destination); err != nil {
			// /bin may itself alias /usr/bin. Accept only the alias just installed.
			if !os.IsExist(err) {
				return fmt.Errorf("add missing executable %s: %w", link.destination, err)
			}
			target, readErr := os.Readlink(link.destination)
			if readErr != nil || target != link.source {
				return fmt.Errorf("executable path appeared during initialization: %s", link.destination)
			}
		}
	}
	return nil
}

func ensureExecutableParent(directory string) error {
	if directory != "/" {
		if err := ensureExecutableParent(filepath.Dir(directory)); err != nil {
			return err
		}
	}
	info, err := os.Lstat(directory)
	if os.IsNotExist(err) {
		if err := os.Mkdir(directory, 0755); err != nil {
			return fmt.Errorf("create executable parent %s: %w", directory, err)
		}
	} else if err != nil {
		return err
	} else {
		stat, ok := info.Sys().(*syscall.Stat_t)
		if !ok || stat.Uid != 0 {
			return fmt.Errorf("executable parent %s is not root-owned", directory)
		}
	}
	return trustedExecutableParent(directory)
}

func trustedExecutableParent(directory string) error {
	resolved, err := filepath.EvalSymlinks(directory)
	if err != nil {
		return err
	}
	for {
		info, err := os.Lstat(resolved)
		if err != nil {
			return err
		}
		stat, ok := info.Sys().(*syscall.Stat_t)
		if !ok || stat.Uid != 0 || !info.IsDir() || info.Mode().Perm()&0022 != 0 {
			return fmt.Errorf("executable parent %s is not a trusted root-owned directory", resolved)
		}
		if resolved == "/" {
			return nil
		}
		resolved = filepath.Dir(resolved)
	}
}

func probeTool(name, file, state string, environment []string, probed map[string]bool) error {
	resolved, err := executable(file)
	if err != nil {
		return err
	}
	key := name + "\x00" + resolved
	if probed[key] {
		return nil
	}
	probed[key] = true
	var args []string
	var input string
	var extraFiles []*os.File
	switch name {
	case "sh":
		args = []string{"-c", "test -n \"$(printf crabbox)\""}
	case "bash":
		args = []string{"--noprofile", "--norc", "-c", "a=(one two); [[ ${#a[@]} = 2 ]]"}
	case "git", "rsync", "tar":
		args = []string{"--version"}
	case "python3":
		args = []string{"-c", "import base64,json,os,sys; assert sys.version_info >= (3, 8)"}
	case "ps":
		args = []string{"-o", "lstart=", "-p", strconv.Itoa(os.Getpid())}
	case "flock":
		f, err := os.CreateTemp(state, ".flock-probe-*")
		if err != nil {
			return err
		}
		defer f.Close()
		defer os.Remove(f.Name())
		args = []string{"-x", "-w", "1", "3"}
		extraFiles = []*os.File{f}
	case "find":
		args = []string{state, "-maxdepth", "0", "-type", "d", "-print0"}
	case "grep":
		args = []string{"-E", "^crabbox$"}
		input = "crabbox\n"
	case "sed":
		args = []string{"-n", "s/^crabbox$/ok/p"}
		input = "crabbox\n"
	case "awk":
		args = []string{"BEGIN { if (split(\"a:b\", a, \":\") != 2) exit 1 }"}
	default:
		return nil
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, file, args...)
	cmd.Env = environment
	cmd.ExtraFiles = extraFiles
	cmd.Stdin = strings.NewReader(input)
	var stdout, stderr boundedBuffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("existing or bundled %s at %s lacks required behavior (%v): %s; existing tools will not be replaced", name, file, err, strings.TrimSpace(stderr.String()))
	}
	if name == "ps" {
		if strings.TrimSpace(stdout.String()) == "" {
			return fmt.Errorf("ps at %s does not report process start time; existing tools will not be replaced", file)
		}
		cmd = exec.CommandContext(ctx, file, "-e", "-o", "pid=")
		cmd.Env = environment
		stdout.Reset()
		stderr.Reset()
		cmd.Stdout, cmd.Stderr = &stdout, &stderr
		if err := cmd.Run(); err != nil || strings.TrimSpace(stdout.String()) == "" {
			return fmt.Errorf("ps at %s lacks -e -o pid= support; existing tools will not be replaced", file)
		}
	}
	return nil
}

type boundedBuffer struct{ bytes.Buffer }

func (b *boundedBuffer) Write(data []byte) (int, error) {
	n := len(data)
	if remaining := 16384 - b.Len(); remaining > 0 {
		if len(data) > remaining {
			data = data[:remaining]
		}
		_, _ = b.Buffer.Write(data)
	}
	return n, nil
}

func prepareHostKey(root, state, expected string) (string, error) {
	keyfile := filepath.Join(state, "host_ed25519")
	if _, err := privateRead(keyfile); errors.Is(err, os.ErrNotExist) {
		if expected != "" {
			return "", errors.New("pinned host private key disappeared; refusing to generate a replacement")
		}
		temporary, err := os.MkdirTemp(state, ".host-key-*")
		if err != nil {
			return "", err
		}
		defer os.RemoveAll(temporary)
		file := filepath.Join(temporary, "key")
		if _, err := runBundled(filepath.Join(root, "bin/dropbearkey"), "-t", "ed25519", "-f", file); err != nil {
			return "", err
		}
		if _, err := privateRead(file); err != nil {
			return "", err
		}
		if err := os.Rename(file, keyfile); err != nil {
			return "", err
		}
	} else if err != nil {
		return "", err
	}
	result, err := runBundled(filepath.Join(root, "bin/dropbearkey"), "-y", "-f", keyfile)
	if err != nil {
		return "", err
	}
	public := ""
	for _, line := range strings.Split(result, "\n") {
		if !strings.HasPrefix(line, "ssh-ed25519 ") {
			continue
		}
		if public != "" {
			return "", errors.New("dropbearkey returned multiple host keys")
		}
		public, err = canonicalKey(line)
		if err != nil {
			return "", err
		}
	}
	if public == "" {
		return "", errors.New("dropbearkey did not return an ed25519 host public key")
	}
	if expected != "" && expected != public {
		return "", errors.New("host key differs from the pinned lease identity")
	}
	return public, nil
}

func runBundled(binary string, args ...string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, binary, args...)
	var stdout, stderr boundedBuffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("%s: %w: %s", filepath.Base(binary), err, strings.TrimSpace(stderr.String()))
	}
	return stdout.String(), nil
}

func daemonArgs(state, port string) []string {
	// The bundled build disables syslog entirely; stderr logging is automatic,
	// and that build does not recognize the otherwise conventional -E option.
	return []string{"-F", "-e", "-s", "-m", "-D", state, "-r", filepath.Join(state, "host_ed25519"), "-P", filepath.Join(state, "dropbear.pid"), "-p", "127.0.0.1:" + port}
}

func ownDaemon(binary, state, port string) (int, bool, error) {
	data, err := privateRead(filepath.Join(state, "dropbear.pid"))
	if errors.Is(err, os.ErrNotExist) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, err
	}
	if len(data) == 0 {
		return 0, false, nil
	} // Precreated file from an interrupted launch.
	text := strings.TrimSuffix(string(data), "\n")
	pid, err := strconv.Atoi(text)
	if err != nil || pid <= 1 || strconv.Itoa(pid) != text {
		return 0, false, errors.New("invalid private daemon PID file")
	}
	actual, err := os.Readlink(fmt.Sprintf("/proc/%d/exe", pid))
	if os.IsNotExist(err) {
		return pid, false, nil
	}
	if err != nil {
		return 0, false, err
	}
	expected, err := filepath.EvalSymlinks(binary)
	if err != nil {
		return 0, false, err
	}
	if actual != expected {
		return 0, false, fmt.Errorf("private PID %d belongs to another executable; refusing to signal or replace it", pid)
	}
	command, err := os.ReadFile(fmt.Sprintf("/proc/%d/cmdline", pid))
	if err != nil {
		return 0, false, err
	}
	want := append([]string{binary}, daemonArgs(state, port)...)
	if string(command) != strings.Join(want, "\x00")+"\x00" {
		return 0, false, fmt.Errorf("private PID %d has unexpected arguments; refusing to signal or replace it", pid)
	}
	return pid, true, nil
}

func verifyListener(port, expected string) error {
	key, _, _, _, err := ssh.ParseAuthorizedKey([]byte(expected))
	if err != nil {
		return err
	}
	conn, err := net.DialTimeout("tcp4", "127.0.0.1:"+port, time.Second)
	if err != nil {
		return err
	}
	defer conn.Close()
	if err := conn.SetDeadline(time.Now().Add(3 * time.Second)); err != nil {
		return err
	}
	pinned := false
	config := &ssh.ClientConfig{User: "root", HostKeyAlgorithms: []string{ssh.KeyAlgoED25519}, HostKeyCallback: func(_ string, _ net.Addr, actual ssh.PublicKey) error {
		if !bytes.Equal(key.Marshal(), actual.Marshal()) {
			return errors.New("listener host key does not match private daemon")
		}
		pinned = true
		return nil
	}}
	client, _, _, err := ssh.NewClientConn(conn, "127.0.0.1:"+port, config)
	if err == nil {
		client.Close()
		return errors.New("private daemon unexpectedly allowed unauthenticated login")
	}
	// This exact client-side error follows successful signed key exchange and
	// rejection of the 'none' method. Merely reaching HostKeyCallback is not proof
	// that the server owns the key: signature verification happens afterwards.
	if pinned && err.Error() == "ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain" {
		return nil
	}
	return fmt.Errorf("private SSH listener verification: %w", err)
}

func startDaemon(root, state, hostKey, expectedPort string, environment []string) (string, error) {
	binary := filepath.Join(root, "bin/dropbear")
	portfile := filepath.Join(state, "port")
	port := ""
	if data, err := privateRead(portfile); err == nil {
		port = strings.TrimSuffix(string(data), "\n")
		if !validPort(port) {
			return "", errors.New("invalid stored private SSH port")
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", err
	}
	if expectedPort != "" {
		if port != "" && port != expectedPort {
			return "", errors.New("stored SSH port differs from pinned endpoint")
		}
		port = expectedPort
	}
	pinnedPort := port != ""
	if port != "" {
		_, live, err := ownDaemon(binary, state, port)
		if err != nil {
			return "", err
		}
		if live {
			if err := verifyListener(port, hostKey); err != nil {
				return "", err
			}
			return port, ensurePrivateContents(portfile, []byte(port+"\n"))
		}
	} else if _, err := privateRead(filepath.Join(state, "dropbear.pid")); err == nil {
		return "", errors.New("daemon PID exists without its port state; refusing ambiguous recovery")
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", err
	}
	for range 8 {
		if !pinnedPort {
			listener, err := net.Listen("tcp4", "127.0.0.1:0")
			if err != nil {
				return "", err
			}
			port = strconv.Itoa(listener.Addr().(*net.TCPAddr).Port)
			if err := listener.Close(); err != nil {
				return "", err
			}
		}
		// Persist before spawning so interrupted initialization can identify the
		// process. This is lease-private state, not an image file being replaced.
		if err := atomicPrivate(portfile, []byte(port+"\n")); err != nil {
			return "", err
		}
		pidfile := filepath.Join(state, "dropbear.pid")
		if _, err := privateRead(pidfile); err == nil {
			if err := os.Remove(pidfile); err != nil {
				return "", err
			}
		} else if !errors.Is(err, os.ErrNotExist) {
			return "", err
		}
		// Dropbear opens this with fopen("w"). Precreation fixes its mode without
		// imposing a private umask on the daemon's later workload processes.
		pidHandle, err := privateFile(pidfile, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
		if err != nil {
			return "", err
		}
		if err := pidHandle.Close(); err != nil {
			return "", err
		}
		logfile, err := privateFile(filepath.Join(state, "dropbear.log"), os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0600)
		if err != nil {
			return "", err
		}
		position, err := logfile.Seek(0, io.SeekEnd)
		if err != nil {
			logfile.Close()
			return "", err
		}
		cmd := exec.Command(binary, daemonArgs(state, port)...)
		cmd.Env = environment
		cmd.Dir = "/"
		cmd.Stdout, cmd.Stderr = logfile, logfile
		cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
		if err := cmd.Start(); err != nil {
			logfile.Close()
			return "", fmt.Errorf("start private Dropbear: %w", err)
		}
		logfile.Close()
		done := make(chan error, 1)
		go func() { done <- cmd.Wait() }()
		var readinessErr error
		var exited bool
		deadline := time.Now().Add(10 * time.Second)
		for time.Now().Before(deadline) {
			select {
			case readinessErr = <-done:
				exited = true
			default:
			}
			if exited {
				break
			}
			pid, live, err := ownDaemon(binary, state, port)
			if err == nil && live && pid == cmd.Process.Pid {
				readinessErr = verifyListener(port, hostKey)
				if readinessErr == nil {
					return port, nil
				}
			} else if err != nil {
				readinessErr = err
			}
			time.Sleep(50 * time.Millisecond)
		}
		if !exited {
			// cmd.Process is the handle we created, not a PID accepted from a file.
			// Still require the current executable/arguments before signalling.
			pid, live, err := ownDaemon(binary, state, port)
			if err == nil && live && pid == cmd.Process.Pid {
				_ = cmd.Process.Kill()
				<-done
			}
		}
		detail := daemonLogSince(filepath.Join(state, "dropbear.log"), position)
		if !pinnedPort && exited && strings.Contains(detail, "Address already in use") {
			if err := os.Remove(pidfile); err != nil && !os.IsNotExist(err) {
				return "", err
			}
			if err := os.Remove(portfile); err != nil {
				return "", err
			}
			continue
		}
		return "", fmt.Errorf("private Dropbear did not become ready (%v): %s", readinessErr, detail)
	}
	return "", errors.New("private SSH port was repeatedly taken during bind; no existing listener was changed")
}

func daemonLogSince(name string, offset int64) string {
	f, err := privateFile(name, os.O_RDONLY, 0600)
	if err != nil {
		return err.Error()
	}
	defer f.Close()
	if _, err := f.Seek(offset, io.SeekStart); err != nil {
		return err.Error()
	}
	data, err := io.ReadAll(io.LimitReader(f, 16384))
	if err != nil {
		return err.Error()
	}
	return strings.TrimSpace(string(data))
}
