// Client subset of the public boxd gRPC API served with TLS at boxd.sh:9443.
//
// Source of truth: https://docs.boxd.sh/reference/grpc-proto (package
// boxd.api.v1, service BoxdApi). This file declares only the RPCs Crabbox
// calls and, within each message, only the fields Crabbox reads or writes.
// Every field keeps the vendor's exact name, type, and number, so the wire
// contract is unchanged: proto3 ignores unknown fields on decode, and omitted
// fields are simply never sent. Field numbers were cross-checked against the
// production endpoint's gRPC server reflection on 2026-09-01.
//
// Regenerate with scripts/gen-boxd-proto.sh.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api.proto

package boxdapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Org to create the VM in (name or id). Empty = personal.
	Org string `protobuf:"bytes,9,opt,name=org,proto3" json:"org,omitempty"`
	// Isolated sandbox creation; immutable after creation.
	Isolated      bool `protobuf:"varint,12,opt,name=isolated,proto3" json:"isolated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVmRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *CreateVmRequest) GetIsolated() bool {
	if x != nil {
		return x.Isolated
	}
	return false
}

type CreateVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicIp      string                 `protobuf:"bytes,3,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	BootTimeMs    uint64                 `protobuf:"varint,7,opt,name=boot_time_ms,json=bootTimeMs,proto3" json:"boot_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse) Reset() {
	*x = CreateVmResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse) ProtoMessage() {}

func (x *CreateVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse.ProtoReflect.Descriptor instead.
func (*CreateVmResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVmResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVmResponse) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *CreateVmResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateVmResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateVmResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateVmResponse) GetBootTimeMs() uint64 {
	if x != nil {
		return x.BootTimeMs
	}
	return 0
}

type DestroyVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVmRequest) Reset() {
	*x = DestroyVmRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmRequest) ProtoMessage() {}

func (x *DestroyVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmRequest.ProtoReflect.Descriptor instead.
func (*DestroyVmRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type DestroyVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVmResponse) Reset() {
	*x = DestroyVmResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmResponse) ProtoMessage() {}

func (x *DestroyVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmResponse.ProtoReflect.Descriptor instead.
func (*DestroyVmResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

type StartVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmRequest) Reset() {
	*x = StartVmRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmRequest) ProtoMessage() {}

func (x *StartVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmRequest.ProtoReflect.Descriptor instead.
func (*StartVmRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *StartVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StartVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmResponse) Reset() {
	*x = StartVmResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmResponse) ProtoMessage() {}

func (x *StartVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmResponse.ProtoReflect.Descriptor instead.
func (*StartVmResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

type StopVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmRequest) Reset() {
	*x = StopVmRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmRequest) ProtoMessage() {}

func (x *StopVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmRequest.ProtoReflect.Descriptor instead.
func (*StopVmRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *StopVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StopVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmResponse) Reset() {
	*x = StopVmResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmResponse) ProtoMessage() {}

func (x *StopVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmResponse.ProtoReflect.Descriptor instead.
func (*StopVmResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

type GetVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmRequest) Reset() {
	*x = GetVmRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmRequest) ProtoMessage() {}

func (x *GetVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmRequest.ProtoReflect.Descriptor instead.
func (*GetVmRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type GetVmResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VmId     string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicIp string                 `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	Status   string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Org the VM is SHARED with (empty = private to its creator) and the org
	// paying for it (empty = the owner's personal quota), plus that org's id.
	Org          string `protobuf:"bytes,10,opt,name=org,proto3" json:"org,omitempty"`
	BillingOrg   string `protobuf:"bytes,11,opt,name=billing_org,json=billingOrg,proto3" json:"billing_org,omitempty"`
	BillingOrgId string `protobuf:"bytes,23,opt,name=billing_org_id,json=billingOrgId,proto3" json:"billing_org_id,omitempty"`
	// Isolated sandbox; immutable after creation.
	Isolated      bool `protobuf:"varint,26,opt,name=isolated,proto3" json:"isolated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmResponse) Reset() {
	*x = GetVmResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmResponse) ProtoMessage() {}

func (x *GetVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmResponse.ProtoReflect.Descriptor instead.
func (*GetVmResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetVmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetVmResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVmResponse) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *GetVmResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetVmResponse) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *GetVmResponse) GetBillingOrg() string {
	if x != nil {
		return x.BillingOrg
	}
	return ""
}

func (x *GetVmResponse) GetBillingOrgId() string {
	if x != nil {
		return x.BillingOrgId
	}
	return ""
}

func (x *GetVmResponse) GetIsolated() bool {
	if x != nil {
		return x.Isolated
	}
	return false
}

// vm addresses the machine (Crabbox always passes the immutable VM id and
// verifies the response's vm_id). Re-exposing the same vm_port keeps its
// public port.
type ExposePortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmPort        uint32                 `protobuf:"varint,2,opt,name=vm_port,json=vmPort,proto3" json:"vm_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Vm            string                 `protobuf:"bytes,4,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExposePortRequest) Reset() {
	*x = ExposePortRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposePortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposePortRequest) ProtoMessage() {}

func (x *ExposePortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposePortRequest.ProtoReflect.Descriptor instead.
func (*ExposePortRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *ExposePortRequest) GetVmPort() uint32 {
	if x != nil {
		return x.VmPort
	}
	return 0
}

func (x *ExposePortRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ExposePortRequest) GetVm() string {
	if x != nil {
		return x.Vm
	}
	return ""
}

type ExposePortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Dns           string                 `protobuf:"bytes,2,opt,name=dns,proto3" json:"dns,omitempty"`
	PublicPort    uint32                 `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	VmPort        uint32                 `protobuf:"varint,4,opt,name=vm_port,json=vmPort,proto3" json:"vm_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	VmId          string                 `protobuf:"bytes,6,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExposePortResponse) Reset() {
	*x = ExposePortResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposePortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposePortResponse) ProtoMessage() {}

func (x *ExposePortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposePortResponse.ProtoReflect.Descriptor instead.
func (*ExposePortResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *ExposePortResponse) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *ExposePortResponse) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *ExposePortResponse) GetPublicPort() uint32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *ExposePortResponse) GetVmPort() uint32 {
	if x != nil {
		return x.VmPort
	}
	return 0
}

func (x *ExposePortResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ExposePortResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type WhoamiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiRequest) Reset() {
	*x = WhoamiRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiRequest) ProtoMessage() {}

func (x *WhoamiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiRequest.ProtoReflect.Descriptor instead.
func (*WhoamiRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

type WhoamiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiResponse) Reset() {
	*x = WhoamiResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiResponse) ProtoMessage() {}

func (x *WhoamiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiResponse.ProtoReflect.Descriptor instead.
func (*WhoamiResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *WhoamiResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Bidirectional exec stream. The first client chunk carries vm_id and
// command; the command string is run by a shell inside the guest. Server
// chunks carry output in data (is_stderr distinguishes stderr for non-PTY
// execs), a nonzero exit_code reports failure, and a stream that ends
// cleanly without one completed with exit code zero.
type ExecChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Stdin         bool                   `protobuf:"varint,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Tty           bool                   `protobuf:"varint,3,opt,name=tty,proto3" json:"tty,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	VmId          string                 `protobuf:"bytes,5,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Cols          uint32                 `protobuf:"varint,7,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,8,opt,name=rows,proto3" json:"rows,omitempty"`
	WindowChange  bool                   `protobuf:"varint,9,opt,name=window_change,json=windowChange,proto3" json:"window_change,omitempty"`
	IsStderr      bool                   `protobuf:"varint,10,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecChunk) Reset() {
	*x = ExecChunk{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecChunk) ProtoMessage() {}

func (x *ExecChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecChunk.ProtoReflect.Descriptor instead.
func (*ExecChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *ExecChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecChunk) GetStdin() bool {
	if x != nil {
		return x.Stdin
	}
	return false
}

func (x *ExecChunk) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecChunk) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecChunk) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ExecChunk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecChunk) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ExecChunk) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ExecChunk) GetWindowChange() bool {
	if x != nil {
		return x.WindowChange
	}
	return false
}

func (x *ExecChunk) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\vboxd.api.v1\"S\n" +
	"\x0fCreateVmRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\t \x01(\tR\x03org\x12\x1a\n" +
	"\bisolated\x18\f \x01(\bR\bisolated\"\xba\x01\n" +
	"\x10CreateVmResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tpublic_ip\x18\x03 \x01(\tR\bpublicIp\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\fboot_time_ms\x18\a \x01(\x04R\n" +
	"bootTimeMs\"'\n" +
	"\x10DestroyVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x13\n" +
	"\x11DestroyVmResponse\"%\n" +
	"\x0eStartVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x11\n" +
	"\x0fStartVmResponse\"$\n" +
	"\rStopVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x10\n" +
	"\x0eStopVmResponse\"#\n" +
	"\fGetVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\xe2\x01\n" +
	"\rGetVmResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tpublic_ip\x18\x04 \x01(\tR\bpublicIp\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x10\n" +
	"\x03org\x18\n" +
	" \x01(\tR\x03org\x12\x1f\n" +
	"\vbilling_org\x18\v \x01(\tR\n" +
	"billingOrg\x12$\n" +
	"\x0ebilling_org_id\x18\x17 \x01(\tR\fbillingOrgId\x12\x1a\n" +
	"\bisolated\x18\x1a \x01(\bR\bisolated\"X\n" +
	"\x11ExposePortRequest\x12\x17\n" +
	"\avm_port\x18\x02 \x01(\rR\x06vmPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x0e\n" +
	"\x02vm\x18\x04 \x01(\tR\x02vm\"\xaa\x01\n" +
	"\x12ExposePortResponse\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\x12\x10\n" +
	"\x03dns\x18\x02 \x01(\tR\x03dns\x12\x1f\n" +
	"\vpublic_port\x18\x03 \x01(\rR\n" +
	"publicPort\x12\x17\n" +
	"\avm_port\x18\x04 \x01(\rR\x06vmPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x13\n" +
	"\x05vm_id\x18\x06 \x01(\tR\x04vmId\"\x0f\n" +
	"\rWhoamiRequest\")\n" +
	"\x0eWhoamiResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xfd\x01\n" +
	"\tExecChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\bR\x05stdin\x12\x10\n" +
	"\x03tty\x18\x03 \x01(\bR\x03tty\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x13\n" +
	"\x05vm_id\x18\x05 \x01(\tR\x04vmId\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12\x12\n" +
	"\x04cols\x18\a \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\b \x01(\rR\x04rows\x12#\n" +
	"\rwindow_change\x18\t \x01(\bR\fwindowChange\x12\x1b\n" +
	"\tis_stderr\x18\n" +
	" \x01(\bR\bisStderr2\xb5\x04\n" +
	"\aBoxdApi\x12G\n" +
	"\bCreateVm\x12\x1c.boxd.api.v1.CreateVmRequest\x1a\x1d.boxd.api.v1.CreateVmResponse\x12J\n" +
	"\tDestroyVm\x12\x1d.boxd.api.v1.DestroyVmRequest\x1a\x1e.boxd.api.v1.DestroyVmResponse\x12D\n" +
	"\aStartVm\x12\x1b.boxd.api.v1.StartVmRequest\x1a\x1c.boxd.api.v1.StartVmResponse\x12A\n" +
	"\x06StopVm\x12\x1a.boxd.api.v1.StopVmRequest\x1a\x1b.boxd.api.v1.StopVmResponse\x12>\n" +
	"\x05GetVm\x12\x19.boxd.api.v1.GetVmRequest\x1a\x1a.boxd.api.v1.GetVmResponse\x12M\n" +
	"\n" +
	"ExposePort\x12\x1e.boxd.api.v1.ExposePortRequest\x1a\x1f.boxd.api.v1.ExposePortResponse\x12A\n" +
	"\x06Whoami\x12\x1a.boxd.api.v1.WhoamiRequest\x1a\x1b.boxd.api.v1.WhoamiResponse\x12:\n" +
	"\x04Exec\x12\x16.boxd.api.v1.ExecChunk\x1a\x16.boxd.api.v1.ExecChunk(\x010\x01B=Z;github.com/openclaw/crabbox/internal/providers/boxd/boxdapib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_goTypes = []any{
	(*CreateVmRequest)(nil),    // 0: boxd.api.v1.CreateVmRequest
	(*CreateVmResponse)(nil),   // 1: boxd.api.v1.CreateVmResponse
	(*DestroyVmRequest)(nil),   // 2: boxd.api.v1.DestroyVmRequest
	(*DestroyVmResponse)(nil),  // 3: boxd.api.v1.DestroyVmResponse
	(*StartVmRequest)(nil),     // 4: boxd.api.v1.StartVmRequest
	(*StartVmResponse)(nil),    // 5: boxd.api.v1.StartVmResponse
	(*StopVmRequest)(nil),      // 6: boxd.api.v1.StopVmRequest
	(*StopVmResponse)(nil),     // 7: boxd.api.v1.StopVmResponse
	(*GetVmRequest)(nil),       // 8: boxd.api.v1.GetVmRequest
	(*GetVmResponse)(nil),      // 9: boxd.api.v1.GetVmResponse
	(*ExposePortRequest)(nil),  // 10: boxd.api.v1.ExposePortRequest
	(*ExposePortResponse)(nil), // 11: boxd.api.v1.ExposePortResponse
	(*WhoamiRequest)(nil),      // 12: boxd.api.v1.WhoamiRequest
	(*WhoamiResponse)(nil),     // 13: boxd.api.v1.WhoamiResponse
	(*ExecChunk)(nil),          // 14: boxd.api.v1.ExecChunk
}
var file_api_proto_depIdxs = []int32{
	0,  // 0: boxd.api.v1.BoxdApi.CreateVm:input_type -> boxd.api.v1.CreateVmRequest
	2,  // 1: boxd.api.v1.BoxdApi.DestroyVm:input_type -> boxd.api.v1.DestroyVmRequest
	4,  // 2: boxd.api.v1.BoxdApi.StartVm:input_type -> boxd.api.v1.StartVmRequest
	6,  // 3: boxd.api.v1.BoxdApi.StopVm:input_type -> boxd.api.v1.StopVmRequest
	8,  // 4: boxd.api.v1.BoxdApi.GetVm:input_type -> boxd.api.v1.GetVmRequest
	10, // 5: boxd.api.v1.BoxdApi.ExposePort:input_type -> boxd.api.v1.ExposePortRequest
	12, // 6: boxd.api.v1.BoxdApi.Whoami:input_type -> boxd.api.v1.WhoamiRequest
	14, // 7: boxd.api.v1.BoxdApi.Exec:input_type -> boxd.api.v1.ExecChunk
	1,  // 8: boxd.api.v1.BoxdApi.CreateVm:output_type -> boxd.api.v1.CreateVmResponse
	3,  // 9: boxd.api.v1.BoxdApi.DestroyVm:output_type -> boxd.api.v1.DestroyVmResponse
	5,  // 10: boxd.api.v1.BoxdApi.StartVm:output_type -> boxd.api.v1.StartVmResponse
	7,  // 11: boxd.api.v1.BoxdApi.StopVm:output_type -> boxd.api.v1.StopVmResponse
	9,  // 12: boxd.api.v1.BoxdApi.GetVm:output_type -> boxd.api.v1.GetVmResponse
	11, // 13: boxd.api.v1.BoxdApi.ExposePort:output_type -> boxd.api.v1.ExposePortResponse
	13, // 14: boxd.api.v1.BoxdApi.Whoami:output_type -> boxd.api.v1.WhoamiResponse
	14, // 15: boxd.api.v1.BoxdApi.Exec:output_type -> boxd.api.v1.ExecChunk
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
