// Client subset of the public boxd gRPC API served with TLS at boxd.sh:9443.
//
// Source of truth: https://docs.boxd.sh/reference/grpc-proto (package
// boxd.api.v1, service BoxdApi). This file declares only the RPCs Crabbox
// calls and, within each message, only the fields Crabbox reads or writes.
// Every field keeps the vendor's exact name, type, and number, so the wire
// contract is unchanged: proto3 ignores unknown fields on decode, and omitted
// fields are simply never sent. Field numbers were cross-checked against the
// production endpoint's gRPC server reflection on 2026-09-01.
//
// Regenerate with scripts/gen-boxd-proto.sh.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api.proto

package boxdapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoxdApi_CreateVm_FullMethodName   = "/boxd.api.v1.BoxdApi/CreateVm"
	BoxdApi_DestroyVm_FullMethodName  = "/boxd.api.v1.BoxdApi/DestroyVm"
	BoxdApi_StartVm_FullMethodName    = "/boxd.api.v1.BoxdApi/StartVm"
	BoxdApi_StopVm_FullMethodName     = "/boxd.api.v1.BoxdApi/StopVm"
	BoxdApi_GetVm_FullMethodName      = "/boxd.api.v1.BoxdApi/GetVm"
	BoxdApi_ExposePort_FullMethodName = "/boxd.api.v1.BoxdApi/ExposePort"
	BoxdApi_Whoami_FullMethodName     = "/boxd.api.v1.BoxdApi/Whoami"
	BoxdApi_Exec_FullMethodName       = "/boxd.api.v1.BoxdApi/Exec"
)

// BoxdApiClient is the client API for BoxdApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoxdApiClient interface {
	CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error)
	DestroyVm(ctx context.Context, in *DestroyVmRequest, opts ...grpc.CallOption) (*DestroyVmResponse, error)
	StartVm(ctx context.Context, in *StartVmRequest, opts ...grpc.CallOption) (*StartVmResponse, error)
	StopVm(ctx context.Context, in *StopVmRequest, opts ...grpc.CallOption) (*StopVmResponse, error)
	GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error)
	ExposePort(ctx context.Context, in *ExposePortRequest, opts ...grpc.CallOption) (*ExposePortResponse, error)
	Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*WhoamiResponse, error)
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecChunk, ExecChunk], error)
}

type boxdApiClient struct {
	cc grpc.ClientConnInterface
}

func NewBoxdApiClient(cc grpc.ClientConnInterface) BoxdApiClient {
	return &boxdApiClient{cc}
}

func (c *boxdApiClient) CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) DestroyVm(ctx context.Context, in *DestroyVmRequest, opts ...grpc.CallOption) (*DestroyVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_DestroyVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) StartVm(ctx context.Context, in *StartVmRequest, opts ...grpc.CallOption) (*StartVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_StartVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) StopVm(ctx context.Context, in *StopVmRequest, opts ...grpc.CallOption) (*StopVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_StopVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVmResponse)
	err := c.cc.Invoke(ctx, BoxdApi_GetVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) ExposePort(ctx context.Context, in *ExposePortRequest, opts ...grpc.CallOption) (*ExposePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExposePortResponse)
	err := c.cc.Invoke(ctx, BoxdApi_ExposePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*WhoamiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoamiResponse)
	err := c.cc.Invoke(ctx, BoxdApi_Whoami_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxdApiClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecChunk, ExecChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BoxdApi_ServiceDesc.Streams[0], BoxdApi_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecChunk, ExecChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxdApi_ExecClient = grpc.BidiStreamingClient[ExecChunk, ExecChunk]

// BoxdApiServer is the server API for BoxdApi service.
// All implementations must embed UnimplementedBoxdApiServer
// for forward compatibility.
type BoxdApiServer interface {
	CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error)
	DestroyVm(context.Context, *DestroyVmRequest) (*DestroyVmResponse, error)
	StartVm(context.Context, *StartVmRequest) (*StartVmResponse, error)
	StopVm(context.Context, *StopVmRequest) (*StopVmResponse, error)
	GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error)
	ExposePort(context.Context, *ExposePortRequest) (*ExposePortResponse, error)
	Whoami(context.Context, *WhoamiRequest) (*WhoamiResponse, error)
	Exec(grpc.BidiStreamingServer[ExecChunk, ExecChunk]) error
	mustEmbedUnimplementedBoxdApiServer()
}

// UnimplementedBoxdApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoxdApiServer struct{}

func (UnimplementedBoxdApiServer) CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedBoxdApiServer) DestroyVm(context.Context, *DestroyVmRequest) (*DestroyVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyVm not implemented")
}
func (UnimplementedBoxdApiServer) StartVm(context.Context, *StartVmRequest) (*StartVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVm not implemented")
}
func (UnimplementedBoxdApiServer) StopVm(context.Context, *StopVmRequest) (*StopVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVm not implemented")
}
func (UnimplementedBoxdApiServer) GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVm not implemented")
}
func (UnimplementedBoxdApiServer) ExposePort(context.Context, *ExposePortRequest) (*ExposePortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExposePort not implemented")
}
func (UnimplementedBoxdApiServer) Whoami(context.Context, *WhoamiRequest) (*WhoamiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Whoami not implemented")
}
func (UnimplementedBoxdApiServer) Exec(grpc.BidiStreamingServer[ExecChunk, ExecChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedBoxdApiServer) mustEmbedUnimplementedBoxdApiServer() {}
func (UnimplementedBoxdApiServer) testEmbeddedByValue()                 {}

// UnsafeBoxdApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoxdApiServer will
// result in compilation errors.
type UnsafeBoxdApiServer interface {
	mustEmbedUnimplementedBoxdApiServer()
}

func RegisterBoxdApiServer(s grpc.ServiceRegistrar, srv BoxdApiServer) {
	// If the following call pancis, it indicates UnimplementedBoxdApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoxdApi_ServiceDesc, srv)
}

func _BoxdApi_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).CreateVm(ctx, req.(*CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_DestroyVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).DestroyVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_DestroyVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).DestroyVm(ctx, req.(*DestroyVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_StartVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).StartVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_StartVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).StartVm(ctx, req.(*StartVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_StopVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).StopVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_StopVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).StopVm(ctx, req.(*StopVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_GetVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).GetVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_GetVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).GetVm(ctx, req.(*GetVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_ExposePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).ExposePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_ExposePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).ExposePort(ctx, req.(*ExposePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_Whoami_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoamiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxdApiServer).Whoami(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxdApi_Whoami_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxdApiServer).Whoami(ctx, req.(*WhoamiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxdApi_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BoxdApiServer).Exec(&grpc.GenericServerStream[ExecChunk, ExecChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxdApi_ExecServer = grpc.BidiStreamingServer[ExecChunk, ExecChunk]

// BoxdApi_ServiceDesc is the grpc.ServiceDesc for BoxdApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoxdApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boxd.api.v1.BoxdApi",
	HandlerType: (*BoxdApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVm",
			Handler:    _BoxdApi_CreateVm_Handler,
		},
		{
			MethodName: "DestroyVm",
			Handler:    _BoxdApi_DestroyVm_Handler,
		},
		{
			MethodName: "StartVm",
			Handler:    _BoxdApi_StartVm_Handler,
		},
		{
			MethodName: "StopVm",
			Handler:    _BoxdApi_StopVm_Handler,
		},
		{
			MethodName: "GetVm",
			Handler:    _BoxdApi_GetVm_Handler,
		},
		{
			MethodName: "ExposePort",
			Handler:    _BoxdApi_ExposePort_Handler,
		},
		{
			MethodName: "Whoami",
			Handler:    _BoxdApi_Whoami_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _BoxdApi_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}
