// Code generated by scripts/configgen from config_morph.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileMorphConfig struct {
	APIKey          string `yaml:"apiKey,omitempty"`
	APIURL          string `yaml:"apiUrl,omitempty"`
	Snapshot        string `yaml:"snapshot,omitempty"`
	SSHGatewayHost  string `yaml:"sshGatewayHost,omitempty"`
	WorkRoot        string `yaml:"workRoot,omitempty"`
	DeleteOnRelease *bool  `yaml:"deleteOnRelease,omitempty"`
	WakeOnSSH       *bool  `yaml:"wakeOnSSH,omitempty"`
}

const MorphConfigDefaultAPIURL string = "https://cloud.morph.so"
const MorphConfigDefaultSSHGatewayHost string = "ssh.cloud.morph.so"
const MorphConfigDefaultWorkRoot string = "/tmp/crabbox"
const MorphConfigDefaultWakeOnSSH bool = true

func defaultMorphConfig() MorphConfig {
	return MorphConfig{
		APIURL:         MorphConfigDefaultAPIURL,
		SSHGatewayHost: MorphConfigDefaultSSHGatewayHost,
		WorkRoot:       MorphConfigDefaultWorkRoot,
		WakeOnSSH:      MorphConfigDefaultWakeOnSSH,
	}
}

// MorphConfigApplied records accepted assignments during one application.
type MorphConfigApplied struct {
	APIKey          bool
	APIURL          bool
	SSHGatewayHost  bool
	DeleteOnRelease bool
}

func (cfg *MorphConfig) applyFile(file *fileMorphConfig) (MorphConfigApplied, error) {
	var applied MorphConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.APIKey != "" {
		cfg.APIKey = file.APIKey
		applied.APIKey = true
	}
	if file.APIURL != "" {
		cfg.APIURL = file.APIURL
		applied.APIURL = true
	}
	if file.Snapshot != "" {
		cfg.Snapshot = file.Snapshot
	}
	if file.SSHGatewayHost != "" {
		cfg.SSHGatewayHost = file.SSHGatewayHost
		applied.SSHGatewayHost = true
	}
	if file.WorkRoot != "" {
		cfg.WorkRoot = file.WorkRoot
	}
	if file.DeleteOnRelease != nil {
		cfg.DeleteOnRelease = *file.DeleteOnRelease
		applied.DeleteOnRelease = true
	}
	if file.WakeOnSSH != nil {
		cfg.WakeOnSSH = *file.WakeOnSSH
	}
	return applied, nil
}

func (cfg *MorphConfig) applyEnv() (MorphConfigApplied, error) {
	var applied MorphConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_MORPH_API_KEY", "MORPH_API_KEY"); ok {
		cfg.APIKey = value
		applied.APIKey = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_MORPH_API_URL"); ok {
		cfg.APIURL = value
		applied.APIURL = true
	}
	cfg.Snapshot = getenv("CRABBOX_MORPH_SNAPSHOT", cfg.Snapshot)
	if value, ok := firstNonEmptyEnv("CRABBOX_MORPH_SSH_GATEWAY_HOST"); ok {
		cfg.SSHGatewayHost = value
		applied.SSHGatewayHost = true
	}
	cfg.WorkRoot = getenv("CRABBOX_MORPH_WORK_ROOT", cfg.WorkRoot)
	if value, ok := getenvBool("CRABBOX_MORPH_DELETE_ON_RELEASE"); ok {
		cfg.DeleteOnRelease = value
		applied.DeleteOnRelease = true
	}
	if value, ok := getenvBool("CRABBOX_MORPH_WAKE_ON_SSH"); ok {
		cfg.WakeOnSSH = value
	}
	return applied, nil
}

// MorphConfigFlagValues holds parsed values; only visited flags are applied.
type MorphConfigFlagValues struct {
	APIURL          *string
	Snapshot        *string
	SSHGatewayHost  *string
	WorkRoot        *string
	DeleteOnRelease *bool
	WakeOnSSH       *bool
}

// RegisterMorphConfigFlags registers mechanical bindings without selecting a provider.
func RegisterMorphConfigFlags(fs *flag.FlagSet, defaults MorphConfig) MorphConfigFlagValues {
	return MorphConfigFlagValues{
		APIURL:          fs.String("morph-api-url", defaults.APIURL, "Morph API URL"),
		Snapshot:        fs.String("morph-snapshot", defaults.Snapshot, "Morph snapshot ID"),
		SSHGatewayHost:  fs.String("morph-ssh-gateway-host", defaults.SSHGatewayHost, "Morph SSH gateway host"),
		WorkRoot:        fs.String("morph-work-root", defaults.WorkRoot, "Morph remote Crabbox work root"),
		DeleteOnRelease: fs.Bool("morph-delete-on-release", defaults.DeleteOnRelease, "Delete Morph instances instead of pausing them on release"),
		WakeOnSSH:       fs.Bool("morph-wake-on-ssh", defaults.WakeOnSSH, "Enable Morph wake-on-ssh for paused instances"),
	}
}

// MorphConfigVisitedFlags records raw flag visits, independently of application.
type MorphConfigVisitedFlags struct {
	APIURL          bool
	SSHGatewayHost  bool
	DeleteOnRelease bool
}

// MorphConfigFlagPresence reports visits for tracked flag bindings.
func MorphConfigFlagPresence(fs *flag.FlagSet) MorphConfigVisitedFlags {
	return MorphConfigVisitedFlags{
		APIURL:          flagWasSet(fs, "morph-api-url"),
		SSHGatewayHost:  flagWasSet(fs, "morph-ssh-gateway-host"),
		DeleteOnRelease: flagWasSet(fs, "morph-delete-on-release"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values MorphConfigFlagValues) Apply(cfg *MorphConfig, fs *flag.FlagSet) MorphConfigApplied {
	var applied MorphConfigApplied
	visited := MorphConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.APIURL = true
	}
	if flagWasSet(fs, "morph-snapshot") {
		cfg.Snapshot = *values.Snapshot
	}
	if visited.SSHGatewayHost {
		cfg.SSHGatewayHost = *values.SSHGatewayHost
		applied.SSHGatewayHost = true
	}
	if flagWasSet(fs, "morph-work-root") {
		cfg.WorkRoot = *values.WorkRoot
	}
	if visited.DeleteOnRelease {
		cfg.DeleteOnRelease = *values.DeleteOnRelease
		applied.DeleteOnRelease = true
	}
	if flagWasSet(fs, "morph-wake-on-ssh") {
		cfg.WakeOnSSH = *values.WakeOnSSH
	}
	return applied
}
