// Code generated by scripts/configgen from config_fastapi_cloud.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileFastAPICloudConfig struct {
	APIURL string `yaml:"apiUrl,omitempty"`
	AppID  string `yaml:"appId,omitempty"`
	TeamID string `yaml:"teamId,omitempty"`
}

const FastAPICloudConfigDefaultAPIURL string = "https://api.fastapicloud.com/api/v1"

func defaultFastAPICloudConfig() FastAPICloudConfig {
	return FastAPICloudConfig{
		APIURL: FastAPICloudConfigDefaultAPIURL,
	}
}

// FastAPICloudConfigApplied records accepted assignments during one application.
type FastAPICloudConfigApplied struct {
	InputAccepted bool
	Token         bool
	APIURL        bool
}

func (cfg *FastAPICloudConfig) applyFile(file *fileFastAPICloudConfig) (FastAPICloudConfigApplied, error) {
	var applied FastAPICloudConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "fastapi-cloud")
	return applied, err
}

func (cfg *FastAPICloudConfig) applyEnv() (FastAPICloudConfigApplied, error) {
	var applied FastAPICloudConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 4)
	return applied, err
}

// FastAPICloudConfigFlagValues holds parsed values; only visited flags are applied.
type FastAPICloudConfigFlagValues struct {
	APIURL *string
	AppID  *string
	TeamID *string
}

// RegisterFastAPICloudConfigFlags registers mechanical bindings without selecting a provider.
func RegisterFastAPICloudConfigFlags(fs *flag.FlagSet, defaults FastAPICloudConfig) FastAPICloudConfigFlagValues {
	var values FastAPICloudConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// FastAPICloudConfigVisitedFlags records raw flag visits, independently of application.
type FastAPICloudConfigVisitedFlags struct {
	APIURL bool
}

// FastAPICloudConfigFlagPresence reports visits for tracked flag bindings.
func FastAPICloudConfigFlagPresence(fs *flag.FlagSet) FastAPICloudConfigVisitedFlags {
	var visited FastAPICloudConfigVisitedFlags
	recordConfigFlagVisits[FastAPICloudConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values FastAPICloudConfigFlagValues) Apply(cfg *FastAPICloudConfig, fs *flag.FlagSet) (FastAPICloudConfigApplied, error) {
	var applied FastAPICloudConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
