// Code generated by scripts/configgen from config_upstash_box.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileUpstashBoxConfig struct {
	BaseURL   string `yaml:"baseUrl,omitempty"`
	Runtime   string `yaml:"runtime,omitempty"`
	Size      string `yaml:"size,omitempty"`
	Workdir   string `yaml:"workdir,omitempty"`
	KeepAlive *bool  `yaml:"keepAlive,omitempty"`
}

const UpstashBoxConfigDefaultBaseURL string = "https://us-east-1.box.upstash.com"
const UpstashBoxConfigDefaultRuntime string = "node"
const UpstashBoxConfigDefaultSize string = "small"
const UpstashBoxConfigDefaultWorkdir string = "/workspace/home/crabbox"

func defaultUpstashBoxConfig() UpstashBoxConfig {
	return UpstashBoxConfig{
		BaseURL: UpstashBoxConfigDefaultBaseURL,
		Runtime: UpstashBoxConfigDefaultRuntime,
		Size:    UpstashBoxConfigDefaultSize,
		Workdir: UpstashBoxConfigDefaultWorkdir,
	}
}

// UpstashBoxConfigApplied records accepted assignments during one application.
type UpstashBoxConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	BaseURL       bool
}

func (cfg *UpstashBoxConfig) applyFile(file *fileUpstashBoxConfig) (UpstashBoxConfigApplied, error) {
	var applied UpstashBoxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "upstash-box")
	return applied, err
}

func (cfg *UpstashBoxConfig) applyEnv() (UpstashBoxConfigApplied, error) {
	var applied UpstashBoxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// UpstashBoxConfigFlagValues holds parsed values; only visited flags are applied.
type UpstashBoxConfigFlagValues struct {
	BaseURL   *string
	Runtime   *string
	Size      *string
	Workdir   *string
	KeepAlive *bool
}

// RegisterUpstashBoxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterUpstashBoxConfigFlags(fs *flag.FlagSet, defaults UpstashBoxConfig) UpstashBoxConfigFlagValues {
	var values UpstashBoxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// UpstashBoxConfigVisitedFlags records raw flag visits, independently of application.
type UpstashBoxConfigVisitedFlags struct {
	BaseURL bool
}

// UpstashBoxConfigFlagPresence reports visits for tracked flag bindings.
func UpstashBoxConfigFlagPresence(fs *flag.FlagSet) UpstashBoxConfigVisitedFlags {
	var visited UpstashBoxConfigVisitedFlags
	recordConfigFlagVisits[UpstashBoxConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values UpstashBoxConfigFlagValues) Apply(cfg *UpstashBoxConfig, fs *flag.FlagSet) (UpstashBoxConfigApplied, error) {
	var applied UpstashBoxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
