// Code generated by scripts/configgen from config_github_codespaces.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileGitHubCodespacesConfig struct {
	APIURL           string `yaml:"apiUrl,omitempty"`
	GHPath           string `yaml:"ghPath,omitempty"`
	Repo             string `yaml:"repo,omitempty"`
	Ref              string `yaml:"ref,omitempty"`
	Machine          string `yaml:"machine,omitempty"`
	DevcontainerPath string `yaml:"devcontainerPath,omitempty"`
	WorkingDirectory string `yaml:"workingDirectory,omitempty"`
	Geo              string `yaml:"geo,omitempty"`
	IdleTimeout      string `yaml:"idleTimeout,omitempty"`
	RetentionPeriod  string `yaml:"retentionPeriod,omitempty"`
	DeleteOnRelease  *bool  `yaml:"deleteOnRelease,omitempty"`
	WorkRoot         string `yaml:"workRoot,omitempty"`
}

const GitHubCodespacesConfigDefaultGHPath string = "gh"
const GitHubCodespacesConfigDefaultMachine string = "basicLinux32gb"
const GitHubCodespacesConfigDefaultIdleTimeout time.Duration = 1800 * time.Second
const GitHubCodespacesConfigDefaultRetentionPeriod time.Duration = 604800 * time.Second
const GitHubCodespacesConfigDefaultDeleteOnRelease bool = true
const GitHubCodespacesConfigDefaultWorkRoot string = "/workspaces/crabbox"

func defaultGitHubCodespacesConfig() GitHubCodespacesConfig {
	return GitHubCodespacesConfig{
		GHPath:          GitHubCodespacesConfigDefaultGHPath,
		Machine:         GitHubCodespacesConfigDefaultMachine,
		IdleTimeout:     GitHubCodespacesConfigDefaultIdleTimeout,
		RetentionPeriod: GitHubCodespacesConfigDefaultRetentionPeriod,
		DeleteOnRelease: GitHubCodespacesConfigDefaultDeleteOnRelease,
		WorkRoot:        GitHubCodespacesConfigDefaultWorkRoot,
	}
}

// GitHubCodespacesConfigApplied records accepted assignments during one application.
type GitHubCodespacesConfigApplied struct {
	InputAccepted   bool
	GHPath          bool
	Machine         bool
	RetentionPeriod bool
	DeleteOnRelease bool
	WorkRoot        bool
}

func (cfg *GitHubCodespacesConfig) applyFile(file *fileGitHubCodespacesConfig, trusted bool) (GitHubCodespacesConfigApplied, error) {
	var applied GitHubCodespacesConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "github-codespaces")
	return applied, err
}

func (cfg *GitHubCodespacesConfig) applyEnv() (GitHubCodespacesConfigApplied, error) {
	var applied GitHubCodespacesConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 12)
	return applied, err
}

// GitHubCodespacesConfigFlagValues holds parsed values; only visited flags are applied.
type GitHubCodespacesConfigFlagValues struct {
	GHPath           *string
	Repo             *string
	Ref              *string
	Machine          *string
	DevcontainerPath *string
	WorkingDirectory *string
	Geo              *string
	IdleTimeout      *time.Duration
	RetentionPeriod  *time.Duration
	DeleteOnRelease  *bool
	WorkRoot         *string
}

// RegisterGitHubCodespacesConfigFlags registers mechanical bindings without selecting a provider.
func RegisterGitHubCodespacesConfigFlags(fs *flag.FlagSet, defaults GitHubCodespacesConfig) GitHubCodespacesConfigFlagValues {
	var values GitHubCodespacesConfigFlagValues
	registerConfigFlags(fs, defaults, &values, "Repo", "Ref", "Machine", "DevcontainerPath", "WorkingDirectory", "Geo", "IdleTimeout", "RetentionPeriod", "DeleteOnRelease", "GHPath", "WorkRoot")
	return values
}

// GitHubCodespacesConfigVisitedFlags records raw flag visits, independently of application.
type GitHubCodespacesConfigVisitedFlags struct {
	GHPath          bool
	Machine         bool
	RetentionPeriod bool
	DeleteOnRelease bool
	WorkRoot        bool
}

// GitHubCodespacesConfigFlagPresence reports visits for tracked flag bindings.
func GitHubCodespacesConfigFlagPresence(fs *flag.FlagSet) GitHubCodespacesConfigVisitedFlags {
	var visited GitHubCodespacesConfigVisitedFlags
	recordConfigFlagVisits[GitHubCodespacesConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values GitHubCodespacesConfigFlagValues) Apply(cfg *GitHubCodespacesConfig, fs *flag.FlagSet) (GitHubCodespacesConfigApplied, error) {
	var applied GitHubCodespacesConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
