// Code generated by scripts/configgen from config_nomad.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileNomadConfig struct {
	Address           string   `yaml:"address,omitempty"`
	Region            string   `yaml:"region,omitempty"`
	Namespace         string   `yaml:"namespace,omitempty"`
	TokenEnv          string   `yaml:"tokenEnv,omitempty"`
	CACert            string   `yaml:"caCert,omitempty"`
	CAPath            string   `yaml:"caPath,omitempty"`
	ClientCert        string   `yaml:"clientCert,omitempty"`
	ClientKey         string   `yaml:"clientKey,omitempty"`
	TLSServerName     string   `yaml:"tlsServerName,omitempty"`
	SkipVerify        *bool    `yaml:"skipVerify,omitempty"`
	Task              *string  `yaml:"task,omitempty"`
	Driver            *string  `yaml:"driver,omitempty"`
	Image             *string  `yaml:"image,omitempty"`
	Workdir           *string  `yaml:"workdir,omitempty"`
	JobSpecTemplate   string   `yaml:"jobspecTemplate,omitempty"`
	NodePool          string   `yaml:"nodePool,omitempty"`
	Datacenters       []string `yaml:"datacenters,omitempty"`
	CPU               *int     `yaml:"cpu,omitempty"`
	MemoryMB          *int     `yaml:"memoryMB,omitempty"`
	DiskMB            *int     `yaml:"diskMB,omitempty"`
	AllocReadyTimeout string   `yaml:"allocReadyTimeout,omitempty"`
	EvalTimeout       string   `yaml:"evalTimeout,omitempty"`
	ExecTimeoutSecs   *int     `yaml:"execTimeoutSecs,omitempty"`
}

const NomadConfigDefaultTokenEnv string = "NOMAD_TOKEN"
const NomadConfigDefaultTask string = "crabbox"
const NomadConfigDefaultDriver string = "docker"
const NomadConfigDefaultImage string = "ubuntu:24.04"
const NomadConfigDefaultWorkdir string = "/workspace/crabbox"
const NomadConfigDefaultCPU int = 1000
const NomadConfigDefaultMemoryMB int = 2048
const NomadConfigDefaultDiskMB int = 1024
const NomadConfigDefaultAllocReadyTimeout time.Duration = 300 * time.Second
const NomadConfigDefaultEvalTimeout time.Duration = 300 * time.Second
const NomadConfigDefaultExecTimeoutSecs int = 600

func defaultNomadConfig() NomadConfig {
	return NomadConfig{
		TokenEnv:          NomadConfigDefaultTokenEnv,
		Task:              NomadConfigDefaultTask,
		Driver:            NomadConfigDefaultDriver,
		Image:             NomadConfigDefaultImage,
		Workdir:           NomadConfigDefaultWorkdir,
		CPU:               NomadConfigDefaultCPU,
		MemoryMB:          NomadConfigDefaultMemoryMB,
		DiskMB:            NomadConfigDefaultDiskMB,
		AllocReadyTimeout: NomadConfigDefaultAllocReadyTimeout,
		EvalTimeout:       NomadConfigDefaultEvalTimeout,
		ExecTimeoutSecs:   NomadConfigDefaultExecTimeoutSecs,
	}
}

// NomadConfigApplied records accepted assignments during one application.
type NomadConfigApplied struct {
	InputAccepted   bool
	Address         bool
	TokenEnv        bool
	CACert          bool
	CAPath          bool
	ClientCert      bool
	ClientKey       bool
	JobSpecTemplate bool
}

func (cfg *NomadConfig) applyFile(file *fileNomadConfig, trusted bool) (NomadConfigApplied, error) {
	var applied NomadConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "nomad")
	return applied, err
}

func (cfg *NomadConfig) applyEnv() (NomadConfigApplied, error) {
	var applied NomadConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 23)
	return applied, err
}

// NomadConfigFlagValues holds parsed values; only visited flags are applied.
type NomadConfigFlagValues struct {
	Address           *string
	Region            *string
	Namespace         *string
	TokenEnv          *string
	CACert            *string
	CAPath            *string
	ClientCert        *string
	ClientKey         *string
	TLSServerName     *string
	SkipVerify        *bool
	Task              *string
	Driver            *string
	Image             *string
	Workdir           *string
	JobSpecTemplate   *string
	NodePool          *string
	Datacenters       *string
	CPU               *int
	MemoryMB          *int
	DiskMB            *int
	AllocReadyTimeout *string
	EvalTimeout       *string
	ExecTimeoutSecs   *int
}

// RegisterNomadConfigFlags registers mechanical bindings without selecting a provider.
func RegisterNomadConfigFlags(fs *flag.FlagSet, defaults NomadConfig) NomadConfigFlagValues {
	var values NomadConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// NomadConfigVisitedFlags records raw flag visits, independently of application.
type NomadConfigVisitedFlags struct {
	Address         bool
	TokenEnv        bool
	CACert          bool
	CAPath          bool
	ClientCert      bool
	ClientKey       bool
	JobSpecTemplate bool
}

// NomadConfigFlagPresence reports visits for tracked flag bindings.
func NomadConfigFlagPresence(fs *flag.FlagSet) NomadConfigVisitedFlags {
	var visited NomadConfigVisitedFlags
	recordConfigFlagVisits[NomadConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values NomadConfigFlagValues) Apply(cfg *NomadConfig, fs *flag.FlagSet) (NomadConfigApplied, error) {
	var applied NomadConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
