// Code generated by scripts/configgen from config_cua.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCuaConfig struct {
	Image              *string `yaml:"image,omitempty"`
	Kind               *string `yaml:"kind,omitempty"`
	Region             *string `yaml:"region,omitempty"`
	Workdir            *string `yaml:"workdir,omitempty"`
	VCPUs              *int    `yaml:"vcpus,omitempty"`
	MemoryMB           *int    `yaml:"memoryMB,omitempty"`
	DiskGB             *int    `yaml:"diskGB,omitempty"`
	StartupTimeoutSecs *int    `yaml:"startupTimeoutSecs,omitempty"`
	ExecTimeoutSecs    *int    `yaml:"execTimeoutSecs,omitempty"`
	BridgeCommand      *string `yaml:"bridgeCommand,omitempty"`
	SDKPackage         *string `yaml:"sdkPackage,omitempty"`
	SDKImport          *string `yaml:"sdkImport,omitempty"`
	SDKFallbackImport  *string `yaml:"sdkFallbackImport,omitempty"`
}

const CuaConfigDefaultImage string = "ubuntu:24.04"
const CuaConfigDefaultKind string = "container"
const CuaConfigDefaultWorkdir string = "/workspace/crabbox"
const CuaConfigDefaultExecTimeoutSecs int = 600
const CuaConfigDefaultBridgeCommand string = "python3"
const CuaConfigDefaultSDKPackage string = "cua"
const CuaConfigDefaultSDKImport string = "cua"
const CuaConfigDefaultSDKFallbackImport string = "cua_sandbox"

func defaultCuaConfig() CuaConfig {
	return CuaConfig{
		Image:             CuaConfigDefaultImage,
		Kind:              CuaConfigDefaultKind,
		Workdir:           CuaConfigDefaultWorkdir,
		ExecTimeoutSecs:   CuaConfigDefaultExecTimeoutSecs,
		BridgeCommand:     CuaConfigDefaultBridgeCommand,
		SDKPackage:        CuaConfigDefaultSDKPackage,
		SDKImport:         CuaConfigDefaultSDKImport,
		SDKFallbackImport: CuaConfigDefaultSDKFallbackImport,
	}
}

// CuaConfigApplied records accepted assignments during one application.
type CuaConfigApplied struct {
	InputAccepted bool
}

func (cfg *CuaConfig) applyFile(file *fileCuaConfig, trusted bool) (CuaConfigApplied, error) {
	var applied CuaConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "cua")
	return applied, err
}

func (cfg *CuaConfig) applyEnv() (CuaConfigApplied, error) {
	var applied CuaConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 14)
	return applied, err
}

// CuaConfigFlagValues holds parsed values; only visited flags are applied.
type CuaConfigFlagValues struct {
	APIURL             *string
	Image              *string
	Kind               *string
	Region             *string
	Workdir            *string
	VCPUs              *int
	MemoryMB           *int
	DiskGB             *int
	StartupTimeoutSecs *int
	ExecTimeoutSecs    *int
	BridgeCommand      *string
	SDKPackage         *string
	SDKImport          *string
	SDKFallbackImport  *string
}

// RegisterCuaConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCuaConfigFlags(fs *flag.FlagSet, defaults CuaConfig) CuaConfigFlagValues {
	var values CuaConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CuaConfigFlagValues) Apply(cfg *CuaConfig, fs *flag.FlagSet) (CuaConfigApplied, error) {
	var applied CuaConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
