// Code generated by scripts/configgen from config_cloudflare.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCloudflareConfig struct {
	APIURL  string `yaml:"apiUrl,omitempty"`
	Token   string `yaml:"token,omitempty"`
	Workdir string `yaml:"workdir,omitempty"`
}

const CloudflareConfigDefaultWorkdir string = "/workspace/crabbox"

func defaultCloudflareConfig() CloudflareConfig {
	return CloudflareConfig{
		Workdir: CloudflareConfigDefaultWorkdir,
	}
}

// CloudflareConfigApplied records accepted assignments during one application.
type CloudflareConfigApplied struct {
	APIURL bool
	Token  bool
}

func (cfg *CloudflareConfig) applyFile(file *fileCloudflareConfig) (CloudflareConfigApplied, error) {
	var applied CloudflareConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.APIURL != "" {
		cfg.APIURL = file.APIURL
		applied.APIURL = true
	}
	if file.Token != "" {
		cfg.Token = file.Token
		applied.Token = true
	}
	if file.Workdir != "" {
		cfg.Workdir = file.Workdir
	}
	return applied, nil
}

func (cfg *CloudflareConfig) applyEnv() (CloudflareConfigApplied, error) {
	var applied CloudflareConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_CLOUDFLARE_RUNNER_URL"); ok {
		cfg.APIURL = value
		applied.APIURL = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_CLOUDFLARE_RUNNER_TOKEN"); ok {
		cfg.Token = value
		applied.Token = true
	}
	cfg.Workdir = getenv("CRABBOX_CLOUDFLARE_WORKDIR", cfg.Workdir)
	return applied, nil
}

// CloudflareConfigFlagValues holds parsed values; only visited flags are applied.
type CloudflareConfigFlagValues struct {
	APIURL  *string
	Workdir *string
}

// RegisterCloudflareConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCloudflareConfigFlags(fs *flag.FlagSet, defaults CloudflareConfig) CloudflareConfigFlagValues {
	return CloudflareConfigFlagValues{
		APIURL:  fs.String("cloudflare-url", defaults.APIURL, "Cloudflare runner API URL"),
		Workdir: fs.String("cloudflare-workdir", defaults.Workdir, "Absolute working directory inside the Cloudflare workspace"),
	}
}

// CloudflareConfigVisitedFlags records raw flag visits, independently of application.
type CloudflareConfigVisitedFlags struct {
	APIURL bool
}

// CloudflareConfigFlagPresence reports visits for tracked flag bindings.
func CloudflareConfigFlagPresence(fs *flag.FlagSet) CloudflareConfigVisitedFlags {
	return CloudflareConfigVisitedFlags{
		APIURL: flagWasSet(fs, "cloudflare-url"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CloudflareConfigFlagValues) Apply(cfg *CloudflareConfig, fs *flag.FlagSet) CloudflareConfigApplied {
	var applied CloudflareConfigApplied
	visited := CloudflareConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.APIURL = true
	}
	if flagWasSet(fs, "cloudflare-workdir") {
		cfg.Workdir = *values.Workdir
	}
	return applied
}
