// Code generated by scripts/configgen from config_scaleway.go; DO NOT EDIT.

package cli

import (
	"flag"
	"os"
)

type fileScalewayConfig struct {
	Region         string   `yaml:"region,omitempty"`
	Zone           string   `yaml:"zone,omitempty"`
	Image          string   `yaml:"image,omitempty"`
	Type           string   `yaml:"type,omitempty"`
	ProjectID      string   `yaml:"projectId,omitempty"`
	OrganizationID string   `yaml:"organizationId,omitempty"`
	SecurityGroup  string   `yaml:"securityGroup,omitempty"`
	SSHCIDRs       []string `yaml:"sshCIDRs,omitempty"`
}

const ScalewayConfigDefaultRegion string = "fr-par"
const ScalewayConfigDefaultZone string = "fr-par-1"
const ScalewayConfigDefaultImage string = "ubuntu_noble"
const ScalewayConfigDefaultType string = "DEV1-S"

func defaultScalewayConfig() ScalewayConfig {
	return ScalewayConfig{
		Region: ScalewayConfigDefaultRegion,
		Zone:   ScalewayConfigDefaultZone,
		Image:  ScalewayConfigDefaultImage,
		Type:   ScalewayConfigDefaultType,
	}
}

// ScalewayConfigApplied records accepted assignments during one application.
type ScalewayConfigApplied struct {
	Region bool
	Zone   bool
	Image  bool
	Type   bool
}

func (cfg *ScalewayConfig) applyFile(file *fileScalewayConfig) (ScalewayConfigApplied, error) {
	var applied ScalewayConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.Region != "" {
		cfg.Region = file.Region
		applied.Region = true
	}
	if file.Zone != "" {
		cfg.Zone = file.Zone
		applied.Zone = true
	}
	if file.Image != "" {
		cfg.Image = file.Image
		applied.Image = true
	}
	if file.Type != "" {
		cfg.Type = file.Type
		applied.Type = true
	}
	if file.ProjectID != "" {
		cfg.ProjectID = file.ProjectID
	}
	if file.OrganizationID != "" {
		cfg.OrganizationID = file.OrganizationID
	}
	if file.SecurityGroup != "" {
		cfg.SecurityGroup = file.SecurityGroup
	}
	if len(file.SSHCIDRs) > 0 {
		cfg.SSHCIDRs = file.SSHCIDRs
	}
	return applied, nil
}

func (cfg *ScalewayConfig) applyEnv() (ScalewayConfigApplied, error) {
	var applied ScalewayConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_SCALEWAY_REGION"); ok {
		cfg.Region = value
		applied.Region = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_SCALEWAY_ZONE"); ok {
		cfg.Zone = value
		applied.Zone = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_SCALEWAY_IMAGE"); ok {
		cfg.Image = value
		applied.Image = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_SCALEWAY_TYPE"); ok {
		cfg.Type = value
		applied.Type = true
	}
	cfg.ProjectID = getenv("CRABBOX_SCALEWAY_PROJECT_ID", cfg.ProjectID)
	cfg.OrganizationID = getenv("CRABBOX_SCALEWAY_ORGANIZATION_ID", cfg.OrganizationID)
	cfg.SecurityGroup = getenv("CRABBOX_SCALEWAY_SECURITY_GROUP", cfg.SecurityGroup)
	if value := os.Getenv("CRABBOX_SCALEWAY_SSH_CIDRS"); value != "" {
		cfg.SSHCIDRs = splitCommaList(value)
	}
	return applied, nil
}

// ScalewayConfigFlagValues holds parsed values; only visited flags are applied.
type ScalewayConfigFlagValues struct {
	Region         *string
	Zone           *string
	Image          *string
	Type           *string
	ProjectID      *string
	OrganizationID *string
	SecurityGroup  *string
	SSHCIDRs       *string
}

// RegisterScalewayConfigFlags registers mechanical bindings without selecting a provider.
func RegisterScalewayConfigFlags(fs *flag.FlagSet, defaults ScalewayConfig) ScalewayConfigFlagValues {
	return ScalewayConfigFlagValues{
		Region:         fs.String("scaleway-region", defaults.Region, "Scaleway region"),
		Zone:           fs.String("scaleway-zone", defaults.Zone, "Scaleway zone"),
		Image:          fs.String("scaleway-image", defaults.Image, "Scaleway image label or ID"),
		Type:           fs.String("scaleway-type", defaults.Type, "Scaleway Instances commercial type"),
		ProjectID:      fs.String("scaleway-project-id", defaults.ProjectID, "Scaleway project ID"),
		OrganizationID: fs.String("scaleway-organization-id", defaults.OrganizationID, "Scaleway organization ID"),
		SecurityGroup:  fs.String("scaleway-security-group", defaults.SecurityGroup, "Scaleway security group ID"),
		SSHCIDRs:       fs.String("scaleway-ssh-cidrs", "", "comma-separated Scaleway SSH source CIDRs"),
	}
}

// ScalewayConfigVisitedFlags records raw flag visits, independently of application.
type ScalewayConfigVisitedFlags struct {
	Region bool
	Zone   bool
	Image  bool
	Type   bool
}

// ScalewayConfigFlagPresence reports visits for tracked flag bindings.
func ScalewayConfigFlagPresence(fs *flag.FlagSet) ScalewayConfigVisitedFlags {
	return ScalewayConfigVisitedFlags{
		Region: flagWasSet(fs, "scaleway-region"),
		Zone:   flagWasSet(fs, "scaleway-zone"),
		Image:  flagWasSet(fs, "scaleway-image"),
		Type:   flagWasSet(fs, "scaleway-type"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values ScalewayConfigFlagValues) Apply(cfg *ScalewayConfig, fs *flag.FlagSet) ScalewayConfigApplied {
	var applied ScalewayConfigApplied
	visited := ScalewayConfigFlagPresence(fs)
	if visited.Region {
		cfg.Region = *values.Region
		applied.Region = true
	}
	if visited.Zone {
		cfg.Zone = *values.Zone
		applied.Zone = true
	}
	if visited.Image {
		cfg.Image = *values.Image
		applied.Image = true
	}
	if visited.Type {
		cfg.Type = *values.Type
		applied.Type = true
	}
	if flagWasSet(fs, "scaleway-project-id") {
		cfg.ProjectID = *values.ProjectID
	}
	if flagWasSet(fs, "scaleway-organization-id") {
		cfg.OrganizationID = *values.OrganizationID
	}
	if flagWasSet(fs, "scaleway-security-group") {
		cfg.SecurityGroup = *values.SecurityGroup
	}
	if flagWasSet(fs, "scaleway-ssh-cidrs") {
		cfg.SSHCIDRs = splitCommaList(*values.SSHCIDRs)
		if len(cfg.SSHCIDRs) == 0 {
			cfg.SSHCIDRs = nil
		}
	}
	return applied
}
