// Code generated by scripts/configgen from config_local_container.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileLocalContainerConfig struct {
	Runtime      string `yaml:"runtime,omitempty"`
	Image        string `yaml:"image,omitempty"`
	User         string `yaml:"user,omitempty"`
	WorkRoot     string `yaml:"workRoot,omitempty"`
	CPUs         int    `yaml:"cpus,omitempty"`
	Memory       string `yaml:"memory,omitempty"`
	Network      string `yaml:"network,omitempty"`
	DockerSocket *bool  `yaml:"dockerSocket,omitempty"`
	NoHostname   *bool  `yaml:"noHostname,omitempty"`
}

const LocalContainerConfigDefaultRuntime string = "docker"
const LocalContainerConfigDefaultUser string = "crabbox"
const LocalContainerConfigDefaultNetwork string = "bridge"

func defaultLocalContainerConfig() LocalContainerConfig {
	return LocalContainerConfig{
		Runtime: LocalContainerConfigDefaultRuntime,
		User:    LocalContainerConfigDefaultUser,
		Network: LocalContainerConfigDefaultNetwork,
	}
}

// LocalContainerConfigApplied records accepted assignments during one application.
type LocalContainerConfigApplied struct {
	InputAccepted bool
	Runtime       bool
	Image         bool
	WorkRoot      bool
}

func (cfg *LocalContainerConfig) applyFile(file *fileLocalContainerConfig) (LocalContainerConfigApplied, error) {
	var applied LocalContainerConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "local-container")
	return applied, err
}

func (cfg *LocalContainerConfig) applyEnv() (LocalContainerConfigApplied, error) {
	var applied LocalContainerConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 10)
	return applied, err
}

// LocalContainerConfigFlagValues holds parsed values; only visited flags are applied.
type LocalContainerConfigFlagValues struct {
	Runtime      *string
	Image        *string
	User         *string
	WorkRoot     *string
	CPUs         *int
	Memory       *string
	Network      *string
	DockerSocket *bool
	Volumes      *[]string
}

// RegisterLocalContainerConfigFlags registers mechanical bindings without selecting a provider.
func RegisterLocalContainerConfigFlags(fs *flag.FlagSet, defaults LocalContainerConfig) LocalContainerConfigFlagValues {
	var values LocalContainerConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// LocalContainerConfigVisitedFlags records raw flag visits, independently of application.
type LocalContainerConfigVisitedFlags struct {
	Runtime      bool
	Image        bool
	User         bool
	WorkRoot     bool
	CPUs         bool
	Memory       bool
	Network      bool
	DockerSocket bool
	Volumes      bool
}

// LocalContainerConfigFlagPresence reports visits for tracked flag bindings.
func LocalContainerConfigFlagPresence(fs *flag.FlagSet) LocalContainerConfigVisitedFlags {
	var visited LocalContainerConfigVisitedFlags
	recordConfigFlagVisits[LocalContainerConfig](fs, &visited)
	return visited
}
