// Code generated by scripts/configgen from config_static.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileStaticConfig struct {
	ID       string `yaml:"id,omitempty"`
	Name     string `yaml:"name,omitempty"`
	Host     string `yaml:"host,omitempty"`
	User     string `yaml:"user,omitempty"`
	Port     string `yaml:"port,omitempty"`
	WorkRoot string `yaml:"workRoot,omitempty"`
}

func defaultStaticConfig() StaticConfig {
	return StaticConfig{}
}

// StaticConfigApplied records accepted assignments during one application.
type StaticConfigApplied struct {
	InputAccepted bool
	Host          bool
}

func (cfg *StaticConfig) applyFile(file *fileStaticConfig) (StaticConfigApplied, error) {
	var applied StaticConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "ssh")
	return applied, err
}

func (cfg *StaticConfig) applyEnv() (StaticConfigApplied, error) {
	var applied StaticConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// StaticConfigFlagValues holds parsed values; only visited flags are applied.
type StaticConfigFlagValues struct {
	Host     *string
	User     *string
	Port     *string
	WorkRoot *string
}

// RegisterStaticConfigFlags registers mechanical bindings without selecting a provider.
func RegisterStaticConfigFlags(fs *flag.FlagSet, defaults StaticConfig) StaticConfigFlagValues {
	var values StaticConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// StaticConfigVisitedFlags records raw flag visits, independently of application.
type StaticConfigVisitedFlags struct {
	Host bool
}

// StaticConfigFlagPresence reports visits for tracked flag bindings.
func StaticConfigFlagPresence(fs *flag.FlagSet) StaticConfigVisitedFlags {
	var visited StaticConfigVisitedFlags
	recordConfigFlagVisits[StaticConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values StaticConfigFlagValues) Apply(cfg *StaticConfig, fs *flag.FlagSet) (StaticConfigApplied, error) {
	var applied StaticConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
