// Code generated by scripts/configgen from config_blaxel.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileBlaxelConfig struct {
	APIURL          string  `yaml:"apiUrl,omitempty"`
	Workspace       string  `yaml:"workspace,omitempty"`
	Region          string  `yaml:"region,omitempty"`
	Image           *string `yaml:"image,omitempty"`
	MemoryMB        *int    `yaml:"memoryMB,omitempty"`
	TTL             string  `yaml:"ttl,omitempty"`
	IdleTTL         string  `yaml:"idleTTL,omitempty"`
	Workdir         *string `yaml:"workdir,omitempty"`
	ExecTimeoutSecs *int    `yaml:"execTimeoutSecs,omitempty"`
	ForgetMissing   *bool   `yaml:"forgetMissing,omitempty"`
}

const BlaxelConfigDefaultAPIURL string = "https://api.blaxel.ai"
const BlaxelConfigDefaultImage string = "ubuntu:24.04"
const BlaxelConfigDefaultWorkdir string = "/workspace/crabbox"
const BlaxelConfigDefaultExecTimeoutSecs int = 600

func defaultBlaxelConfig() BlaxelConfig {
	return BlaxelConfig{
		APIURL:          BlaxelConfigDefaultAPIURL,
		Image:           BlaxelConfigDefaultImage,
		Workdir:         BlaxelConfigDefaultWorkdir,
		ExecTimeoutSecs: BlaxelConfigDefaultExecTimeoutSecs,
	}
}

// BlaxelConfigApplied records accepted assignments during one application.
type BlaxelConfigApplied struct {
	InputAccepted bool
}

func (cfg *BlaxelConfig) applyFile(file *fileBlaxelConfig, trusted bool) (BlaxelConfigApplied, error) {
	var applied BlaxelConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "blaxel")
	return applied, err
}

func (cfg *BlaxelConfig) applyEnv() (BlaxelConfigApplied, error) {
	var applied BlaxelConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 11)
	return applied, err
}

// BlaxelConfigFlagValues holds parsed values; only visited flags are applied.
type BlaxelConfigFlagValues struct {
	APIURL          *string
	Workspace       *string
	Region          *string
	Image           *string
	MemoryMB        *int
	TTL             *string
	IdleTTL         *string
	Workdir         *string
	ExecTimeoutSecs *int
	ForgetMissing   *bool
}

// RegisterBlaxelConfigFlags registers mechanical bindings without selecting a provider.
func RegisterBlaxelConfigFlags(fs *flag.FlagSet, defaults BlaxelConfig) BlaxelConfigFlagValues {
	var values BlaxelConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values BlaxelConfigFlagValues) Apply(cfg *BlaxelConfig, fs *flag.FlagSet) (BlaxelConfigApplied, error) {
	var applied BlaxelConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
