// Code generated by scripts/configgen from config_vercel_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileVercelSandboxConfig struct {
	Runtime         *string   `yaml:"runtime,omitempty"`
	Workdir         *string   `yaml:"workdir,omitempty"`
	ProjectID       *string   `yaml:"projectId,omitempty"`
	TeamID          *string   `yaml:"teamId,omitempty"`
	Scope           *string   `yaml:"scope,omitempty"`
	VCPUs           *float64  `yaml:"vcpus,omitempty"`
	TimeoutSecs     *int      `yaml:"timeoutSecs,omitempty"`
	ExecTimeoutSecs *int      `yaml:"execTimeoutSecs,omitempty"`
	Persistent      *bool     `yaml:"persistent,omitempty"`
	Snapshot        *string   `yaml:"snapshot,omitempty"`
	SnapshotMode    *string   `yaml:"snapshotMode,omitempty"`
	NetworkPolicy   *string   `yaml:"networkPolicy,omitempty"`
	NetworkAllow    *[]string `yaml:"networkAllow,omitempty"`
	NetworkDeny     *[]string `yaml:"networkDeny,omitempty"`
	Ports           *[]string `yaml:"ports,omitempty"`
	ForgetMissing   *bool     `yaml:"forgetMissing,omitempty"`
}

const VercelSandboxConfigDefaultRuntime string = "node24"
const VercelSandboxConfigDefaultWorkdir string = "/vercel/sandbox/crabbox"
const VercelSandboxConfigDefaultExecTimeoutSecs int = 600
const VercelSandboxConfigDefaultNetworkPolicy string = "default"

func defaultVercelSandboxConfig() VercelSandboxConfig {
	return VercelSandboxConfig{
		Runtime:         VercelSandboxConfigDefaultRuntime,
		Workdir:         VercelSandboxConfigDefaultWorkdir,
		ExecTimeoutSecs: VercelSandboxConfigDefaultExecTimeoutSecs,
		NetworkPolicy:   VercelSandboxConfigDefaultNetworkPolicy,
	}
}

// VercelSandboxConfigApplied records accepted assignments during one application.
type VercelSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *VercelSandboxConfig) applyFile(file *fileVercelSandboxConfig) (VercelSandboxConfigApplied, error) {
	var applied VercelSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "vercel-sandbox")
	return applied, err
}

func (cfg *VercelSandboxConfig) applyEnv() (VercelSandboxConfigApplied, error) {
	var applied VercelSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 16)
	return applied, err
}

// VercelSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type VercelSandboxConfigFlagValues struct {
	Runtime         *string
	Workdir         *string
	ProjectID       *string
	TeamID          *string
	Scope           *string
	VCPUs           *float64
	TimeoutSecs     *int
	ExecTimeoutSecs *int
	Persistent      *bool
	Snapshot        *string
	SnapshotMode    *string
	NetworkPolicy   *string
	NetworkAllow    *string
	NetworkDeny     *string
	Ports           *string
	ForgetMissing   *bool
}

// RegisterVercelSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterVercelSandboxConfigFlags(fs *flag.FlagSet, defaults VercelSandboxConfig) VercelSandboxConfigFlagValues {
	var values VercelSandboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values VercelSandboxConfigFlagValues) Apply(cfg *VercelSandboxConfig, fs *flag.FlagSet) (VercelSandboxConfigApplied, error) {
	var applied VercelSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
