// Code generated by scripts/configgen from config_upstash_box.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileUpstashBoxConfig struct {
	BaseURL   string `yaml:"baseUrl,omitempty"`
	Runtime   string `yaml:"runtime,omitempty"`
	Size      string `yaml:"size,omitempty"`
	Workdir   string `yaml:"workdir,omitempty"`
	KeepAlive *bool  `yaml:"keepAlive,omitempty"`
}

const UpstashBoxConfigDefaultBaseURL string = "https://us-east-1.box.upstash.com"
const UpstashBoxConfigDefaultRuntime string = "node"
const UpstashBoxConfigDefaultSize string = "small"
const UpstashBoxConfigDefaultWorkdir string = "/workspace/home/crabbox"

func defaultUpstashBoxConfig() UpstashBoxConfig {
	return UpstashBoxConfig{
		BaseURL: UpstashBoxConfigDefaultBaseURL,
		Runtime: UpstashBoxConfigDefaultRuntime,
		Size:    UpstashBoxConfigDefaultSize,
		Workdir: UpstashBoxConfigDefaultWorkdir,
	}
}

// UpstashBoxConfigApplied records accepted assignments during one application.
type UpstashBoxConfigApplied struct {
	APIKey  bool
	BaseURL bool
}

func (cfg *UpstashBoxConfig) applyFile(file *fileUpstashBoxConfig) (UpstashBoxConfigApplied, error) {
	var applied UpstashBoxConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.BaseURL != "" {
		cfg.BaseURL = file.BaseURL
		applied.BaseURL = true
	}
	if file.Runtime != "" {
		cfg.Runtime = file.Runtime
	}
	if file.Size != "" {
		cfg.Size = file.Size
	}
	if file.Workdir != "" {
		cfg.Workdir = file.Workdir
	}
	if file.KeepAlive != nil {
		cfg.KeepAlive = *file.KeepAlive
	}
	return applied, nil
}

func (cfg *UpstashBoxConfig) applyEnv() (UpstashBoxConfigApplied, error) {
	var applied UpstashBoxConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_UPSTASH_BOX_API_KEY", "UPSTASH_BOX_API_KEY"); ok {
		cfg.APIKey = value
		applied.APIKey = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_UPSTASH_BOX_BASE_URL", "UPSTASH_BOX_BASE_URL"); ok {
		cfg.BaseURL = value
		applied.BaseURL = true
	}
	cfg.Runtime = getenv("CRABBOX_UPSTASH_BOX_RUNTIME", cfg.Runtime)
	cfg.Size = getenv("CRABBOX_UPSTASH_BOX_SIZE", cfg.Size)
	cfg.Workdir = getenv("CRABBOX_UPSTASH_BOX_WORKDIR", cfg.Workdir)
	if value, ok := getenvBool("CRABBOX_UPSTASH_BOX_KEEP_ALIVE"); ok {
		cfg.KeepAlive = value
	}
	return applied, nil
}

// UpstashBoxConfigFlagValues holds parsed values; only visited flags are applied.
type UpstashBoxConfigFlagValues struct {
	BaseURL   *string
	Runtime   *string
	Size      *string
	Workdir   *string
	KeepAlive *bool
}

// RegisterUpstashBoxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterUpstashBoxConfigFlags(fs *flag.FlagSet, defaults UpstashBoxConfig) UpstashBoxConfigFlagValues {
	return UpstashBoxConfigFlagValues{
		BaseURL:   fs.String("upstash-box-base-url", defaults.BaseURL, "Upstash Box API base URL"),
		Runtime:   fs.String("upstash-box-runtime", defaults.Runtime, "Upstash Box runtime: node, python, golang, ruby, or rust"),
		Size:      fs.String("upstash-box-size", defaults.Size, "Upstash Box size: small, medium, or large"),
		Workdir:   fs.String("upstash-box-workdir", defaults.Workdir, "absolute working directory inside the Upstash Box"),
		KeepAlive: fs.Bool("upstash-box-keep-alive", defaults.KeepAlive, "create Upstash boxes with keepAlive enabled"),
	}
}

// UpstashBoxConfigVisitedFlags records raw flag visits, independently of application.
type UpstashBoxConfigVisitedFlags struct {
	BaseURL bool
}

// UpstashBoxConfigFlagPresence reports visits for tracked flag bindings.
func UpstashBoxConfigFlagPresence(fs *flag.FlagSet) UpstashBoxConfigVisitedFlags {
	return UpstashBoxConfigVisitedFlags{
		BaseURL: flagWasSet(fs, "upstash-box-base-url"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values UpstashBoxConfigFlagValues) Apply(cfg *UpstashBoxConfig, fs *flag.FlagSet) UpstashBoxConfigApplied {
	var applied UpstashBoxConfigApplied
	visited := UpstashBoxConfigFlagPresence(fs)
	if visited.BaseURL {
		cfg.BaseURL = *values.BaseURL
		applied.BaseURL = true
	}
	if flagWasSet(fs, "upstash-box-runtime") {
		cfg.Runtime = *values.Runtime
	}
	if flagWasSet(fs, "upstash-box-size") {
		cfg.Size = *values.Size
	}
	if flagWasSet(fs, "upstash-box-workdir") {
		cfg.Workdir = *values.Workdir
	}
	if flagWasSet(fs, "upstash-box-keep-alive") {
		cfg.KeepAlive = *values.KeepAlive
	}
	return applied
}
