// Code generated by scripts/configgen from config_blacksmith.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileBlacksmithConfig struct {
	Org         string `yaml:"org,omitempty"`
	Workflow    string `yaml:"workflow,omitempty"`
	Job         string `yaml:"job,omitempty"`
	Ref         string `yaml:"ref,omitempty"`
	IdleTimeout string `yaml:"idleTimeout,omitempty"`
	Debug       *bool  `yaml:"debug,omitempty"`
}

func defaultBlacksmithConfig() BlacksmithConfig {
	return BlacksmithConfig{}
}

// BlacksmithConfigApplied records accepted assignments during one application.
type BlacksmithConfigApplied struct {
	InputAccepted bool
}

func (cfg *BlacksmithConfig) applyFile(file *fileBlacksmithConfig) (BlacksmithConfigApplied, error) {
	var applied BlacksmithConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "blacksmith-testbox")
	return applied, err
}

func (cfg *BlacksmithConfig) applyEnvPrefix() (BlacksmithConfigApplied, error) {
	var applied BlacksmithConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 4)
	return applied, err
}

func (cfg *BlacksmithConfig) applyEnvSuffix() (BlacksmithConfigApplied, error) {
	var applied BlacksmithConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 4, 6)
	return applied, err
}

// BlacksmithConfigFlagValues holds parsed values; only visited flags are applied.
type BlacksmithConfigFlagValues struct {
	Org      *string
	Workflow *string
	Job      *string
	Ref      *string
}

// RegisterBlacksmithConfigFlags registers mechanical bindings without selecting a provider.
func RegisterBlacksmithConfigFlags(fs *flag.FlagSet, defaults BlacksmithConfig) BlacksmithConfigFlagValues {
	var values BlacksmithConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values BlacksmithConfigFlagValues) Apply(cfg *BlacksmithConfig, fs *flag.FlagSet) (BlacksmithConfigApplied, error) {
	var applied BlacksmithConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
