// Code generated by scripts/configgen from config_tenki.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileTenkiConfig struct {
	CLIPath   string `yaml:"cliPath,omitempty"`
	Endpoint  string `yaml:"endpoint,omitempty"`
	Gateway   string `yaml:"gateway,omitempty"`
	Workspace string `yaml:"workspace,omitempty"`
	Project   string `yaml:"project,omitempty"`
	Image     string `yaml:"image,omitempty"`
	Snapshot  string `yaml:"snapshot,omitempty"`
	WorkRoot  string `yaml:"workRoot,omitempty"`
	CPUs      int    `yaml:"cpus,omitempty"`
	MemoryMB  int    `yaml:"memoryMB,omitempty"`
	DiskGB    int    `yaml:"diskGB,omitempty"`
}

const TenkiConfigDefaultCLIPath string = "tenki"
const TenkiConfigDefaultWorkRoot string = "/home/tenki/crabbox"

func defaultTenkiConfig() TenkiConfig {
	return TenkiConfig{
		CLIPath:  TenkiConfigDefaultCLIPath,
		WorkRoot: TenkiConfigDefaultWorkRoot,
	}
}

// TenkiConfigApplied records accepted assignments during one application.
type TenkiConfigApplied struct {
	InputAccepted bool
	Endpoint      bool
	Gateway       bool
}

func (cfg *TenkiConfig) applyFile(file *fileTenkiConfig) (TenkiConfigApplied, error) {
	var applied TenkiConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "tenki")
	return applied, err
}

func (cfg *TenkiConfig) applyEnv() (TenkiConfigApplied, error) {
	var applied TenkiConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 11)
	return applied, err
}

// TenkiConfigFlagValues holds parsed values; only visited flags are applied.
type TenkiConfigFlagValues struct {
	CLIPath   *string
	Endpoint  *string
	Gateway   *string
	Workspace *string
	Project   *string
	Image     *string
	Snapshot  *string
	WorkRoot  *string
	CPUs      *int
	MemoryMB  *int
	DiskGB    *int
}

// RegisterTenkiConfigFlags registers mechanical bindings without selecting a provider.
func RegisterTenkiConfigFlags(fs *flag.FlagSet, defaults TenkiConfig) TenkiConfigFlagValues {
	var values TenkiConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// TenkiConfigVisitedFlags records raw flag visits, independently of application.
type TenkiConfigVisitedFlags struct {
	Endpoint bool
	Gateway  bool
}

// TenkiConfigFlagPresence reports visits for tracked flag bindings.
func TenkiConfigFlagPresence(fs *flag.FlagSet) TenkiConfigVisitedFlags {
	var visited TenkiConfigVisitedFlags
	recordConfigFlagVisits[TenkiConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values TenkiConfigFlagValues) Apply(cfg *TenkiConfig, fs *flag.FlagSet) (TenkiConfigApplied, error) {
	var applied TenkiConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
