// Code generated by scripts/configgen from config_freestyle.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileFreestyleConfig struct {
	APIURL   string `yaml:"apiUrl,omitempty"`
	Workdir  string `yaml:"workdir,omitempty"`
	VCPUs    int    `yaml:"vcpus,omitempty"`
	MemoryGB int    `yaml:"memoryGB,omitempty"`
}

const FreestyleConfigDefaultAPIURL string = "https://api.freestyle.sh"
const FreestyleConfigDefaultWorkdir string = "crabbox"

func defaultFreestyleConfig() FreestyleConfig {
	return FreestyleConfig{
		APIURL:  FreestyleConfigDefaultAPIURL,
		Workdir: FreestyleConfigDefaultWorkdir,
	}
}

// FreestyleConfigApplied records accepted assignments during one application.
type FreestyleConfigApplied struct {
	InputAccepted bool
}

func (cfg *FreestyleConfig) applyFile(file *fileFreestyleConfig, trusted bool) (FreestyleConfigApplied, error) {
	var applied FreestyleConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "freestyle")
	return applied, err
}

func (cfg *FreestyleConfig) applyEnv() (FreestyleConfigApplied, error) {
	var applied FreestyleConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// FreestyleConfigFlagValues holds parsed values; only visited flags are applied.
type FreestyleConfigFlagValues struct {
	APIURL   *string
	Workdir  *string
	VCPUs    *int
	MemoryGB *int
}

// RegisterFreestyleConfigFlags registers mechanical bindings without selecting a provider.
func RegisterFreestyleConfigFlags(fs *flag.FlagSet, defaults FreestyleConfig) FreestyleConfigFlagValues {
	var values FreestyleConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values FreestyleConfigFlagValues) Apply(cfg *FreestyleConfig, fs *flag.FlagSet) (FreestyleConfigApplied, error) {
	var applied FreestyleConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
