// Code generated by scripts/configgen from config_incus.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileIncusConfig struct {
	Remote            string `yaml:"remote,omitempty"`
	Project           string `yaml:"project,omitempty"`
	Address           string `yaml:"address,omitempty"`
	Socket            string `yaml:"socket,omitempty"`
	InstanceType      string `yaml:"instanceType,omitempty"`
	Image             string `yaml:"image,omitempty"`
	Profile           string `yaml:"profile,omitempty"`
	User              string `yaml:"user,omitempty"`
	WorkRoot          string `yaml:"workRoot,omitempty"`
	DeleteOnRelease   *bool  `yaml:"deleteOnRelease,omitempty"`
	StartTimeout      string `yaml:"startTimeout,omitempty"`
	LaunchPort        string `yaml:"launchPort,omitempty"`
	ProxyListenHost   string `yaml:"proxyListenHost,omitempty"`
	ProxyListenPort   string `yaml:"proxyListenPort,omitempty"`
	ProxyDevice       string `yaml:"proxyDevice,omitempty"`
	TLSServerCert     string `yaml:"tlsServerCert,omitempty"`
	InsecureTLS       *bool  `yaml:"insecureTLS,omitempty"`
	RemoteImageServer string `yaml:"remoteImageServer,omitempty"`
}

const IncusConfigDefaultRemote string = "local"
const IncusConfigDefaultInstanceType string = "container"
const IncusConfigDefaultImage string = "images:ubuntu/24.04/cloud"
const IncusConfigDefaultUser string = "crabbox"
const IncusConfigDefaultDeleteOnRelease bool = true
const IncusConfigDefaultStartTimeout time.Duration = 600 * time.Second
const IncusConfigDefaultLaunchPort string = "22"
const IncusConfigDefaultProxyListenHost string = "127.0.0.1"
const IncusConfigDefaultProxyDevice string = "crabbox-ssh"

func defaultIncusConfig() IncusConfig {
	return IncusConfig{
		Remote:          IncusConfigDefaultRemote,
		InstanceType:    IncusConfigDefaultInstanceType,
		Image:           IncusConfigDefaultImage,
		User:            IncusConfigDefaultUser,
		DeleteOnRelease: IncusConfigDefaultDeleteOnRelease,
		StartTimeout:    IncusConfigDefaultStartTimeout,
		LaunchPort:      IncusConfigDefaultLaunchPort,
		ProxyListenHost: IncusConfigDefaultProxyListenHost,
		ProxyDevice:     IncusConfigDefaultProxyDevice,
	}
}

// IncusConfigApplied records accepted assignments during one application.
type IncusConfigApplied struct {
	InputAccepted   bool
	Socket          bool
	DeleteOnRelease bool
	TLSServerCert   bool
}

func (cfg *IncusConfig) applyFile(file *fileIncusConfig) (IncusConfigApplied, error) {
	var applied IncusConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "incus")
	return applied, err
}

func (cfg *IncusConfig) applyEnv() (IncusConfigApplied, error) {
	var applied IncusConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 18)
	return applied, err
}

// IncusConfigFlagValues holds parsed values; only visited flags are applied.
type IncusConfigFlagValues struct {
	Remote            *string
	Project           *string
	Address           *string
	Socket            *string
	InstanceType      *string
	Image             *string
	Profile           *string
	User              *string
	WorkRoot          *string
	DeleteOnRelease   *bool
	StartTimeout      *string
	LaunchPort        *string
	ProxyListenHost   *string
	ProxyListenPort   *string
	ProxyDevice       *string
	TLSServerCert     *string
	InsecureTLS       *bool
	RemoteImageServer *string
}

// RegisterIncusConfigFlags registers mechanical bindings without selecting a provider.
func RegisterIncusConfigFlags(fs *flag.FlagSet, defaults IncusConfig) IncusConfigFlagValues {
	var values IncusConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// IncusConfigVisitedFlags records raw flag visits, independently of application.
type IncusConfigVisitedFlags struct {
	Remote            bool
	Project           bool
	Address           bool
	Socket            bool
	InstanceType      bool
	Image             bool
	Profile           bool
	User              bool
	WorkRoot          bool
	DeleteOnRelease   bool
	StartTimeout      bool
	LaunchPort        bool
	ProxyListenHost   bool
	ProxyListenPort   bool
	ProxyDevice       bool
	TLSServerCert     bool
	InsecureTLS       bool
	RemoteImageServer bool
}

// IncusConfigFlagPresence reports visits for tracked flag bindings.
func IncusConfigFlagPresence(fs *flag.FlagSet) IncusConfigVisitedFlags {
	var visited IncusConfigVisitedFlags
	recordConfigFlagVisits[IncusConfig](fs, &visited)
	return visited
}
