// Code generated by scripts/configgen from config_morph.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileMorphConfig struct {
	APIKey          string `yaml:"apiKey,omitempty"`
	APIURL          string `yaml:"apiUrl,omitempty"`
	Snapshot        string `yaml:"snapshot,omitempty"`
	SSHGatewayHost  string `yaml:"sshGatewayHost,omitempty"`
	WorkRoot        string `yaml:"workRoot,omitempty"`
	DeleteOnRelease *bool  `yaml:"deleteOnRelease,omitempty"`
	WakeOnSSH       *bool  `yaml:"wakeOnSSH,omitempty"`
}

const MorphConfigDefaultAPIURL string = "https://cloud.morph.so"
const MorphConfigDefaultSSHGatewayHost string = "ssh.cloud.morph.so"
const MorphConfigDefaultWorkRoot string = "/tmp/crabbox"
const MorphConfigDefaultWakeOnSSH bool = true

func defaultMorphConfig() MorphConfig {
	return MorphConfig{
		APIURL:         MorphConfigDefaultAPIURL,
		SSHGatewayHost: MorphConfigDefaultSSHGatewayHost,
		WorkRoot:       MorphConfigDefaultWorkRoot,
		WakeOnSSH:      MorphConfigDefaultWakeOnSSH,
	}
}

// MorphConfigApplied records accepted assignments during one application.
type MorphConfigApplied struct {
	InputAccepted   bool
	APIKey          bool
	APIURL          bool
	SSHGatewayHost  bool
	DeleteOnRelease bool
}

func (cfg *MorphConfig) applyFile(file *fileMorphConfig) (MorphConfigApplied, error) {
	var applied MorphConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "morph")
	return applied, err
}

func (cfg *MorphConfig) applyEnv() (MorphConfigApplied, error) {
	var applied MorphConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 7)
	return applied, err
}

// MorphConfigFlagValues holds parsed values; only visited flags are applied.
type MorphConfigFlagValues struct {
	APIURL          *string
	Snapshot        *string
	SSHGatewayHost  *string
	WorkRoot        *string
	DeleteOnRelease *bool
	WakeOnSSH       *bool
}

// RegisterMorphConfigFlags registers mechanical bindings without selecting a provider.
func RegisterMorphConfigFlags(fs *flag.FlagSet, defaults MorphConfig) MorphConfigFlagValues {
	var values MorphConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// MorphConfigVisitedFlags records raw flag visits, independently of application.
type MorphConfigVisitedFlags struct {
	APIURL          bool
	SSHGatewayHost  bool
	DeleteOnRelease bool
}

// MorphConfigFlagPresence reports visits for tracked flag bindings.
func MorphConfigFlagPresence(fs *flag.FlagSet) MorphConfigVisitedFlags {
	var visited MorphConfigVisitedFlags
	recordConfigFlagVisits[MorphConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values MorphConfigFlagValues) Apply(cfg *MorphConfig, fs *flag.FlagSet) (MorphConfigApplied, error) {
	var applied MorphConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
