// Code generated by scripts/configgen from config_aws_lambda_microvm.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileAWSLambdaMicroVMConfig struct {
	Image             string    `yaml:"image,omitempty"`
	ImageVersion      string    `yaml:"imageVersion,omitempty"`
	ExecutionRoleARN  string    `yaml:"executionRoleArn,omitempty"`
	Workdir           string    `yaml:"workdir,omitempty"`
	IngressConnectors *[]string `yaml:"ingressConnectors,omitempty"`
	EgressConnectors  *[]string `yaml:"egressConnectors,omitempty"`
	ForgetMissing     *bool     `yaml:"forgetMissing,omitempty"`
}

const AWSLambdaMicroVMConfigDefaultWorkdir string = "/workspace/crabbox"

func defaultAWSLambdaMicroVMConfig() AWSLambdaMicroVMConfig {
	return AWSLambdaMicroVMConfig{
		Workdir: AWSLambdaMicroVMConfigDefaultWorkdir,
	}
}

// AWSLambdaMicroVMConfigApplied records accepted assignments during one application.
type AWSLambdaMicroVMConfigApplied struct {
	InputAccepted    bool
	Image            bool
	ImageVersion     bool
	ExecutionRoleARN bool
	Workdir          bool
}

func (cfg *AWSLambdaMicroVMConfig) applyFile(file *fileAWSLambdaMicroVMConfig) (AWSLambdaMicroVMConfigApplied, error) {
	var applied AWSLambdaMicroVMConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "awsLambdaMicroVM")
	return applied, err
}

func (cfg *AWSLambdaMicroVMConfig) applyEnv() (AWSLambdaMicroVMConfigApplied, error) {
	var applied AWSLambdaMicroVMConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 7)
	return applied, err
}

// AWSLambdaMicroVMConfigFlagValues holds parsed values; only visited flags are applied.
type AWSLambdaMicroVMConfigFlagValues struct {
	Image             *string
	ImageVersion      *string
	ExecutionRoleARN  *string
	Workdir           *string
	IngressConnectors *string
	EgressConnectors  *string
	ForgetMissing     *bool
}

// RegisterAWSLambdaMicroVMConfigFlags registers mechanical bindings without selecting a provider.
func RegisterAWSLambdaMicroVMConfigFlags(fs *flag.FlagSet, defaults AWSLambdaMicroVMConfig) AWSLambdaMicroVMConfigFlagValues {
	var values AWSLambdaMicroVMConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// AWSLambdaMicroVMConfigVisitedFlags records raw flag visits, independently of application.
type AWSLambdaMicroVMConfigVisitedFlags struct {
	Image            bool
	ImageVersion     bool
	ExecutionRoleARN bool
	Workdir          bool
}

// AWSLambdaMicroVMConfigFlagPresence reports visits for tracked flag bindings.
func AWSLambdaMicroVMConfigFlagPresence(fs *flag.FlagSet) AWSLambdaMicroVMConfigVisitedFlags {
	var visited AWSLambdaMicroVMConfigVisitedFlags
	recordConfigFlagVisits[AWSLambdaMicroVMConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values AWSLambdaMicroVMConfigFlagValues) Apply(cfg *AWSLambdaMicroVMConfig, fs *flag.FlagSet) (AWSLambdaMicroVMConfigApplied, error) {
	var applied AWSLambdaMicroVMConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
