// Code generated by scripts/configgen from config_modal.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileModalConfig struct {
	App         string    `yaml:"app,omitempty"`
	Image       string    `yaml:"image,omitempty"`
	Workdir     string    `yaml:"workdir,omitempty"`
	Python      string    `yaml:"python,omitempty"`
	Environment string    `yaml:"environment,omitempty"`
	Secrets     *[]string `yaml:"secrets,omitempty"`
}

const ModalConfigDefaultApp string = "crabbox"
const ModalConfigDefaultImage string = "python:3.13-slim"
const ModalConfigDefaultWorkdir string = "/workspace/crabbox"
const ModalConfigDefaultPython string = "python3"

func defaultModalConfig() ModalConfig {
	return ModalConfig{
		App:     ModalConfigDefaultApp,
		Image:   ModalConfigDefaultImage,
		Workdir: ModalConfigDefaultWorkdir,
		Python:  ModalConfigDefaultPython,
	}
}

// ModalConfigApplied records accepted assignments during one application.
type ModalConfigApplied struct {
	InputAccepted bool
}

func (cfg *ModalConfig) applyFile(file *fileModalConfig, trusted bool) (ModalConfigApplied, error) {
	var applied ModalConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "modal")
	return applied, err
}

func (cfg *ModalConfig) applyEnv() (ModalConfigApplied, error) {
	var applied ModalConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// ModalConfigFlagValues holds parsed values; only visited flags are applied.
type ModalConfigFlagValues struct {
	App         *string
	Image       *string
	Workdir     *string
	Python      *string
	Environment *string
	Secrets     *replaceAppendListFlag
}

// RegisterModalConfigFlags registers mechanical bindings without selecting a provider.
func RegisterModalConfigFlags(fs *flag.FlagSet, defaults ModalConfig) ModalConfigFlagValues {
	var values ModalConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values ModalConfigFlagValues) Apply(cfg *ModalConfig, fs *flag.FlagSet) (ModalConfigApplied, error) {
	var applied ModalConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
