// Code generated by scripts/configgen from config_smolvm.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileSmolvmConfig struct {
	BaseURL  string `yaml:"baseUrl,omitempty"`
	Image    string `yaml:"image,omitempty"`
	Workdir  string `yaml:"workdir,omitempty"`
	CPUs     int    `yaml:"cpus,omitempty"`
	MemoryMB int    `yaml:"memoryMB,omitempty"`
	Network  string `yaml:"network,omitempty"`
	Keep     *bool  `yaml:"keep,omitempty"`
}

const SmolvmConfigDefaultBaseURL string = "https://api.smolmachines.com"
const SmolvmConfigDefaultImage string = "alpine"
const SmolvmConfigDefaultWorkdir string = "/workspace"
const SmolvmConfigDefaultCPUs int = 2
const SmolvmConfigDefaultMemoryMB int = 2048
const SmolvmConfigDefaultNetwork string = "open"

func defaultSmolvmConfig() SmolvmConfig {
	return SmolvmConfig{
		BaseURL:  SmolvmConfigDefaultBaseURL,
		Image:    SmolvmConfigDefaultImage,
		Workdir:  SmolvmConfigDefaultWorkdir,
		CPUs:     SmolvmConfigDefaultCPUs,
		MemoryMB: SmolvmConfigDefaultMemoryMB,
		Network:  SmolvmConfigDefaultNetwork,
	}
}

// SmolvmConfigApplied records accepted assignments during one application.
type SmolvmConfigApplied struct {
	APIKey  bool
	BaseURL bool
}

func (cfg *SmolvmConfig) applyFile(file *fileSmolvmConfig) (SmolvmConfigApplied, error) {
	var applied SmolvmConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.BaseURL != "" {
		cfg.BaseURL = file.BaseURL
		applied.BaseURL = true
	}
	if file.Image != "" {
		cfg.Image = file.Image
	}
	if file.Workdir != "" {
		cfg.Workdir = file.Workdir
	}
	if file.CPUs > 0 {
		cfg.CPUs = file.CPUs
	}
	if file.MemoryMB > 0 {
		cfg.MemoryMB = file.MemoryMB
	}
	if file.Network != "" {
		cfg.Network = file.Network
	}
	if file.Keep != nil {
		cfg.Keep = *file.Keep
	}
	return applied, nil
}

func (cfg *SmolvmConfig) applyEnv() (SmolvmConfigApplied, error) {
	var applied SmolvmConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_SMOLVM_API_KEY", "SMOLMACHINES_API_KEY", "SMK_API_KEY"); ok {
		cfg.APIKey = value
		applied.APIKey = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_SMOLVM_BASE_URL"); ok {
		cfg.BaseURL = value
		applied.BaseURL = true
	}
	cfg.Image = getenv("CRABBOX_SMOLVM_IMAGE", cfg.Image)
	cfg.Workdir = getenv("CRABBOX_SMOLVM_WORKDIR", cfg.Workdir)
	cfg.CPUs = getenvInt("CRABBOX_SMOLVM_CPUS", cfg.CPUs)
	cfg.MemoryMB = getenvInt("CRABBOX_SMOLVM_MEMORY_MB", cfg.MemoryMB)
	cfg.Network = getenv("CRABBOX_SMOLVM_NETWORK", cfg.Network)
	if value, ok := getenvBool("CRABBOX_SMOLVM_KEEP"); ok {
		cfg.Keep = value
	}
	return applied, nil
}

// SmolvmConfigFlagValues holds parsed values; only visited flags are applied.
type SmolvmConfigFlagValues struct {
	BaseURL  *string
	Image    *string
	Workdir  *string
	CPUs     *int
	MemoryMB *int
	Network  *string
	Keep     *bool
}

// RegisterSmolvmConfigFlags registers mechanical bindings without selecting a provider.
func RegisterSmolvmConfigFlags(fs *flag.FlagSet, defaults SmolvmConfig) SmolvmConfigFlagValues {
	return SmolvmConfigFlagValues{
		BaseURL:  fs.String("smolvm-base-url", defaults.BaseURL, "SmolVM / SmolFleet API base URL"),
		Image:    fs.String("smolvm-image", defaults.Image, "source image for smolvm machines (e.g. ubuntu:24.04)"),
		Workdir:  fs.String("smolvm-workdir", defaults.Workdir, "absolute working directory inside the smolvm machine"),
		CPUs:     fs.Int("smolvm-cpus", defaults.CPUs, "number of vCPUs for the smolvm machine"),
		MemoryMB: fs.Int("smolvm-memory-mb", defaults.MemoryMB, "memory in MiB for the smolvm machine"),
		Network:  fs.String("smolvm-network", defaults.Network, "network mode: open or blocked"),
		Keep:     fs.Bool("smolvm-keep", defaults.Keep, "keep the smolvm machine after run (do not auto-delete)"),
	}
}

// SmolvmConfigVisitedFlags records raw flag visits, independently of application.
type SmolvmConfigVisitedFlags struct {
	BaseURL bool
}

// SmolvmConfigFlagPresence reports visits for tracked flag bindings.
func SmolvmConfigFlagPresence(fs *flag.FlagSet) SmolvmConfigVisitedFlags {
	return SmolvmConfigVisitedFlags{
		BaseURL: flagWasSet(fs, "smolvm-base-url"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values SmolvmConfigFlagValues) Apply(cfg *SmolvmConfig, fs *flag.FlagSet) SmolvmConfigApplied {
	var applied SmolvmConfigApplied
	visited := SmolvmConfigFlagPresence(fs)
	if visited.BaseURL {
		cfg.BaseURL = *values.BaseURL
		applied.BaseURL = true
	}
	if flagWasSet(fs, "smolvm-image") {
		cfg.Image = *values.Image
	}
	if flagWasSet(fs, "smolvm-workdir") {
		cfg.Workdir = *values.Workdir
	}
	if flagWasSet(fs, "smolvm-cpus") {
		cfg.CPUs = *values.CPUs
	}
	if flagWasSet(fs, "smolvm-memory-mb") {
		cfg.MemoryMB = *values.MemoryMB
	}
	if flagWasSet(fs, "smolvm-network") {
		cfg.Network = *values.Network
	}
	if flagWasSet(fs, "smolvm-keep") {
		cfg.Keep = *values.Keep
	}
	return applied
}
