// Code generated by scripts/configgen from config_cubesandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCubeSandboxConfig struct {
	APIURL        string `yaml:"apiUrl,omitempty"`
	Domain        string `yaml:"domain,omitempty"`
	Template      string `yaml:"template,omitempty"`
	Workdir       string `yaml:"workdir,omitempty"`
	User          string `yaml:"user,omitempty"`
	ProxyNodeIP   string `yaml:"proxyNodeIp,omitempty"`
	ProxyPortHTTP int    `yaml:"proxyPortHttp,omitempty"`
	ProxyScheme   string `yaml:"proxyScheme,omitempty"`
}

const CubeSandboxConfigDefaultAPIURL string = "http://127.0.0.1:3000"
const CubeSandboxConfigDefaultDomain string = "cube.app"
const CubeSandboxConfigDefaultWorkdir string = "crabbox"
const CubeSandboxConfigDefaultProxyPortHTTP int = 80

func defaultCubeSandboxConfig() CubeSandboxConfig {
	return CubeSandboxConfig{
		APIURL:        CubeSandboxConfigDefaultAPIURL,
		Domain:        CubeSandboxConfigDefaultDomain,
		Workdir:       CubeSandboxConfigDefaultWorkdir,
		ProxyPortHTTP: CubeSandboxConfigDefaultProxyPortHTTP,
	}
}

// CubeSandboxConfigApplied records accepted assignments during one application.
type CubeSandboxConfigApplied struct {
	InputAccepted bool
	APIURL        bool
	Domain        bool
	ProxyNodeIP   bool
	ProxyPortHTTP bool
	ProxyScheme   bool
}

func (cfg *CubeSandboxConfig) applyFile(file *fileCubeSandboxConfig) (CubeSandboxConfigApplied, error) {
	var applied CubeSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "cubesandbox")
	return applied, err
}

func (cfg *CubeSandboxConfig) applyEnv() (CubeSandboxConfigApplied, error) {
	var applied CubeSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 9)
	return applied, err
}

// CubeSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type CubeSandboxConfigFlagValues struct {
	APIURL        *string
	Domain        *string
	Template      *string
	Workdir       *string
	User          *string
	ProxyNodeIP   *string
	ProxyPortHTTP *int
	ProxyScheme   *string
}

// RegisterCubeSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCubeSandboxConfigFlags(fs *flag.FlagSet, defaults CubeSandboxConfig) CubeSandboxConfigFlagValues {
	var values CubeSandboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// CubeSandboxConfigVisitedFlags records raw flag visits, independently of application.
type CubeSandboxConfigVisitedFlags struct {
	APIURL        bool
	Domain        bool
	ProxyNodeIP   bool
	ProxyPortHTTP bool
	ProxyScheme   bool
}

// CubeSandboxConfigFlagPresence reports visits for tracked flag bindings.
func CubeSandboxConfigFlagPresence(fs *flag.FlagSet) CubeSandboxConfigVisitedFlags {
	var visited CubeSandboxConfigVisitedFlags
	recordConfigFlagVisits[CubeSandboxConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CubeSandboxConfigFlagValues) Apply(cfg *CubeSandboxConfig, fs *flag.FlagSet) (CubeSandboxConfigApplied, error) {
	var applied CubeSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
