// Code generated by scripts/configgen from config_smolvm.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileSmolvmConfig struct {
	BaseURL  string `yaml:"baseUrl,omitempty"`
	Image    string `yaml:"image,omitempty"`
	Workdir  string `yaml:"workdir,omitempty"`
	CPUs     int    `yaml:"cpus,omitempty"`
	MemoryMB int    `yaml:"memoryMB,omitempty"`
	Network  string `yaml:"network,omitempty"`
	Keep     *bool  `yaml:"keep,omitempty"`
}

const SmolvmConfigDefaultBaseURL string = "https://api.smolmachines.com"
const SmolvmConfigDefaultImage string = "alpine"
const SmolvmConfigDefaultWorkdir string = "/workspace"
const SmolvmConfigDefaultCPUs int = 2
const SmolvmConfigDefaultMemoryMB int = 2048
const SmolvmConfigDefaultNetwork string = "open"

func defaultSmolvmConfig() SmolvmConfig {
	return SmolvmConfig{
		BaseURL:  SmolvmConfigDefaultBaseURL,
		Image:    SmolvmConfigDefaultImage,
		Workdir:  SmolvmConfigDefaultWorkdir,
		CPUs:     SmolvmConfigDefaultCPUs,
		MemoryMB: SmolvmConfigDefaultMemoryMB,
		Network:  SmolvmConfigDefaultNetwork,
	}
}

// SmolvmConfigApplied records accepted assignments during one application.
type SmolvmConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	BaseURL       bool
}

func (cfg *SmolvmConfig) applyFile(file *fileSmolvmConfig) (SmolvmConfigApplied, error) {
	var applied SmolvmConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "smolvm")
	return applied, err
}

func (cfg *SmolvmConfig) applyEnv() (SmolvmConfigApplied, error) {
	var applied SmolvmConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 8)
	return applied, err
}

// SmolvmConfigFlagValues holds parsed values; only visited flags are applied.
type SmolvmConfigFlagValues struct {
	BaseURL  *string
	Image    *string
	Workdir  *string
	CPUs     *int
	MemoryMB *int
	Network  *string
	Keep     *bool
}

// RegisterSmolvmConfigFlags registers mechanical bindings without selecting a provider.
func RegisterSmolvmConfigFlags(fs *flag.FlagSet, defaults SmolvmConfig) SmolvmConfigFlagValues {
	var values SmolvmConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// SmolvmConfigVisitedFlags records raw flag visits, independently of application.
type SmolvmConfigVisitedFlags struct {
	BaseURL bool
}

// SmolvmConfigFlagPresence reports visits for tracked flag bindings.
func SmolvmConfigFlagPresence(fs *flag.FlagSet) SmolvmConfigVisitedFlags {
	var visited SmolvmConfigVisitedFlags
	recordConfigFlagVisits[SmolvmConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values SmolvmConfigFlagValues) Apply(cfg *SmolvmConfig, fs *flag.FlagSet) (SmolvmConfigApplied, error) {
	var applied SmolvmConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
