// Code generated by scripts/configgen from config_cloudflare_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCloudflareSandboxConfig struct {
	BridgeURL            *string `yaml:"bridgeUrl,omitempty"`
	BridgeURLConfigAlias *string `yaml:"url,omitempty"`
	Token                *string `yaml:"token,omitempty"`
	Workdir              *string `yaml:"workdir,omitempty"`
	ExecTimeoutSecs      *int    `yaml:"execTimeoutSecs,omitempty"`
	ForgetMissing        *bool   `yaml:"forgetMissing,omitempty"`
}

const CloudflareSandboxConfigDefaultWorkdir string = "/workspace/crabbox"
const CloudflareSandboxConfigDefaultExecTimeoutSecs int = 600

func defaultCloudflareSandboxConfig() CloudflareSandboxConfig {
	return CloudflareSandboxConfig{
		Workdir:         CloudflareSandboxConfigDefaultWorkdir,
		ExecTimeoutSecs: CloudflareSandboxConfigDefaultExecTimeoutSecs,
	}
}

// CloudflareSandboxConfigApplied records accepted assignments during one application.
type CloudflareSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *CloudflareSandboxConfig) applyFile(file *fileCloudflareSandboxConfig, trusted bool) (CloudflareSandboxConfigApplied, error) {
	var applied CloudflareSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "cloudflare-sandbox")
	return applied, err
}

func (cfg *CloudflareSandboxConfig) applyEnv() (CloudflareSandboxConfigApplied, error) {
	var applied CloudflareSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// CloudflareSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type CloudflareSandboxConfigFlagValues struct {
	BridgeURL       *string
	Workdir         *string
	ExecTimeoutSecs *int
	ForgetMissing   *bool
}

// RegisterCloudflareSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCloudflareSandboxConfigFlags(fs *flag.FlagSet, defaults CloudflareSandboxConfig) CloudflareSandboxConfigFlagValues {
	var values CloudflareSandboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CloudflareSandboxConfigFlagValues) Apply(cfg *CloudflareSandboxConfig, fs *flag.FlagSet) (CloudflareSandboxConfigApplied, error) {
	var applied CloudflareSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
