// Code generated by scripts/configgen from config_runpod.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileRunpodConfig struct {
	APIURL     string `yaml:"apiUrl,omitempty"`
	CloudType  string `yaml:"cloudType,omitempty"`
	InstanceID string `yaml:"instanceId,omitempty"`
	Image      string `yaml:"image,omitempty"`
	TemplateID string `yaml:"templateId,omitempty"`
	DiskGB     int    `yaml:"diskGB,omitempty"`
	User       string `yaml:"user,omitempty"`
	WorkRoot   string `yaml:"workRoot,omitempty"`
}

const RunpodConfigDefaultAPIURL string = "https://rest.runpod.io/v1"
const RunpodConfigDefaultCloudType string = "SECURE"
const RunpodConfigDefaultInstanceID string = "NVIDIA L4,NVIDIA RTX 4000 Ada Generation,NVIDIA RTX A4000,NVIDIA GeForce RTX 3090,NVIDIA GeForce RTX 4090,NVIDIA RTX A5000,NVIDIA RTX A4500"
const RunpodConfigDefaultImage string = "runpod/pytorch:2.8.0-py3.11-cuda12.8.1-cudnn-devel-ubuntu22.04"
const RunpodConfigDefaultDiskGB int = 20

func defaultRunpodConfig() RunpodConfig {
	return RunpodConfig{
		APIURL:     RunpodConfigDefaultAPIURL,
		CloudType:  RunpodConfigDefaultCloudType,
		InstanceID: RunpodConfigDefaultInstanceID,
		Image:      RunpodConfigDefaultImage,
		DiskGB:     RunpodConfigDefaultDiskGB,
	}
}

// RunpodConfigApplied records accepted assignments during one application.
type RunpodConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	APIURL        bool
}

func (cfg *RunpodConfig) applyFile(file *fileRunpodConfig) (RunpodConfigApplied, error) {
	var applied RunpodConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "runpod")
	return applied, err
}

func (cfg *RunpodConfig) applyEnv() (RunpodConfigApplied, error) {
	var applied RunpodConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 9)
	return applied, err
}

// RunpodConfigFlagValues holds parsed values; only visited flags are applied.
type RunpodConfigFlagValues struct {
	APIURL     *string
	CloudType  *string
	InstanceID *string
	Image      *string
	TemplateID *string
	DiskGB     *int
	User       *string
	WorkRoot   *string
}

// RegisterRunpodConfigFlags registers mechanical bindings without selecting a provider.
func RegisterRunpodConfigFlags(fs *flag.FlagSet, defaults RunpodConfig) RunpodConfigFlagValues {
	var values RunpodConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// RunpodConfigVisitedFlags records raw flag visits, independently of application.
type RunpodConfigVisitedFlags struct {
	APIURL bool
}

// RunpodConfigFlagPresence reports visits for tracked flag bindings.
func RunpodConfigFlagPresence(fs *flag.FlagSet) RunpodConfigVisitedFlags {
	var visited RunpodConfigVisitedFlags
	recordConfigFlagVisits[RunpodConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values RunpodConfigFlagValues) Apply(cfg *RunpodConfig, fs *flag.FlagSet) (RunpodConfigApplied, error) {
	var applied RunpodConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
