// Code generated by scripts/configgen from config_tensorlake.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileTensorlakeConfig struct {
	APIURL         string  `yaml:"apiUrl,omitempty"`
	CLIPath        string  `yaml:"cliPath,omitempty"`
	Image          string  `yaml:"image,omitempty"`
	Snapshot       string  `yaml:"snapshot,omitempty"`
	OrganizationID string  `yaml:"organizationId,omitempty"`
	ProjectID      string  `yaml:"projectId,omitempty"`
	Namespace      string  `yaml:"namespace,omitempty"`
	Workdir        string  `yaml:"workdir,omitempty"`
	CPUs           float64 `yaml:"cpus,omitempty"`
	MemoryMB       int     `yaml:"memoryMB,omitempty"`
	DiskMB         int     `yaml:"diskMB,omitempty"`
	TimeoutSecs    int     `yaml:"timeoutSecs,omitempty"`
	NoInternet     *bool   `yaml:"noInternet,omitempty"`
}

const TensorlakeConfigDefaultAPIURL string = "https://api.tensorlake.ai"
const TensorlakeConfigDefaultCLIPath string = "tensorlake"
const TensorlakeConfigDefaultWorkdir string = "/workspace/crabbox"
const TensorlakeConfigDefaultCPUs float64 = 1
const TensorlakeConfigDefaultMemoryMB int = 1024
const TensorlakeConfigDefaultDiskMB int = 10240

func defaultTensorlakeConfig() TensorlakeConfig {
	return TensorlakeConfig{
		APIURL:   TensorlakeConfigDefaultAPIURL,
		CLIPath:  TensorlakeConfigDefaultCLIPath,
		Workdir:  TensorlakeConfigDefaultWorkdir,
		CPUs:     TensorlakeConfigDefaultCPUs,
		MemoryMB: TensorlakeConfigDefaultMemoryMB,
		DiskMB:   TensorlakeConfigDefaultDiskMB,
	}
}

// TensorlakeConfigApplied records accepted assignments during one application.
type TensorlakeConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	APIURL        bool
}

func (cfg *TensorlakeConfig) applyFile(file *fileTensorlakeConfig) (TensorlakeConfigApplied, error) {
	var applied TensorlakeConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "tensorlake")
	return applied, err
}

func (cfg *TensorlakeConfig) applyEnv() (TensorlakeConfigApplied, error) {
	var applied TensorlakeConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 14)
	return applied, err
}

// TensorlakeConfigFlagValues holds parsed values; only visited flags are applied.
type TensorlakeConfigFlagValues struct {
	APIURL         *string
	CLIPath        *string
	Image          *string
	Snapshot       *string
	OrganizationID *string
	ProjectID      *string
	Namespace      *string
	Workdir        *string
	CPUs           *float64
	MemoryMB       *int
	DiskMB         *int
	TimeoutSecs    *int
	NoInternet     *bool
}

// RegisterTensorlakeConfigFlags registers mechanical bindings without selecting a provider.
func RegisterTensorlakeConfigFlags(fs *flag.FlagSet, defaults TensorlakeConfig) TensorlakeConfigFlagValues {
	var values TensorlakeConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// TensorlakeConfigVisitedFlags records raw flag visits, independently of application.
type TensorlakeConfigVisitedFlags struct {
	APIURL bool
}

// TensorlakeConfigFlagPresence reports visits for tracked flag bindings.
func TensorlakeConfigFlagPresence(fs *flag.FlagSet) TensorlakeConfigVisitedFlags {
	var visited TensorlakeConfigVisitedFlags
	recordConfigFlagVisits[TensorlakeConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values TensorlakeConfigFlagValues) Apply(cfg *TensorlakeConfig, fs *flag.FlagSet) (TensorlakeConfigApplied, error) {
	var applied TensorlakeConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
