// Code generated by scripts/configgen from config_sealos_devbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileSealosDevboxConfig struct {
	Kubectl         string `yaml:"kubectl,omitempty"`
	Kubeconfig      string `yaml:"kubeconfig,omitempty"`
	Context         string `yaml:"context,omitempty"`
	Namespace       string `yaml:"namespace,omitempty"`
	Image           string `yaml:"image,omitempty"`
	TemplateID      string `yaml:"templateID,omitempty"`
	CPU             string `yaml:"cpu,omitempty"`
	Memory          string `yaml:"memory,omitempty"`
	StorageLimit    string `yaml:"storageLimit,omitempty"`
	Network         string `yaml:"network,omitempty"`
	SSHGatewayHost  string `yaml:"sshGatewayHost,omitempty"`
	SSHGatewayPort  string `yaml:"sshGatewayPort,omitempty"`
	SSHUser         string `yaml:"sshUser,omitempty"`
	WorkRoot        string `yaml:"workRoot,omitempty"`
	NodeHost        string `yaml:"nodeHost,omitempty"`
	DeleteOnRelease *bool  `yaml:"deleteOnRelease,omitempty"`
}

const SealosDevboxConfigDefaultKubectl string = "kubectl"
const SealosDevboxConfigDefaultNamespace string = "default"
const SealosDevboxConfigDefaultCPU string = "2"
const SealosDevboxConfigDefaultMemory string = "4Gi"
const SealosDevboxConfigDefaultStorageLimit string = "20Gi"
const SealosDevboxConfigDefaultNetwork string = "SSHGate"
const SealosDevboxConfigDefaultSSHGatewayPort string = "2233"
const SealosDevboxConfigDefaultSSHUser string = "devbox"
const SealosDevboxConfigDefaultWorkRoot string = "/home/devbox/project"

func defaultSealosDevboxConfig() SealosDevboxConfig {
	return SealosDevboxConfig{
		Kubectl:        SealosDevboxConfigDefaultKubectl,
		Namespace:      SealosDevboxConfigDefaultNamespace,
		CPU:            SealosDevboxConfigDefaultCPU,
		Memory:         SealosDevboxConfigDefaultMemory,
		StorageLimit:   SealosDevboxConfigDefaultStorageLimit,
		Network:        SealosDevboxConfigDefaultNetwork,
		SSHGatewayPort: SealosDevboxConfigDefaultSSHGatewayPort,
		SSHUser:        SealosDevboxConfigDefaultSSHUser,
		WorkRoot:       SealosDevboxConfigDefaultWorkRoot,
	}
}

// SealosDevboxConfigApplied records accepted assignments during one application.
type SealosDevboxConfigApplied struct {
	InputAccepted   bool
	Kubectl         bool
	Kubeconfig      bool
	WorkRoot        bool
	DeleteOnRelease bool
}

func (cfg *SealosDevboxConfig) applyFile(file *fileSealosDevboxConfig, trusted bool) (SealosDevboxConfigApplied, error) {
	var applied SealosDevboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "sealos-devbox")
	return applied, err
}

func (cfg *SealosDevboxConfig) applyEnv() (SealosDevboxConfigApplied, error) {
	var applied SealosDevboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 16)
	return applied, err
}

// SealosDevboxConfigFlagValues holds parsed values; only visited flags are applied.
type SealosDevboxConfigFlagValues struct {
	Kubectl         *string
	Kubeconfig      *string
	Context         *string
	Namespace       *string
	Image           *string
	TemplateID      *string
	CPU             *string
	Memory          *string
	StorageLimit    *string
	Network         *string
	SSHGatewayHost  *string
	SSHGatewayPort  *string
	SSHUser         *string
	WorkRoot        *string
	NodeHost        *string
	DeleteOnRelease *bool
}

// RegisterSealosDevboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterSealosDevboxConfigFlags(fs *flag.FlagSet, defaults SealosDevboxConfig) SealosDevboxConfigFlagValues {
	var values SealosDevboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// SealosDevboxConfigVisitedFlags records raw flag visits, independently of application.
type SealosDevboxConfigVisitedFlags struct {
	Kubectl         bool
	Kubeconfig      bool
	WorkRoot        bool
	DeleteOnRelease bool
}

// SealosDevboxConfigFlagPresence reports visits for tracked flag bindings.
func SealosDevboxConfigFlagPresence(fs *flag.FlagSet) SealosDevboxConfigVisitedFlags {
	var visited SealosDevboxConfigVisitedFlags
	recordConfigFlagVisits[SealosDevboxConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values SealosDevboxConfigFlagValues) Apply(cfg *SealosDevboxConfig, fs *flag.FlagSet) (SealosDevboxConfigApplied, error) {
	var applied SealosDevboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
