// Code generated by scripts/configgen from config_xcpng.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileXCPNgConfig struct {
	APIURL       string `yaml:"apiUrl,omitempty"`
	Username     string `yaml:"username,omitempty"`
	Password     string `yaml:"password,omitempty"`
	Template     string `yaml:"template,omitempty"`
	TemplateUUID string `yaml:"templateUuid,omitempty"`
	SR           string `yaml:"sr,omitempty"`
	SRUUID       string `yaml:"srUuid,omitempty"`
	Network      string `yaml:"network,omitempty"`
	NetworkUUID  string `yaml:"networkUuid,omitempty"`
	Host         string `yaml:"host,omitempty"`
	User         string `yaml:"user,omitempty"`
	WorkRoot     string `yaml:"workRoot,omitempty"`
	InsecureTLS  *bool  `yaml:"insecureTLS,omitempty"`
}

const XCPNgConfigDefaultUser string = "crabbox"

func defaultXCPNgConfig() XCPNgConfig {
	return XCPNgConfig{
		User: XCPNgConfigDefaultUser,
	}
}

// XCPNgConfigApplied records accepted assignments during one application.
type XCPNgConfigApplied struct {
	InputAccepted bool
	Template      bool
	TemplateUUID  bool
	SR            bool
	SRUUID        bool
	Network       bool
	NetworkUUID   bool
	User          bool
	WorkRoot      bool
}

func (cfg *XCPNgConfig) applyFile(file *fileXCPNgConfig, trusted bool) (XCPNgConfigApplied, error) {
	var applied XCPNgConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "xcp-ng")
	return applied, err
}

func (cfg *XCPNgConfig) applyEnv() (XCPNgConfigApplied, error) {
	var applied XCPNgConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 13)
	return applied, err
}

// XCPNgConfigFlagValues holds parsed values; only visited flags are applied.
type XCPNgConfigFlagValues struct {
	APIURL       *string
	Username     *string
	Template     *string
	TemplateUUID *string
	SR           *string
	SRUUID       *string
	Network      *string
	NetworkUUID  *string
	Host         *string
	User         *string
	WorkRoot     *string
	InsecureTLS  *bool
}

// RegisterXCPNgConfigFlags registers mechanical bindings without selecting a provider.
func RegisterXCPNgConfigFlags(fs *flag.FlagSet, defaults XCPNgConfig) XCPNgConfigFlagValues {
	var values XCPNgConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// XCPNgConfigVisitedFlags records raw flag visits, independently of application.
type XCPNgConfigVisitedFlags struct {
	Template     bool
	TemplateUUID bool
	SR           bool
	SRUUID       bool
	Network      bool
	NetworkUUID  bool
	User         bool
	WorkRoot     bool
}

// XCPNgConfigFlagPresence reports visits for tracked flag bindings.
func XCPNgConfigFlagPresence(fs *flag.FlagSet) XCPNgConfigVisitedFlags {
	var visited XCPNgConfigVisitedFlags
	recordConfigFlagVisits[XCPNgConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values XCPNgConfigFlagValues) Apply(cfg *XCPNgConfig, fs *flag.FlagSet) (XCPNgConfigApplied, error) {
	var applied XCPNgConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
