// Code generated by scripts/configgen from config_docker_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileDockerSandboxConfig struct {
	CLIPath         string    `yaml:"cliPath,omitempty"`
	Agent           string    `yaml:"agent,omitempty"`
	Template        *string   `yaml:"template,omitempty"`
	CPUs            *float64  `yaml:"cpus,omitempty"`
	Memory          *string   `yaml:"memory,omitempty"`
	Clone           *bool     `yaml:"clone,omitempty"`
	Workdir         *string   `yaml:"workdir,omitempty"`
	ExtraWorkspaces *[]string `yaml:"extraWorkspaces,omitempty"`
	MCP             *[]string `yaml:"mcp,omitempty"`
	Kit             *[]string `yaml:"kit,omitempty"`
}

const DockerSandboxConfigDefaultCLIPath string = "sbx"
const DockerSandboxConfigDefaultAgent string = "shell"

func defaultDockerSandboxConfig() DockerSandboxConfig {
	return DockerSandboxConfig{
		CLIPath: DockerSandboxConfigDefaultCLIPath,
		Agent:   DockerSandboxConfigDefaultAgent,
	}
}

// DockerSandboxConfigApplied records accepted assignments during one application.
type DockerSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *DockerSandboxConfig) applyFile(file *fileDockerSandboxConfig) (DockerSandboxConfigApplied, error) {
	var applied DockerSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "docker-sandbox")
	return applied, err
}

func (cfg *DockerSandboxConfig) applyEnv() (DockerSandboxConfigApplied, error) {
	var applied DockerSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 10)
	return applied, err
}

// DockerSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type DockerSandboxConfigFlagValues struct {
	CLIPath         *string
	Agent           *string
	Template        *string
	CPUs            *float64
	Memory          *string
	Clone           *bool
	Workdir         *string
	ExtraWorkspaces *appendTrimmedNonemptyListFlag
	MCP             *appendTrimmedNonemptyListFlag
	Kit             *appendTrimmedNonemptyListFlag
}

// RegisterDockerSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterDockerSandboxConfigFlags(fs *flag.FlagSet, defaults DockerSandboxConfig) DockerSandboxConfigFlagValues {
	var values DockerSandboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values DockerSandboxConfigFlagValues) Apply(cfg *DockerSandboxConfig, fs *flag.FlagSet) (DockerSandboxConfigApplied, error) {
	var applied DockerSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
