// Code generated by scripts/configgen from config_railway.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileRailwayConfig struct {
	APIURL        string `yaml:"apiUrl,omitempty"`
	ProjectID     string `yaml:"projectId,omitempty"`
	EnvironmentID string `yaml:"environmentId,omitempty"`
}

const RailwayConfigDefaultAPIURL string = "https://backboard.railway.com/graphql/v2"

func defaultRailwayConfig() RailwayConfig {
	return RailwayConfig{
		APIURL: RailwayConfigDefaultAPIURL,
	}
}

// RailwayConfigApplied records accepted assignments during one application.
type RailwayConfigApplied struct {
	InputAccepted bool
	APIToken      bool
	APIURL        bool
}

func (cfg *RailwayConfig) applyFile(file *fileRailwayConfig) (RailwayConfigApplied, error) {
	var applied RailwayConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "railway")
	return applied, err
}

func (cfg *RailwayConfig) applyEnv() (RailwayConfigApplied, error) {
	var applied RailwayConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 4)
	return applied, err
}

// RailwayConfigFlagValues holds parsed values; only visited flags are applied.
type RailwayConfigFlagValues struct {
	APIURL        *string
	ProjectID     *string
	EnvironmentID *string
}

// RegisterRailwayConfigFlags registers mechanical bindings without selecting a provider.
func RegisterRailwayConfigFlags(fs *flag.FlagSet, defaults RailwayConfig) RailwayConfigFlagValues {
	var values RailwayConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// RailwayConfigVisitedFlags records raw flag visits, independently of application.
type RailwayConfigVisitedFlags struct {
	APIURL bool
}

// RailwayConfigFlagPresence reports visits for tracked flag bindings.
func RailwayConfigFlagPresence(fs *flag.FlagSet) RailwayConfigVisitedFlags {
	var visited RailwayConfigVisitedFlags
	recordConfigFlagVisits[RailwayConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values RailwayConfigFlagValues) Apply(cfg *RailwayConfig, fs *flag.FlagSet) (RailwayConfigApplied, error) {
	var applied RailwayConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
