// Code generated by scripts/configgen from config_machine0.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileMachine0Config struct {
	CLIPath       string `yaml:"cliPath,omitempty"`
	Image         string `yaml:"image,omitempty"`
	ImageVersion  *int   `yaml:"imageVersion,omitempty"`
	DesktopImage  string `yaml:"desktopImage,omitempty"`
	Size          string `yaml:"size,omitempty"`
	Region        string `yaml:"region,omitempty"`
	Key           string `yaml:"key,omitempty"`
	WorkRoot      string `yaml:"workRoot,omitempty"`
	ReleasePolicy string `yaml:"releasePolicy,omitempty"`
	CreateTimeout string `yaml:"createTimeout,omitempty"`
	PollInterval  string `yaml:"pollInterval,omitempty"`
}

const Machine0ConfigDefaultCLIPath string = "machine0"
const Machine0ConfigDefaultImage string = "ubuntu-24-04-loaded"
const Machine0ConfigDefaultSize string = "large"
const Machine0ConfigDefaultRegion string = "eu"
const Machine0ConfigDefaultReleasePolicy string = "destroy"
const Machine0ConfigDefaultCreateTimeout time.Duration = 900 * time.Second
const Machine0ConfigDefaultPollInterval time.Duration = 60 * time.Second

func defaultMachine0Config() Machine0Config {
	return Machine0Config{
		CLIPath:       Machine0ConfigDefaultCLIPath,
		Image:         Machine0ConfigDefaultImage,
		Size:          Machine0ConfigDefaultSize,
		Region:        Machine0ConfigDefaultRegion,
		ReleasePolicy: Machine0ConfigDefaultReleasePolicy,
		CreateTimeout: Machine0ConfigDefaultCreateTimeout,
		PollInterval:  Machine0ConfigDefaultPollInterval,
	}
}

// Machine0ConfigApplied records accepted assignments during one application.
type Machine0ConfigApplied struct {
	InputAccepted bool
	Size          bool
	WorkRoot      bool
}

func (cfg *Machine0Config) applyFile(file *fileMachine0Config) (Machine0ConfigApplied, error) {
	var applied Machine0ConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "machine0")
	return applied, err
}

func (cfg *Machine0Config) applyEnv() (Machine0ConfigApplied, error) {
	var applied Machine0ConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 11)
	return applied, err
}

// Machine0ConfigFlagValues holds parsed values; only visited flags are applied.
type Machine0ConfigFlagValues struct {
	CLIPath       *string
	Image         *string
	ImageVersion  *int
	DesktopImage  *string
	Size          *string
	Region        *string
	Key           *string
	WorkRoot      *string
	ReleasePolicy *string
	CreateTimeout *string
	PollInterval  *string
}

// RegisterMachine0ConfigFlags registers mechanical bindings without selecting a provider.
func RegisterMachine0ConfigFlags(fs *flag.FlagSet, defaults Machine0Config) Machine0ConfigFlagValues {
	var values Machine0ConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Machine0ConfigVisitedFlags records raw flag visits, independently of application.
type Machine0ConfigVisitedFlags struct {
	Size     bool
	WorkRoot bool
}

// Machine0ConfigFlagPresence reports visits for tracked flag bindings.
func Machine0ConfigFlagPresence(fs *flag.FlagSet) Machine0ConfigVisitedFlags {
	var visited Machine0ConfigVisitedFlags
	recordConfigFlagVisits[Machine0Config](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values Machine0ConfigFlagValues) Apply(cfg *Machine0Config, fs *flag.FlagSet) (Machine0ConfigApplied, error) {
	var applied Machine0ConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
