// Code generated by scripts/configgen from config_tart.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileTartConfig struct {
	Image    string `yaml:"image,omitempty"`
	User     string `yaml:"user,omitempty"`
	Password string `yaml:"password,omitempty"`
	WorkRoot string `yaml:"workRoot,omitempty"`
	CPUs     *int   `yaml:"cpus,omitempty"`
	Memory   *int   `yaml:"memory,omitempty"`
	Disk     *int   `yaml:"disk,omitempty"`
}

const TartConfigDefaultUser string = "admin"
const TartConfigDefaultCPUs int = 4
const TartConfigDefaultMemory int = 8192

func defaultTartConfig() TartConfig {
	return TartConfig{
		User:   TartConfigDefaultUser,
		CPUs:   TartConfigDefaultCPUs,
		Memory: TartConfigDefaultMemory,
	}
}

// TartConfigApplied records accepted assignments during one application.
type TartConfigApplied struct {
	InputAccepted bool
	Image         bool
}

func (cfg *TartConfig) applyFile(file *fileTartConfig) (TartConfigApplied, error) {
	var applied TartConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "tart")
	return applied, err
}

func (cfg *TartConfig) applyEnv() (TartConfigApplied, error) {
	var applied TartConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 7)
	return applied, err
}

// TartConfigFlagValues holds parsed values; only visited flags are applied.
type TartConfigFlagValues struct {
	Image  *string
	User   *string
	CPUs   *int
	Memory *int
	Disk   *int
}

// RegisterTartConfigFlags registers mechanical bindings without selecting a provider.
func RegisterTartConfigFlags(fs *flag.FlagSet, defaults TartConfig) TartConfigFlagValues {
	var values TartConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// TartConfigVisitedFlags records raw flag visits, independently of application.
type TartConfigVisitedFlags struct {
	Image  bool
	User   bool
	CPUs   bool
	Memory bool
	Disk   bool
}

// TartConfigFlagPresence reports visits for tracked flag bindings.
func TartConfigFlagPresence(fs *flag.FlagSet) TartConfigVisitedFlags {
	var visited TartConfigVisitedFlags
	recordConfigFlagVisits[TartConfig](fs, &visited)
	return visited
}
