// Code generated by scripts/configgen from config_nvidia_brev.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileNvidiaBrevConfig struct {
	CLI           string `yaml:"cli,omitempty"`
	Org           string `yaml:"org,omitempty"`
	Type          string `yaml:"type,omitempty"`
	GPUName       string `yaml:"gpuName,omitempty"`
	Provider      string `yaml:"provider,omitempty"`
	Mode          string `yaml:"mode,omitempty"`
	Launchable    string `yaml:"launchable,omitempty"`
	StartupScript string `yaml:"startupScript,omitempty"`
	ReleaseAction string `yaml:"releaseAction,omitempty"`
	Target        string `yaml:"target,omitempty"`
	User          string `yaml:"user,omitempty"`
	WorkRoot      string `yaml:"workRoot,omitempty"`
}

const NvidiaBrevConfigDefaultCLI string = "brev"
const NvidiaBrevConfigDefaultGPUName string = "A100"
const NvidiaBrevConfigDefaultMode string = "vm"
const NvidiaBrevConfigDefaultReleaseAction string = "delete"
const NvidiaBrevConfigDefaultTarget string = "container"
const NvidiaBrevConfigDefaultWorkRoot string = "/tmp/crabbox"

func defaultNvidiaBrevConfig() NvidiaBrevConfig {
	return NvidiaBrevConfig{
		CLI:           NvidiaBrevConfigDefaultCLI,
		GPUName:       NvidiaBrevConfigDefaultGPUName,
		Mode:          NvidiaBrevConfigDefaultMode,
		ReleaseAction: NvidiaBrevConfigDefaultReleaseAction,
		Target:        NvidiaBrevConfigDefaultTarget,
		WorkRoot:      NvidiaBrevConfigDefaultWorkRoot,
	}
}

// NvidiaBrevConfigApplied records accepted assignments during one application.
type NvidiaBrevConfigApplied struct {
	InputAccepted bool
	ReleaseAction bool
	Target        bool
	WorkRoot      bool
}

func (cfg *NvidiaBrevConfig) applyFile(file *fileNvidiaBrevConfig, trusted bool) (NvidiaBrevConfigApplied, error) {
	var applied NvidiaBrevConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "nvidia-brev")
	return applied, err
}

func (cfg *NvidiaBrevConfig) applyEnv() (NvidiaBrevConfigApplied, error) {
	var applied NvidiaBrevConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 12)
	return applied, err
}

// NvidiaBrevConfigFlagValues holds parsed values; only visited flags are applied.
type NvidiaBrevConfigFlagValues struct {
	CLI           *string
	Org           *string
	Type          *string
	GPUName       *string
	Provider      *string
	Mode          *string
	Launchable    *string
	StartupScript *string
	ReleaseAction *string
	Target        *string
	User          *string
	WorkRoot      *string
}

// RegisterNvidiaBrevConfigFlags registers mechanical bindings without selecting a provider.
func RegisterNvidiaBrevConfigFlags(fs *flag.FlagSet, defaults NvidiaBrevConfig) NvidiaBrevConfigFlagValues {
	var values NvidiaBrevConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// NvidiaBrevConfigVisitedFlags records raw flag visits, independently of application.
type NvidiaBrevConfigVisitedFlags struct {
	ReleaseAction bool
	Target        bool
	WorkRoot      bool
}

// NvidiaBrevConfigFlagPresence reports visits for tracked flag bindings.
func NvidiaBrevConfigFlagPresence(fs *flag.FlagSet) NvidiaBrevConfigVisitedFlags {
	var visited NvidiaBrevConfigVisitedFlags
	recordConfigFlagVisits[NvidiaBrevConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values NvidiaBrevConfigFlagValues) Apply(cfg *NvidiaBrevConfig, fs *flag.FlagSet) (NvidiaBrevConfigApplied, error) {
	var applied NvidiaBrevConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
