// Code generated by scripts/configgen from config_hyperv.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileHyperVConfig struct {
	Image         string `yaml:"image,omitempty"`
	User          string `yaml:"user,omitempty"`
	WorkRoot      string `yaml:"workRoot,omitempty"`
	CPUs          int    `yaml:"cpus,omitempty"`
	Memory        int    `yaml:"memory,omitempty"`
	Switch        string `yaml:"switch,omitempty"`
	GuestPassword string `yaml:"guestPassword,omitempty"`
	InitPassword  *bool  `yaml:"initPassword,omitempty"`
}

const HyperVConfigDefaultUser string = "crabbox"
const HyperVConfigDefaultCPUs int = 4
const HyperVConfigDefaultMemory int = 8192
const HyperVConfigDefaultSwitch string = "Default Switch"

func defaultHyperVConfig() HyperVConfig {
	return HyperVConfig{
		User:   HyperVConfigDefaultUser,
		CPUs:   HyperVConfigDefaultCPUs,
		Memory: HyperVConfigDefaultMemory,
		Switch: HyperVConfigDefaultSwitch,
	}
}

// HyperVConfigApplied records accepted assignments during one application.
type HyperVConfigApplied struct {
	InputAccepted bool
}

func (cfg *HyperVConfig) applyFile(file *fileHyperVConfig) (HyperVConfigApplied, error) {
	var applied HyperVConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "hyperv")
	return applied, err
}

func (cfg *HyperVConfig) applyEnv() (HyperVConfigApplied, error) {
	var applied HyperVConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 8)
	return applied, err
}

// HyperVConfigFlagValues holds parsed values; only visited flags are applied.
type HyperVConfigFlagValues struct {
	Image        *string
	User         *string
	WorkRoot     *string
	CPUs         *int
	Memory       *int
	Switch       *string
	InitPassword *bool
}

// RegisterHyperVConfigFlags registers mechanical bindings without selecting a provider.
func RegisterHyperVConfigFlags(fs *flag.FlagSet, defaults HyperVConfig) HyperVConfigFlagValues {
	var values HyperVConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values HyperVConfigFlagValues) Apply(cfg *HyperVConfig, fs *flag.FlagSet) (HyperVConfigApplied, error) {
	var applied HyperVConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
