// Code generated by scripts/configgen from config_orgo.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileOrgoConfig struct {
	APIKey      string `yaml:"apiKey,omitempty"`
	APIBase     string `yaml:"apiBase,omitempty"`
	WorkspaceID string `yaml:"workspaceID,omitempty"`
	RAMGB       int    `yaml:"ramGB,omitempty"`
	CPUs        int    `yaml:"cpus,omitempty"`
	DiskGB      int    `yaml:"diskGB,omitempty"`
	Resolution  string `yaml:"resolution,omitempty"`
}

const OrgoConfigDefaultAPIBase string = "https://www.orgo.ai/api"
const OrgoConfigDefaultRAMGB int = 4
const OrgoConfigDefaultCPUs int = 1
const OrgoConfigDefaultDiskGB int = 8
const OrgoConfigDefaultResolution string = "1280x720x24"

func defaultOrgoConfig() OrgoConfig {
	return OrgoConfig{
		APIBase:    OrgoConfigDefaultAPIBase,
		RAMGB:      OrgoConfigDefaultRAMGB,
		CPUs:       OrgoConfigDefaultCPUs,
		DiskGB:     OrgoConfigDefaultDiskGB,
		Resolution: OrgoConfigDefaultResolution,
	}
}

// OrgoConfigApplied records accepted assignments during one application.
type OrgoConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	APIBase       bool
}

func (cfg *OrgoConfig) applyFile(file *fileOrgoConfig, trusted bool) (OrgoConfigApplied, error) {
	var applied OrgoConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "orgo")
	return applied, err
}

func (cfg *OrgoConfig) applyEnv() (OrgoConfigApplied, error) {
	var applied OrgoConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 7)
	return applied, err
}

// OrgoConfigFlagValues holds parsed values; only visited flags are applied.
type OrgoConfigFlagValues struct {
	APIBase     *string
	WorkspaceID *string
	RAMGB       *int
	CPUs        *int
	DiskGB      *int
	Resolution  *string
}

// RegisterOrgoConfigFlags registers mechanical bindings without selecting a provider.
func RegisterOrgoConfigFlags(fs *flag.FlagSet, defaults OrgoConfig) OrgoConfigFlagValues {
	var values OrgoConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// OrgoConfigVisitedFlags records raw flag visits, independently of application.
type OrgoConfigVisitedFlags struct {
	APIBase bool
}

// OrgoConfigFlagPresence reports visits for tracked flag bindings.
func OrgoConfigFlagPresence(fs *flag.FlagSet) OrgoConfigVisitedFlags {
	var visited OrgoConfigVisitedFlags
	recordConfigFlagVisits[OrgoConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values OrgoConfigFlagValues) Apply(cfg *OrgoConfig, fs *flag.FlagSet) (OrgoConfigApplied, error) {
	var applied OrgoConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
