// Code generated by scripts/configgen from config_wandb.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileWandbConfig struct {
	APIKey             string `yaml:"apiKey,omitempty"`
	DefaultImage       string `yaml:"defaultImage,omitempty"`
	MaxLifetimeSeconds int    `yaml:"maxLifetimeSeconds,omitempty"`
}

func defaultWandbConfig() WandbConfig {
	return WandbConfig{}
}

func (cfg *WandbConfig) applyFile(file *fileWandbConfig) error {
	if file == nil {
		return nil
	}
	if file.APIKey != "" {
		cfg.APIKey = file.APIKey
	}
	if file.DefaultImage != "" {
		cfg.DefaultImage = file.DefaultImage
	}
	if file.MaxLifetimeSeconds > 0 {
		cfg.MaxLifetimeSeconds = file.MaxLifetimeSeconds
	}
	return nil
}

func (cfg *WandbConfig) applyEnv() error {
	cfg.APIKey = getenv("CRABBOX_WANDB_API_KEY", cfg.APIKey)
	cfg.DefaultImage = getenv("CRABBOX_WANDB_DEFAULT_IMAGE", getenv("WANDB_DEFAULT_IMAGE", cfg.DefaultImage))
	cfg.MaxLifetimeSeconds = getenvInt("CRABBOX_WANDB_MAX_LIFETIME_SECONDS", getenvInt("WANDB_MAX_LIFETIME_SECONDS", cfg.MaxLifetimeSeconds))
	return nil
}

// WandbConfigFlagValues holds parsed values; only visited flags are applied.
type WandbConfigFlagValues struct {
	DefaultImage       *string
	MaxLifetimeSeconds *int
}

// RegisterWandbConfigFlags registers mechanical bindings without selecting a provider.
func RegisterWandbConfigFlags(fs *flag.FlagSet, defaults WandbConfig) WandbConfigFlagValues {
	return WandbConfigFlagValues{
		DefaultImage:       fs.String("wandb-image", defaults.DefaultImage, "Container image used when acquiring a new W&B sandbox"),
		MaxLifetimeSeconds: fs.Int("wandb-max-lifetime", defaults.MaxLifetimeSeconds, "Maximum sandbox lifetime in seconds before W&B reclaims it"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values WandbConfigFlagValues) Apply(cfg *WandbConfig, fs *flag.FlagSet) {
	if flagWasSet(fs, "wandb-image") {
		cfg.DefaultImage = *values.DefaultImage
	}
	if flagWasSet(fs, "wandb-max-lifetime") {
		cfg.MaxLifetimeSeconds = *values.MaxLifetimeSeconds
	}
}
