// Code generated by scripts/configgen from config_semaphore.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileSemaphoreConfig struct {
	Host        string `yaml:"host,omitempty"`
	Token       string `yaml:"token,omitempty"`
	Project     string `yaml:"project,omitempty"`
	Machine     string `yaml:"machine,omitempty"`
	OSImage     string `yaml:"osImage,omitempty"`
	IdleTimeout string `yaml:"idleTimeout,omitempty"`
}

const SemaphoreConfigFlagFallbackMachine string = "f1-standard-2"
const SemaphoreConfigFlagFallbackOSImage string = "ubuntu2204"
const SemaphoreConfigFlagFallbackIdleTimeout string = "30m"

func defaultSemaphoreConfig() SemaphoreConfig {
	return SemaphoreConfig{}
}

// SemaphoreConfigApplied records accepted assignments during one application.
type SemaphoreConfigApplied struct {
	InputAccepted bool
	Host          bool
	Token         bool
}

func (cfg *SemaphoreConfig) applyFile(file *fileSemaphoreConfig) (SemaphoreConfigApplied, error) {
	var applied SemaphoreConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "semaphore")
	return applied, err
}

func (cfg *SemaphoreConfig) applyEnv() (SemaphoreConfigApplied, error) {
	var applied SemaphoreConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// SemaphoreConfigFlagValues holds parsed values; only visited flags are applied.
type SemaphoreConfigFlagValues struct {
	Host        *string
	Project     *string
	Machine     *string
	OSImage     *string
	IdleTimeout *string
}

// RegisterSemaphoreConfigFlags registers mechanical bindings without selecting a provider.
func RegisterSemaphoreConfigFlags(fs *flag.FlagSet, defaults SemaphoreConfig) SemaphoreConfigFlagValues {
	var values SemaphoreConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// SemaphoreConfigVisitedFlags records raw flag visits, independently of application.
type SemaphoreConfigVisitedFlags struct {
	Host bool
}

// SemaphoreConfigFlagPresence reports visits for tracked flag bindings.
func SemaphoreConfigFlagPresence(fs *flag.FlagSet) SemaphoreConfigVisitedFlags {
	var visited SemaphoreConfigVisitedFlags
	recordConfigFlagVisits[SemaphoreConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values SemaphoreConfigFlagValues) Apply(cfg *SemaphoreConfig, fs *flag.FlagSet) (SemaphoreConfigApplied, error) {
	var applied SemaphoreConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
