// Code generated by scripts/configgen from config_ovh.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileOVHConfig struct {
	Endpoint  string `yaml:"endpoint,omitempty"`
	ProjectID string `yaml:"projectId,omitempty"`
	Region    string `yaml:"region,omitempty"`
	Image     string `yaml:"image,omitempty"`
	Flavor    string `yaml:"flavor,omitempty"`
}

const OVHConfigDefaultEndpoint string = "https://api.us.ovhcloud.com/1.0"
const OVHConfigDefaultImage string = "Ubuntu 24.04"
const OVHConfigDefaultFlavor string = "b3-8"

func defaultOVHConfig() OVHConfig {
	return OVHConfig{
		Endpoint: OVHConfigDefaultEndpoint,
		Image:    OVHConfigDefaultImage,
		Flavor:   OVHConfigDefaultFlavor,
	}
}

// OVHConfigApplied records accepted assignments during one application.
type OVHConfigApplied struct {
	InputAccepted bool
	Image         bool
}

func (cfg *OVHConfig) applyFile(file *fileOVHConfig, trusted bool) (OVHConfigApplied, error) {
	var applied OVHConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "ovh")
	return applied, err
}

func (cfg *OVHConfig) applyEnv() (OVHConfigApplied, error) {
	var applied OVHConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// OVHConfigFlagValues holds parsed values; only visited flags are applied.
type OVHConfigFlagValues struct {
	Endpoint  *string
	ProjectID *string
	Region    *string
	Image     *string
	Flavor    *string
}

// RegisterOVHConfigFlags registers mechanical bindings without selecting a provider.
func RegisterOVHConfigFlags(fs *flag.FlagSet, defaults OVHConfig) OVHConfigFlagValues {
	var values OVHConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// OVHConfigVisitedFlags records raw flag visits, independently of application.
type OVHConfigVisitedFlags struct {
	Image bool
}

// OVHConfigFlagPresence reports visits for tracked flag bindings.
func OVHConfigFlagPresence(fs *flag.FlagSet) OVHConfigVisitedFlags {
	var visited OVHConfigVisitedFlags
	recordConfigFlagVisits[OVHConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values OVHConfigFlagValues) Apply(cfg *OVHConfig, fs *flag.FlagSet) (OVHConfigApplied, error) {
	var applied OVHConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
