// Code generated by scripts/configgen from config_phala.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type filePhalaConfig struct {
	CLIPath      string `yaml:"cli,omitempty"`
	InstanceType string `yaml:"instanceType,omitempty"`
	WorkRoot     string `yaml:"workRoot,omitempty"`
	NodeID       string `yaml:"nodeId,omitempty"`
	Compose      string `yaml:"compose,omitempty"`
	Attest       *bool  `yaml:"attest,omitempty"`
}

const PhalaConfigDefaultCLIPath string = "phala"
const PhalaConfigDefaultInstanceType string = "tdx.small"
const PhalaConfigDefaultWorkRoot string = "/var/volatile/crabbox"

func defaultPhalaConfig() PhalaConfig {
	return PhalaConfig{
		CLIPath:      PhalaConfigDefaultCLIPath,
		InstanceType: PhalaConfigDefaultInstanceType,
		WorkRoot:     PhalaConfigDefaultWorkRoot,
	}
}

// PhalaConfigApplied records accepted assignments during one application.
type PhalaConfigApplied struct {
	InputAccepted bool
	CLIPath       bool
	InstanceType  bool
	Compose       bool
}

func (cfg *PhalaConfig) applyFile(file *filePhalaConfig, trusted bool) (PhalaConfigApplied, error) {
	var applied PhalaConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "phala")
	return applied, err
}

func (cfg *PhalaConfig) applyEnv() (PhalaConfigApplied, error) {
	var applied PhalaConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// PhalaConfigFlagValues holds parsed values; only visited flags are applied.
type PhalaConfigFlagValues struct {
	CLIPath      *string
	InstanceType *string
	WorkRoot     *string
	NodeID       *string
	Compose      *string
	Attest       *bool
}

// RegisterPhalaConfigFlags registers mechanical bindings without selecting a provider.
func RegisterPhalaConfigFlags(fs *flag.FlagSet, defaults PhalaConfig) PhalaConfigFlagValues {
	var values PhalaConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// PhalaConfigVisitedFlags records raw flag visits, independently of application.
type PhalaConfigVisitedFlags struct {
	CLIPath      bool
	InstanceType bool
	WorkRoot     bool
	NodeID       bool
	Compose      bool
	Attest       bool
}

// PhalaConfigFlagPresence reports visits for tracked flag bindings.
func PhalaConfigFlagPresence(fs *flag.FlagSet) PhalaConfigVisitedFlags {
	var visited PhalaConfigVisitedFlags
	recordConfigFlagVisits[PhalaConfig](fs, &visited)
	return visited
}
