// Code generated by scripts/configgen from config_agentsandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileAgentSandboxConfig struct {
	Kubectl             string `yaml:"kubectl,omitempty"`
	Kubeconfig          string `yaml:"kubeconfig,omitempty"`
	Context             string `yaml:"context,omitempty"`
	Namespace           string `yaml:"namespace,omitempty"`
	WarmPool            string `yaml:"warmPool,omitempty"`
	Container           string `yaml:"container,omitempty"`
	Workdir             string `yaml:"workdir,omitempty"`
	SandboxReadyTimeout string `yaml:"sandboxReadyTimeout,omitempty"`
	PodReadyTimeout     string `yaml:"podReadyTimeout,omitempty"`
	ExecTimeoutSecs     *int   `yaml:"execTimeoutSecs,omitempty"`
	DeleteOnRelease     *bool  `yaml:"deleteOnRelease,omitempty"`
	ForgetMissing       *bool  `yaml:"forgetMissing,omitempty"`
}

const AgentSandboxConfigDefaultKubectl string = "kubectl"
const AgentSandboxConfigDefaultNamespace string = "default"
const AgentSandboxConfigDefaultWorkdir string = "/workspace/crabbox"
const AgentSandboxConfigDefaultSandboxReadyTimeout time.Duration = 180 * time.Second
const AgentSandboxConfigDefaultPodReadyTimeout time.Duration = 180 * time.Second
const AgentSandboxConfigDefaultExecTimeoutSecs int = 600
const AgentSandboxConfigDefaultDeleteOnRelease bool = true

func defaultAgentSandboxConfig() AgentSandboxConfig {
	return AgentSandboxConfig{
		Kubectl:             AgentSandboxConfigDefaultKubectl,
		Namespace:           AgentSandboxConfigDefaultNamespace,
		Workdir:             AgentSandboxConfigDefaultWorkdir,
		SandboxReadyTimeout: AgentSandboxConfigDefaultSandboxReadyTimeout,
		PodReadyTimeout:     AgentSandboxConfigDefaultPodReadyTimeout,
		ExecTimeoutSecs:     AgentSandboxConfigDefaultExecTimeoutSecs,
		DeleteOnRelease:     AgentSandboxConfigDefaultDeleteOnRelease,
	}
}

// AgentSandboxConfigApplied records accepted assignments during one application.
type AgentSandboxConfigApplied struct {
	InputAccepted   bool
	Kubeconfig      bool
	DeleteOnRelease bool
}

func (cfg *AgentSandboxConfig) applyFile(file *fileAgentSandboxConfig, trusted bool) (AgentSandboxConfigApplied, error) {
	var applied AgentSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "agentSandbox")
	return applied, err
}

func (cfg *AgentSandboxConfig) applyEnv() (AgentSandboxConfigApplied, error) {
	var applied AgentSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 12)
	return applied, err
}

// AgentSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type AgentSandboxConfigFlagValues struct {
	Kubectl             *string
	Kubeconfig          *string
	Context             *string
	Namespace           *string
	WarmPool            *string
	Container           *string
	Workdir             *string
	SandboxReadyTimeout *time.Duration
	PodReadyTimeout     *time.Duration
	ExecTimeoutSecs     *int
	DeleteOnRelease     *bool
	ForgetMissing       *bool
}

// RegisterAgentSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterAgentSandboxConfigFlags(fs *flag.FlagSet, defaults AgentSandboxConfig) AgentSandboxConfigFlagValues {
	var values AgentSandboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// AgentSandboxConfigVisitedFlags records raw flag visits, independently of application.
type AgentSandboxConfigVisitedFlags struct {
	Kubeconfig      bool
	DeleteOnRelease bool
}

// AgentSandboxConfigFlagPresence reports visits for tracked flag bindings.
func AgentSandboxConfigFlagPresence(fs *flag.FlagSet) AgentSandboxConfigVisitedFlags {
	var visited AgentSandboxConfigVisitedFlags
	recordConfigFlagVisits[AgentSandboxConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values AgentSandboxConfigFlagValues) Apply(cfg *AgentSandboxConfig, fs *flag.FlagSet) (AgentSandboxConfigApplied, error) {
	var applied AgentSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
