// Code generated by scripts/configgen from config_anthropic_sandbox_runtime.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileAnthropicSRTConfig struct {
	CLIPath  string  `yaml:"cliPath,omitempty"`
	Settings *string `yaml:"settings,omitempty"`
	Debug    *bool   `yaml:"debug,omitempty"`
}

const AnthropicSRTConfigDefaultCLIPath string = "srt"

func defaultAnthropicSRTConfig() AnthropicSRTConfig {
	return AnthropicSRTConfig{
		CLIPath: AnthropicSRTConfigDefaultCLIPath,
	}
}

// AnthropicSRTConfigApplied records accepted assignments during one application.
type AnthropicSRTConfigApplied struct {
	InputAccepted bool
}

func (cfg *AnthropicSRTConfig) applyFile(file *fileAnthropicSRTConfig) (AnthropicSRTConfigApplied, error) {
	var applied AnthropicSRTConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "anthropic-sandbox-runtime")
	return applied, err
}

func (cfg *AnthropicSRTConfig) applyEnv() (AnthropicSRTConfigApplied, error) {
	var applied AnthropicSRTConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 3)
	return applied, err
}

// AnthropicSRTConfigFlagValues holds parsed values; only visited flags are applied.
type AnthropicSRTConfigFlagValues struct {
	CLIPath  *string
	Settings *string
	Debug    *bool
}

// RegisterAnthropicSRTConfigFlags registers mechanical bindings without selecting a provider.
func RegisterAnthropicSRTConfigFlags(fs *flag.FlagSet, defaults AnthropicSRTConfig) AnthropicSRTConfigFlagValues {
	var values AnthropicSRTConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values AnthropicSRTConfigFlagValues) Apply(cfg *AnthropicSRTConfig, fs *flag.FlagSet) (AnthropicSRTConfigApplied, error) {
	var applied AnthropicSRTConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
