// Code generated by scripts/configgen from config_islo.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileIsloConfig struct {
	BaseURL        string `yaml:"baseUrl,omitempty"`
	Image          string `yaml:"image,omitempty"`
	Workdir        string `yaml:"workdir,omitempty"`
	GatewayProfile string `yaml:"gatewayProfile,omitempty"`
	SnapshotName   string `yaml:"snapshotName,omitempty"`
	VCPUs          int    `yaml:"vcpus,omitempty"`
	MemoryMB       int    `yaml:"memoryMB,omitempty"`
	DiskGB         int    `yaml:"diskGB,omitempty"`
	IdlePause      *bool  `yaml:"idlePause,omitempty"`
}

const IsloConfigDefaultBaseURL string = "https://api.islo.dev"
const IsloConfigDefaultWorkdir string = "crabbox"
const IsloConfigDefaultVCPUs int = 2
const IsloConfigDefaultMemoryMB int = 4096
const IsloConfigDefaultDiskGB int = 20

func defaultIsloConfig() IsloConfig {
	return IsloConfig{
		BaseURL:  IsloConfigDefaultBaseURL,
		Workdir:  IsloConfigDefaultWorkdir,
		VCPUs:    IsloConfigDefaultVCPUs,
		MemoryMB: IsloConfigDefaultMemoryMB,
		DiskGB:   IsloConfigDefaultDiskGB,
	}
}

// IsloConfigApplied records accepted assignments during one application.
type IsloConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	BaseURL       bool
	Image         bool
	VCPUs         bool
	MemoryMB      bool
	DiskGB        bool
}

func (cfg *IsloConfig) applyFile(file *fileIsloConfig) (IsloConfigApplied, error) {
	var applied IsloConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "islo")
	return applied, err
}

func (cfg *IsloConfig) applyEnv() (IsloConfigApplied, error) {
	var applied IsloConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 10)
	return applied, err
}

// IsloConfigFlagValues holds parsed values; only visited flags are applied.
type IsloConfigFlagValues struct {
	BaseURL        *string
	Image          *string
	Workdir        *string
	GatewayProfile *string
	SnapshotName   *string
	VCPUs          *int
	MemoryMB       *int
	DiskGB         *int
	IdlePause      *bool
}

// RegisterIsloConfigFlags registers mechanical bindings without selecting a provider.
func RegisterIsloConfigFlags(fs *flag.FlagSet, defaults IsloConfig) IsloConfigFlagValues {
	var values IsloConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// IsloConfigVisitedFlags records raw flag visits, independently of application.
type IsloConfigVisitedFlags struct {
	BaseURL  bool
	Image    bool
	VCPUs    bool
	MemoryMB bool
	DiskGB   bool
}

// IsloConfigFlagPresence reports visits for tracked flag bindings.
func IsloConfigFlagPresence(fs *flag.FlagSet) IsloConfigVisitedFlags {
	var visited IsloConfigVisitedFlags
	recordConfigFlagVisits[IsloConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values IsloConfigFlagValues) Apply(cfg *IsloConfig, fs *flag.FlagSet) (IsloConfigApplied, error) {
	var applied IsloConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
