// Code generated by scripts/configgen from config_multipass.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileMultipassConfig struct {
	CLIPath       string `yaml:"cliPath,omitempty"`
	Image         string `yaml:"image,omitempty"`
	User          string `yaml:"user,omitempty"`
	WorkRoot      string `yaml:"workRoot,omitempty"`
	CPUs          int    `yaml:"cpus,omitempty"`
	Memory        string `yaml:"memory,omitempty"`
	Disk          string `yaml:"disk,omitempty"`
	LaunchTimeout string `yaml:"launchTimeout,omitempty"`
}

const MultipassConfigDefaultCLIPath string = "multipass"
const MultipassConfigDefaultUser string = "crabbox"
const MultipassConfigDefaultCPUs int = 4
const MultipassConfigDefaultMemory string = "8G"
const MultipassConfigDefaultDisk string = "30G"
const MultipassConfigDefaultLaunchTimeout time.Duration = 1200 * time.Second

func defaultMultipassConfig() MultipassConfig {
	return MultipassConfig{
		CLIPath:       MultipassConfigDefaultCLIPath,
		User:          MultipassConfigDefaultUser,
		CPUs:          MultipassConfigDefaultCPUs,
		Memory:        MultipassConfigDefaultMemory,
		Disk:          MultipassConfigDefaultDisk,
		LaunchTimeout: MultipassConfigDefaultLaunchTimeout,
	}
}

// MultipassConfigApplied records accepted assignments during one application.
type MultipassConfigApplied struct {
	InputAccepted bool
	Image         bool
	User          bool
	WorkRoot      bool
}

func (cfg *MultipassConfig) applyFile(file *fileMultipassConfig) (MultipassConfigApplied, error) {
	var applied MultipassConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "multipass")
	return applied, err
}

func (cfg *MultipassConfig) applyEnv() (MultipassConfigApplied, error) {
	var applied MultipassConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 8)
	return applied, err
}

// MultipassConfigFlagValues holds parsed values; only visited flags are applied.
type MultipassConfigFlagValues struct {
	CLIPath       *string
	Image         *string
	User          *string
	WorkRoot      *string
	CPUs          *int
	Memory        *string
	Disk          *string
	LaunchTimeout *string
}

// RegisterMultipassConfigFlags registers mechanical bindings without selecting a provider.
func RegisterMultipassConfigFlags(fs *flag.FlagSet, defaults MultipassConfig) MultipassConfigFlagValues {
	var values MultipassConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// MultipassConfigVisitedFlags records raw flag visits, independently of application.
type MultipassConfigVisitedFlags struct {
	Image    bool
	User     bool
	WorkRoot bool
}

// MultipassConfigFlagPresence reports visits for tracked flag bindings.
func MultipassConfigFlagPresence(fs *flag.FlagSet) MultipassConfigVisitedFlags {
	var visited MultipassConfigVisitedFlags
	recordConfigFlagVisits[MultipassConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values MultipassConfigFlagValues) Apply(cfg *MultipassConfig, fs *flag.FlagSet) (MultipassConfigApplied, error) {
	var applied MultipassConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
