// Code generated by scripts/configgen from config_lume.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileLumeConfig struct {
	CLIPath  string `yaml:"cliPath,omitempty"`
	Base     string `yaml:"base,omitempty"`
	Storage  string `yaml:"storage,omitempty"`
	User     string `yaml:"user,omitempty"`
	WorkRoot string `yaml:"workRoot,omitempty"`
}

const LumeConfigDefaultCLIPath string = "lume"
const LumeConfigDefaultBase string = "crabbox-macos-golden"
const LumeConfigDefaultUser string = "lume"
const LumeConfigDefaultWorkRoot string = "/Users/lume/crabbox"

func defaultLumeConfig() LumeConfig {
	return LumeConfig{
		CLIPath:  LumeConfigDefaultCLIPath,
		Base:     LumeConfigDefaultBase,
		User:     LumeConfigDefaultUser,
		WorkRoot: LumeConfigDefaultWorkRoot,
	}
}

// LumeConfigApplied records accepted assignments during one application.
type LumeConfigApplied struct {
	InputAccepted bool
}

func (cfg *LumeConfig) applyFile(file *fileLumeConfig, trusted bool) (LumeConfigApplied, error) {
	var applied LumeConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "lume")
	return applied, err
}

func (cfg *LumeConfig) applyEnv() (LumeConfigApplied, error) {
	var applied LumeConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// LumeConfigFlagValues holds parsed values; only visited flags are applied.
type LumeConfigFlagValues struct {
	CLIPath  *string
	Base     *string
	Storage  *string
	User     *string
	WorkRoot *string
}

// RegisterLumeConfigFlags registers mechanical bindings without selecting a provider.
func RegisterLumeConfigFlags(fs *flag.FlagSet, defaults LumeConfig) LumeConfigFlagValues {
	var values LumeConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values LumeConfigFlagValues) Apply(cfg *LumeConfig, fs *flag.FlagSet) (LumeConfigApplied, error) {
	var applied LumeConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
