// Code generated by scripts/configgen from config_vultr.go; DO NOT EDIT.

package cli

import (
	"os"
)

type fileVultrConfig struct {
	Region        string   `yaml:"region,omitempty"`
	OS            string   `yaml:"os,omitempty"`
	Image         string   `yaml:"image,omitempty"`
	Snapshot      string   `yaml:"snapshot,omitempty"`
	FirewallGroup string   `yaml:"firewallGroup,omitempty"`
	VPCIDs        []string `yaml:"vpcIds,omitempty"`
	SSHCIDRs      []string `yaml:"sshCIDRs,omitempty"`
	UserScheme    string   `yaml:"userScheme,omitempty"`
}

func defaultVultrConfig() VultrConfig {
	return VultrConfig{}
}

func (cfg *VultrConfig) applyFile(file *fileVultrConfig) error {
	if file == nil {
		return nil
	}
	if file.Region != "" {
		cfg.Region = file.Region
	}
	if file.OS != "" {
		cfg.OS = file.OS
	}
	if file.Image != "" {
		cfg.Image = file.Image
	}
	if file.Snapshot != "" {
		cfg.Snapshot = file.Snapshot
	}
	if file.FirewallGroup != "" {
		cfg.FirewallGroup = file.FirewallGroup
	}
	if len(file.VPCIDs) > 0 {
		cfg.VPCIDs = file.VPCIDs
	}
	if len(file.SSHCIDRs) > 0 {
		cfg.SSHCIDRs = file.SSHCIDRs
	}
	if file.UserScheme != "" {
		cfg.UserScheme = file.UserScheme
	}
	return nil
}

func (cfg *VultrConfig) applyEnv() error {
	cfg.Region = getenv("CRABBOX_VULTR_REGION", cfg.Region)
	cfg.OS = getenv("CRABBOX_VULTR_OS", cfg.OS)
	cfg.Image = getenv("CRABBOX_VULTR_IMAGE", cfg.Image)
	cfg.Snapshot = getenv("CRABBOX_VULTR_SNAPSHOT", cfg.Snapshot)
	cfg.FirewallGroup = getenv("CRABBOX_VULTR_FIREWALL_GROUP", cfg.FirewallGroup)
	if value := os.Getenv("CRABBOX_VULTR_VPC_IDS"); value != "" {
		cfg.VPCIDs = splitCommaList(value)
	}
	if value := os.Getenv("CRABBOX_VULTR_SSH_CIDRS"); value != "" {
		cfg.SSHCIDRs = splitCommaList(value)
	}
	cfg.UserScheme = getenv("CRABBOX_VULTR_USER_SCHEME", cfg.UserScheme)
	return nil
}
