// Code generated by scripts/configgen from config_firecracker.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileFirecrackerConfig struct {
	Binary          string `yaml:"binary,omitempty"`
	Jailer          string `yaml:"jailer,omitempty"`
	Kernel          string `yaml:"kernel,omitempty"`
	RootFS          string `yaml:"rootfs,omitempty"`
	User            string `yaml:"user,omitempty"`
	WorkRoot        string `yaml:"workRoot,omitempty"`
	CPUs            *int   `yaml:"cpus,omitempty"`
	MemoryMiB       *int   `yaml:"memoryMiB,omitempty"`
	DiskMiB         *int   `yaml:"diskMiB,omitempty"`
	Network         string `yaml:"network,omitempty"`
	CNINetwork      string `yaml:"cniNetwork,omitempty"`
	CNIConfDir      string `yaml:"cniConfDir,omitempty"`
	CNIBinDir       string `yaml:"cniBinDir,omitempty"`
	LaunchTimeout   string `yaml:"launchTimeout,omitempty"`
	DeleteOnRelease *bool  `yaml:"deleteOnRelease,omitempty"`
}

const FirecrackerConfigDefaultBinary string = "firecracker"
const FirecrackerConfigDefaultKernel string = "/var/lib/crabbox/firecracker/vmlinux"
const FirecrackerConfigDefaultRootFS string = "/var/lib/crabbox/firecracker/rootfs.ext4"
const FirecrackerConfigDefaultUser string = "crabbox"
const FirecrackerConfigDefaultCPUs int = 4
const FirecrackerConfigDefaultMemoryMiB int = 4096
const FirecrackerConfigDefaultDiskMiB int = 16384
const FirecrackerConfigDefaultNetwork string = "cni"
const FirecrackerConfigDefaultCNINetwork string = "crabbox-firecracker"
const FirecrackerConfigDefaultCNIConfDir string = "/etc/cni/conf.d"
const FirecrackerConfigDefaultCNIBinDir string = "/opt/cni/bin"
const FirecrackerConfigDefaultLaunchTimeout time.Duration = 120 * time.Second
const FirecrackerConfigDefaultDeleteOnRelease bool = true

func defaultFirecrackerConfig() FirecrackerConfig {
	return FirecrackerConfig{
		Binary:          FirecrackerConfigDefaultBinary,
		Kernel:          FirecrackerConfigDefaultKernel,
		RootFS:          FirecrackerConfigDefaultRootFS,
		User:            FirecrackerConfigDefaultUser,
		CPUs:            FirecrackerConfigDefaultCPUs,
		MemoryMiB:       FirecrackerConfigDefaultMemoryMiB,
		DiskMiB:         FirecrackerConfigDefaultDiskMiB,
		Network:         FirecrackerConfigDefaultNetwork,
		CNINetwork:      FirecrackerConfigDefaultCNINetwork,
		CNIConfDir:      FirecrackerConfigDefaultCNIConfDir,
		CNIBinDir:       FirecrackerConfigDefaultCNIBinDir,
		LaunchTimeout:   FirecrackerConfigDefaultLaunchTimeout,
		DeleteOnRelease: FirecrackerConfigDefaultDeleteOnRelease,
	}
}

// FirecrackerConfigApplied records accepted assignments during one application.
type FirecrackerConfigApplied struct {
	InputAccepted   bool
	Binary          bool
	Jailer          bool
	Kernel          bool
	RootFS          bool
	User            bool
	WorkRoot        bool
	CNIConfDir      bool
	CNIBinDir       bool
	DeleteOnRelease bool
}

func (cfg *FirecrackerConfig) applyFile(file *fileFirecrackerConfig, trusted bool) (FirecrackerConfigApplied, error) {
	var applied FirecrackerConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "firecracker")
	return applied, err
}

func (cfg *FirecrackerConfig) applyEnv() (FirecrackerConfigApplied, error) {
	var applied FirecrackerConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 15)
	return applied, err
}

// FirecrackerConfigFlagValues holds parsed values; only visited flags are applied.
type FirecrackerConfigFlagValues struct {
	Binary          *string
	Jailer          *string
	Kernel          *string
	RootFS          *string
	User            *string
	WorkRoot        *string
	CPUs            *int
	MemoryMiB       *int
	DiskMiB         *int
	Network         *string
	CNINetwork      *string
	CNIConfDir      *string
	CNIBinDir       *string
	LaunchTimeout   *string
	DeleteOnRelease *bool
}

// RegisterFirecrackerConfigFlags registers mechanical bindings without selecting a provider.
func RegisterFirecrackerConfigFlags(fs *flag.FlagSet, defaults FirecrackerConfig) FirecrackerConfigFlagValues {
	var values FirecrackerConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// FirecrackerConfigVisitedFlags records raw flag visits, independently of application.
type FirecrackerConfigVisitedFlags struct {
	Binary          bool
	Jailer          bool
	Kernel          bool
	RootFS          bool
	User            bool
	WorkRoot        bool
	CNIConfDir      bool
	CNIBinDir       bool
	DeleteOnRelease bool
}

// FirecrackerConfigFlagPresence reports visits for tracked flag bindings.
func FirecrackerConfigFlagPresence(fs *flag.FlagSet) FirecrackerConfigVisitedFlags {
	var visited FirecrackerConfigVisitedFlags
	recordConfigFlagVisits[FirecrackerConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values FirecrackerConfigFlagValues) Apply(cfg *FirecrackerConfig, fs *flag.FlagSet) (FirecrackerConfigApplied, error) {
	var applied FirecrackerConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
