// Code generated by scripts/configgen from config_daytona.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileDaytonaConfig struct {
	APIURL           string `yaml:"apiUrl,omitempty"`
	Snapshot         string `yaml:"snapshot,omitempty"`
	Target           string `yaml:"target,omitempty"`
	User             string `yaml:"user,omitempty"`
	WorkRoot         string `yaml:"workRoot,omitempty"`
	SSHGatewayHost   string `yaml:"sshGatewayHost,omitempty"`
	SSHAccessMinutes int    `yaml:"sshAccessMinutes,omitempty"`
}

const DaytonaConfigDefaultAPIURL string = "https://app.daytona.io/api"
const DaytonaConfigDefaultUser string = "daytona"
const DaytonaConfigDefaultWorkRoot string = "/home/daytona/crabbox"
const DaytonaConfigDefaultSSHGatewayHost string = "ssh.app.daytona.io"
const DaytonaConfigDefaultSSHAccessMinutes int = 30

func defaultDaytonaConfig() DaytonaConfig {
	return DaytonaConfig{
		APIURL:           DaytonaConfigDefaultAPIURL,
		User:             DaytonaConfigDefaultUser,
		WorkRoot:         DaytonaConfigDefaultWorkRoot,
		SSHGatewayHost:   DaytonaConfigDefaultSSHGatewayHost,
		SSHAccessMinutes: DaytonaConfigDefaultSSHAccessMinutes,
	}
}

// DaytonaConfigApplied records accepted assignments during one application.
type DaytonaConfigApplied struct {
	InputAccepted  bool
	APIKey         bool
	JWTToken       bool
	APIURL         bool
	SSHGatewayHost bool
}

func (cfg *DaytonaConfig) applyFile(file *fileDaytonaConfig) (DaytonaConfigApplied, error) {
	var applied DaytonaConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "daytona")
	return applied, err
}

func (cfg *DaytonaConfig) applyEnv() (DaytonaConfigApplied, error) {
	var applied DaytonaConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 10)
	return applied, err
}

// DaytonaConfigFlagValues holds parsed values; only visited flags are applied.
type DaytonaConfigFlagValues struct {
	APIURL           *string
	Snapshot         *string
	Target           *string
	User             *string
	WorkRoot         *string
	SSHGatewayHost   *string
	SSHAccessMinutes *int
}

// RegisterDaytonaConfigFlags registers mechanical bindings without selecting a provider.
func RegisterDaytonaConfigFlags(fs *flag.FlagSet, defaults DaytonaConfig) DaytonaConfigFlagValues {
	var values DaytonaConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// DaytonaConfigVisitedFlags records raw flag visits, independently of application.
type DaytonaConfigVisitedFlags struct {
	APIURL         bool
	SSHGatewayHost bool
}

// DaytonaConfigFlagPresence reports visits for tracked flag bindings.
func DaytonaConfigFlagPresence(fs *flag.FlagSet) DaytonaConfigVisitedFlags {
	var visited DaytonaConfigVisitedFlags
	recordConfigFlagVisits[DaytonaConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values DaytonaConfigFlagValues) Apply(cfg *DaytonaConfig, fs *flag.FlagSet) (DaytonaConfigApplied, error) {
	var applied DaytonaConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
