// Code generated by scripts/configgen from config_windows_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileWindowsSandboxConfig struct {
	Workdir            string `yaml:"workdir,omitempty"`
	TempRoot           string `yaml:"tempRoot,omitempty"`
	Networking         string `yaml:"networking,omitempty"`
	VGPU               string `yaml:"vgpu,omitempty"`
	Clipboard          string `yaml:"clipboard,omitempty"`
	ProtectedClient    string `yaml:"protectedClient,omitempty"`
	AudioInput         string `yaml:"audioInput,omitempty"`
	VideoInput         string `yaml:"videoInput,omitempty"`
	PrinterRedirection string `yaml:"printerRedirection,omitempty"`
	MemoryMB           int    `yaml:"memoryMB,omitempty"`
}

const WindowsSandboxConfigDefaultWorkdir string = "C:\\crabbox-work"
const WindowsSandboxConfigDefaultNetworking string = "Enable"
const WindowsSandboxConfigDefaultVGPU string = "Disable"
const WindowsSandboxConfigDefaultClipboard string = "Disable"
const WindowsSandboxConfigDefaultProtectedClient string = "Default"
const WindowsSandboxConfigDefaultAudioInput string = "Disable"
const WindowsSandboxConfigDefaultVideoInput string = "Disable"
const WindowsSandboxConfigDefaultPrinterRedirection string = "Disable"

func defaultWindowsSandboxConfig() WindowsSandboxConfig {
	return WindowsSandboxConfig{
		Workdir:            WindowsSandboxConfigDefaultWorkdir,
		Networking:         WindowsSandboxConfigDefaultNetworking,
		VGPU:               WindowsSandboxConfigDefaultVGPU,
		Clipboard:          WindowsSandboxConfigDefaultClipboard,
		ProtectedClient:    WindowsSandboxConfigDefaultProtectedClient,
		AudioInput:         WindowsSandboxConfigDefaultAudioInput,
		VideoInput:         WindowsSandboxConfigDefaultVideoInput,
		PrinterRedirection: WindowsSandboxConfigDefaultPrinterRedirection,
	}
}

// WindowsSandboxConfigApplied records accepted assignments during one application.
type WindowsSandboxConfigApplied struct {
	InputAccepted bool
	TempRoot      bool
}

func (cfg *WindowsSandboxConfig) applyFile(file *fileWindowsSandboxConfig, trusted bool) (WindowsSandboxConfigApplied, error) {
	var applied WindowsSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "windows-sandbox")
	return applied, err
}

func (cfg *WindowsSandboxConfig) applyEnv() (WindowsSandboxConfigApplied, error) {
	var applied WindowsSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 10)
	return applied, err
}

// WindowsSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type WindowsSandboxConfigFlagValues struct {
	Workdir            *string
	TempRoot           *string
	Networking         *string
	VGPU               *string
	Clipboard          *string
	ProtectedClient    *string
	AudioInput         *string
	VideoInput         *string
	PrinterRedirection *string
	MemoryMB           *int
}

// RegisterWindowsSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterWindowsSandboxConfigFlags(fs *flag.FlagSet, defaults WindowsSandboxConfig) WindowsSandboxConfigFlagValues {
	var values WindowsSandboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// WindowsSandboxConfigVisitedFlags records raw flag visits, independently of application.
type WindowsSandboxConfigVisitedFlags struct {
	Workdir            bool
	TempRoot           bool
	Networking         bool
	VGPU               bool
	Clipboard          bool
	ProtectedClient    bool
	AudioInput         bool
	VideoInput         bool
	PrinterRedirection bool
	MemoryMB           bool
}

// WindowsSandboxConfigFlagPresence reports visits for tracked flag bindings.
func WindowsSandboxConfigFlagPresence(fs *flag.FlagSet) WindowsSandboxConfigVisitedFlags {
	var visited WindowsSandboxConfigVisitedFlags
	recordConfigFlagVisits[WindowsSandboxConfig](fs, &visited)
	return visited
}
