// Code generated by scripts/configgen from config_opensandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileOpenSandboxConfig struct {
	Image           *string `yaml:"image,omitempty"`
	Workdir         *string `yaml:"workdir,omitempty"`
	CPU             *string `yaml:"cpu,omitempty"`
	Memory          *string `yaml:"memory,omitempty"`
	TimeoutSecs     *int    `yaml:"timeoutSecs,omitempty"`
	ExecTimeoutSecs *int    `yaml:"execTimeoutSecs,omitempty"`
	PlatformOS      *string `yaml:"platformOS,omitempty"`
	PlatformArch    *string `yaml:"platformArch,omitempty"`
	SecureAccess    *bool   `yaml:"secureAccess,omitempty"`
	UseServerProxy  *bool   `yaml:"useServerProxy,omitempty"`
}

const OpenSandboxConfigDefaultImage string = "ubuntu:24.04"
const OpenSandboxConfigDefaultWorkdir string = "/workspace/crabbox"
const OpenSandboxConfigDefaultCPU string = "1"
const OpenSandboxConfigDefaultMemory string = "2Gi"
const OpenSandboxConfigDefaultExecTimeoutSecs int = 600
const OpenSandboxConfigDefaultPlatformOS string = "linux"
const OpenSandboxConfigDefaultPlatformArch string = "amd64"

func defaultOpenSandboxConfig() OpenSandboxConfig {
	return OpenSandboxConfig{
		Image:           OpenSandboxConfigDefaultImage,
		Workdir:         OpenSandboxConfigDefaultWorkdir,
		CPU:             OpenSandboxConfigDefaultCPU,
		Memory:          OpenSandboxConfigDefaultMemory,
		ExecTimeoutSecs: OpenSandboxConfigDefaultExecTimeoutSecs,
		PlatformOS:      OpenSandboxConfigDefaultPlatformOS,
		PlatformArch:    OpenSandboxConfigDefaultPlatformArch,
	}
}

// OpenSandboxConfigApplied records accepted assignments during one application.
type OpenSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *OpenSandboxConfig) applyFile(file *fileOpenSandboxConfig) (OpenSandboxConfigApplied, error) {
	var applied OpenSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "opensandbox")
	return applied, err
}

func (cfg *OpenSandboxConfig) applyEnv() (OpenSandboxConfigApplied, error) {
	var applied OpenSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 12)
	return applied, err
}

// OpenSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type OpenSandboxConfigFlagValues struct {
	APIURL          *string
	Image           *string
	Workdir         *string
	CPU             *string
	Memory          *string
	TimeoutSecs     *int
	ExecTimeoutSecs *int
	PlatformOS      *string
	PlatformArch    *string
	SecureAccess    *bool
	UseServerProxy  *bool
	ForgetMissing   *bool
}

// RegisterOpenSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterOpenSandboxConfigFlags(fs *flag.FlagSet, defaults OpenSandboxConfig) OpenSandboxConfigFlagValues {
	var values OpenSandboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values OpenSandboxConfigFlagValues) Apply(cfg *OpenSandboxConfig, fs *flag.FlagSet) (OpenSandboxConfigApplied, error) {
	var applied OpenSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
