// Code generated by scripts/configgen from config_digitalocean.go; DO NOT EDIT.

package cli

type fileDigitalOceanConfig struct {
	Region   string   `yaml:"region,omitempty"`
	Image    string   `yaml:"image,omitempty"`
	VPCUUID  string   `yaml:"vpc,omitempty"`
	SSHCIDRs []string `yaml:"sshCIDRs,omitempty"`
}

func defaultDigitalOceanConfig() DigitalOceanConfig {
	return DigitalOceanConfig{}
}

// DigitalOceanConfigApplied records accepted assignments during one application.
type DigitalOceanConfigApplied struct {
	InputAccepted bool
	Image         bool
}

func (cfg *DigitalOceanConfig) applyFile(file *fileDigitalOceanConfig) (DigitalOceanConfigApplied, error) {
	var applied DigitalOceanConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "digitalocean")
	return applied, err
}

func (cfg *DigitalOceanConfig) applyEnv() (DigitalOceanConfigApplied, error) {
	var applied DigitalOceanConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 4)
	return applied, err
}
