// Code generated by scripts/configgen from config_tensorlake.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileTensorlakeConfig struct {
	APIURL         string  `yaml:"apiUrl,omitempty"`
	CLIPath        string  `yaml:"cliPath,omitempty"`
	Image          string  `yaml:"image,omitempty"`
	Snapshot       string  `yaml:"snapshot,omitempty"`
	OrganizationID string  `yaml:"organizationId,omitempty"`
	ProjectID      string  `yaml:"projectId,omitempty"`
	Namespace      string  `yaml:"namespace,omitempty"`
	Workdir        string  `yaml:"workdir,omitempty"`
	CPUs           float64 `yaml:"cpus,omitempty"`
	MemoryMB       int     `yaml:"memoryMB,omitempty"`
	DiskMB         int     `yaml:"diskMB,omitempty"`
	TimeoutSecs    int     `yaml:"timeoutSecs,omitempty"`
	NoInternet     *bool   `yaml:"noInternet,omitempty"`
}

const TensorlakeConfigDefaultAPIURL string = "https://api.tensorlake.ai"
const TensorlakeConfigDefaultCLIPath string = "tensorlake"
const TensorlakeConfigDefaultWorkdir string = "/workspace/crabbox"
const TensorlakeConfigDefaultCPUs float64 = 1
const TensorlakeConfigDefaultMemoryMB int = 1024
const TensorlakeConfigDefaultDiskMB int = 10240

func defaultTensorlakeConfig() TensorlakeConfig {
	return TensorlakeConfig{
		APIURL:   TensorlakeConfigDefaultAPIURL,
		CLIPath:  TensorlakeConfigDefaultCLIPath,
		Workdir:  TensorlakeConfigDefaultWorkdir,
		CPUs:     TensorlakeConfigDefaultCPUs,
		MemoryMB: TensorlakeConfigDefaultMemoryMB,
		DiskMB:   TensorlakeConfigDefaultDiskMB,
	}
}

// TensorlakeConfigApplied records accepted assignments during one application.
type TensorlakeConfigApplied struct {
	APIKey bool
	APIURL bool
}

func (cfg *TensorlakeConfig) applyFile(file *fileTensorlakeConfig) (TensorlakeConfigApplied, error) {
	var applied TensorlakeConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.APIURL != "" {
		cfg.APIURL = file.APIURL
		applied.APIURL = true
	}
	if file.CLIPath != "" {
		cfg.CLIPath = file.CLIPath
	}
	if file.Image != "" {
		cfg.Image = file.Image
	}
	if file.Snapshot != "" {
		cfg.Snapshot = file.Snapshot
	}
	if file.OrganizationID != "" {
		cfg.OrganizationID = file.OrganizationID
	}
	if file.ProjectID != "" {
		cfg.ProjectID = file.ProjectID
	}
	if file.Namespace != "" {
		cfg.Namespace = file.Namespace
	}
	if file.Workdir != "" {
		cfg.Workdir = file.Workdir
	}
	if file.CPUs > 0 {
		cfg.CPUs = file.CPUs
	}
	if file.MemoryMB > 0 {
		cfg.MemoryMB = file.MemoryMB
	}
	if file.DiskMB > 0 {
		cfg.DiskMB = file.DiskMB
	}
	if file.TimeoutSecs > 0 {
		cfg.TimeoutSecs = file.TimeoutSecs
	}
	if file.NoInternet != nil {
		cfg.NoInternet = *file.NoInternet
	}
	return applied, nil
}

func (cfg *TensorlakeConfig) applyEnv() (TensorlakeConfigApplied, error) {
	var applied TensorlakeConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_TENSORLAKE_API_KEY", "TENSORLAKE_API_KEY"); ok {
		cfg.APIKey = value
		applied.APIKey = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_TENSORLAKE_API_URL", "TENSORLAKE_API_URL"); ok {
		cfg.APIURL = value
		applied.APIURL = true
	}
	cfg.CLIPath = getenv("CRABBOX_TENSORLAKE_CLI", cfg.CLIPath)
	cfg.Image = getenv("CRABBOX_TENSORLAKE_IMAGE", cfg.Image)
	cfg.Snapshot = getenv("CRABBOX_TENSORLAKE_SNAPSHOT", cfg.Snapshot)
	cfg.OrganizationID = getenv("CRABBOX_TENSORLAKE_ORGANIZATION_ID", getenv("TENSORLAKE_ORGANIZATION_ID", cfg.OrganizationID))
	cfg.ProjectID = getenv("CRABBOX_TENSORLAKE_PROJECT_ID", getenv("TENSORLAKE_PROJECT_ID", cfg.ProjectID))
	cfg.Namespace = getenv("CRABBOX_TENSORLAKE_NAMESPACE", getenv("INDEXIFY_NAMESPACE", cfg.Namespace))
	cfg.Workdir = getenv("CRABBOX_TENSORLAKE_WORKDIR", cfg.Workdir)
	cfg.CPUs = getenvFloat("CRABBOX_TENSORLAKE_CPUS", cfg.CPUs)
	cfg.MemoryMB = getenvInt("CRABBOX_TENSORLAKE_MEMORY_MB", cfg.MemoryMB)
	cfg.DiskMB = getenvInt("CRABBOX_TENSORLAKE_DISK_MB", cfg.DiskMB)
	cfg.TimeoutSecs = getenvInt("CRABBOX_TENSORLAKE_TIMEOUT_SECS", cfg.TimeoutSecs)
	if value, ok := getenvBool("CRABBOX_TENSORLAKE_NO_INTERNET"); ok {
		cfg.NoInternet = value
	}
	return applied, nil
}

// TensorlakeConfigFlagValues holds parsed values; only visited flags are applied.
type TensorlakeConfigFlagValues struct {
	APIURL         *string
	CLIPath        *string
	Image          *string
	Snapshot       *string
	OrganizationID *string
	ProjectID      *string
	Namespace      *string
	Workdir        *string
	CPUs           *float64
	MemoryMB       *int
	DiskMB         *int
	TimeoutSecs    *int
	NoInternet     *bool
}

// RegisterTensorlakeConfigFlags registers mechanical bindings without selecting a provider.
func RegisterTensorlakeConfigFlags(fs *flag.FlagSet, defaults TensorlakeConfig) TensorlakeConfigFlagValues {
	return TensorlakeConfigFlagValues{
		APIURL:         fs.String("tensorlake-api-url", defaults.APIURL, "Tensorlake API base URL"),
		CLIPath:        fs.String("tensorlake-cli", defaults.CLIPath, "Path to the tensorlake CLI binary"),
		Image:          fs.String("tensorlake-image", defaults.Image, "Tensorlake sandbox image name"),
		Snapshot:       fs.String("tensorlake-snapshot", defaults.Snapshot, "Tensorlake snapshot ID to restore from"),
		OrganizationID: fs.String("tensorlake-organization-id", defaults.OrganizationID, "Tensorlake organization ID"),
		ProjectID:      fs.String("tensorlake-project-id", defaults.ProjectID, "Tensorlake project ID"),
		Namespace:      fs.String("tensorlake-namespace", defaults.Namespace, "Tensorlake namespace"),
		Workdir:        fs.String("tensorlake-workdir", defaults.Workdir, "Absolute working directory inside the sandbox (also used as sync target)"),
		CPUs:           fs.Float64("tensorlake-cpus", defaults.CPUs, "Tensorlake sandbox CPU count"),
		MemoryMB:       fs.Int("tensorlake-memory-mb", defaults.MemoryMB, "Tensorlake sandbox memory in MB"),
		DiskMB:         fs.Int("tensorlake-disk-mb", defaults.DiskMB, "Tensorlake sandbox root disk in MB"),
		TimeoutSecs:    fs.Int("tensorlake-timeout-secs", defaults.TimeoutSecs, "Tensorlake sandbox lifetime timeout in seconds"),
		NoInternet:     fs.Bool("tensorlake-no-internet", defaults.NoInternet, "Block outbound internet from the sandbox"),
	}
}

// TensorlakeConfigVisitedFlags records raw flag visits, independently of application.
type TensorlakeConfigVisitedFlags struct {
	APIURL bool
}

// TensorlakeConfigFlagPresence reports visits for tracked flag bindings.
func TensorlakeConfigFlagPresence(fs *flag.FlagSet) TensorlakeConfigVisitedFlags {
	return TensorlakeConfigVisitedFlags{
		APIURL: flagWasSet(fs, "tensorlake-api-url"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values TensorlakeConfigFlagValues) Apply(cfg *TensorlakeConfig, fs *flag.FlagSet) TensorlakeConfigApplied {
	var applied TensorlakeConfigApplied
	visited := TensorlakeConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.APIURL = true
	}
	if flagWasSet(fs, "tensorlake-cli") {
		cfg.CLIPath = *values.CLIPath
	}
	if flagWasSet(fs, "tensorlake-image") {
		cfg.Image = *values.Image
	}
	if flagWasSet(fs, "tensorlake-snapshot") {
		cfg.Snapshot = *values.Snapshot
	}
	if flagWasSet(fs, "tensorlake-organization-id") {
		cfg.OrganizationID = *values.OrganizationID
	}
	if flagWasSet(fs, "tensorlake-project-id") {
		cfg.ProjectID = *values.ProjectID
	}
	if flagWasSet(fs, "tensorlake-namespace") {
		cfg.Namespace = *values.Namespace
	}
	if flagWasSet(fs, "tensorlake-workdir") {
		cfg.Workdir = *values.Workdir
	}
	if flagWasSet(fs, "tensorlake-cpus") {
		cfg.CPUs = *values.CPUs
	}
	if flagWasSet(fs, "tensorlake-memory-mb") {
		cfg.MemoryMB = *values.MemoryMB
	}
	if flagWasSet(fs, "tensorlake-disk-mb") {
		cfg.DiskMB = *values.DiskMB
	}
	if flagWasSet(fs, "tensorlake-timeout-secs") {
		cfg.TimeoutSecs = *values.TimeoutSecs
	}
	if flagWasSet(fs, "tensorlake-no-internet") {
		cfg.NoInternet = *values.NoInternet
	}
	return applied
}
