// Code generated by scripts/configgen from config_vast.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileVastConfig struct {
	APIURL         string   `yaml:"apiUrl,omitempty"`
	InstanceType   string   `yaml:"instanceType,omitempty"`
	GPUName        string   `yaml:"gpuName,omitempty"`
	GPUCount       int      `yaml:"gpuCount,omitempty"`
	Image          string   `yaml:"image,omitempty"`
	TemplateID     string   `yaml:"templateId,omitempty"`
	Runtype        string   `yaml:"runtype,omitempty"`
	DiskGB         int      `yaml:"diskGB,omitempty"`
	MaxDphTotal    *float64 `yaml:"maxDphTotal,omitempty"`
	MinReliability *float64 `yaml:"minReliability,omitempty"`
	Order          string   `yaml:"order,omitempty"`
	User           string   `yaml:"user,omitempty"`
	WorkRoot       string   `yaml:"workRoot,omitempty"`
	ReleaseAction  string   `yaml:"releaseAction,omitempty"`
}

const VastConfigDefaultAPIURL string = "https://console.vast.ai/api/v0"
const VastConfigDefaultInstanceType string = "ondemand"
const VastConfigDefaultImage string = "nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04"
const VastConfigDefaultRuntype string = "ssh_direct"
const VastConfigDefaultDiskGB int = 20
const VastConfigDefaultOrder string = "dlperf_per_dphtotal desc"
const VastConfigDefaultUser string = "root"
const VastConfigDefaultWorkRoot string = "/work/crabbox"
const VastConfigDefaultReleaseAction string = "destroy"

func defaultVastConfig() VastConfig {
	return VastConfig{
		APIURL:        VastConfigDefaultAPIURL,
		InstanceType:  VastConfigDefaultInstanceType,
		Image:         VastConfigDefaultImage,
		Runtype:       VastConfigDefaultRuntype,
		DiskGB:        VastConfigDefaultDiskGB,
		Order:         VastConfigDefaultOrder,
		User:          VastConfigDefaultUser,
		WorkRoot:      VastConfigDefaultWorkRoot,
		ReleaseAction: VastConfigDefaultReleaseAction,
	}
}

// VastConfigApplied records accepted assignments during one application.
type VastConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	APIURL        bool
	InstanceType  bool
	WorkRoot      bool
	ReleaseAction bool
}

func (cfg *VastConfig) applyFile(file *fileVastConfig) (VastConfigApplied, error) {
	var applied VastConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "vast")
	return applied, err
}

func (cfg *VastConfig) applyEnv() (VastConfigApplied, error) {
	var applied VastConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 15)
	return applied, err
}

// VastConfigFlagValues holds parsed values; only visited flags are applied.
type VastConfigFlagValues struct {
	APIURL         *string
	InstanceType   *string
	GPUName        *string
	GPUCount       *int
	Image          *string
	TemplateID     *string
	Runtype        *string
	DiskGB         *int
	MaxDphTotal    *float64
	MinReliability *float64
	Order          *string
	User           *string
	WorkRoot       *string
	ReleaseAction  *string
}

// RegisterVastConfigFlags registers mechanical bindings without selecting a provider.
func RegisterVastConfigFlags(fs *flag.FlagSet, defaults VastConfig) VastConfigFlagValues {
	var values VastConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// VastConfigVisitedFlags records raw flag visits, independently of application.
type VastConfigVisitedFlags struct {
	APIURL        bool
	InstanceType  bool
	WorkRoot      bool
	ReleaseAction bool
}

// VastConfigFlagPresence reports visits for tracked flag bindings.
func VastConfigFlagPresence(fs *flag.FlagSet) VastConfigVisitedFlags {
	var visited VastConfigVisitedFlags
	recordConfigFlagVisits[VastConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values VastConfigFlagValues) Apply(cfg *VastConfig, fs *flag.FlagSet) (VastConfigApplied, error) {
	var applied VastConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
