// Code generated by scripts/configgen from config_e2b.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileE2BConfig struct {
	APIURL   string `yaml:"apiUrl,omitempty"`
	Domain   string `yaml:"domain,omitempty"`
	Template string `yaml:"template,omitempty"`
	Workdir  string `yaml:"workdir,omitempty"`
	User     string `yaml:"user,omitempty"`
}

const E2BConfigDefaultAPIURL string = "https://api.e2b.app"
const E2BConfigDefaultDomain string = "e2b.app"
const E2BConfigDefaultTemplate string = "base"
const E2BConfigDefaultWorkdir string = "crabbox"

func defaultE2BConfig() E2BConfig {
	return E2BConfig{
		APIURL:   E2BConfigDefaultAPIURL,
		Domain:   E2BConfigDefaultDomain,
		Template: E2BConfigDefaultTemplate,
		Workdir:  E2BConfigDefaultWorkdir,
	}
}

// E2BConfigApplied records accepted assignments during one application.
type E2BConfigApplied struct {
	APIKey bool
	APIURL bool
	Domain bool
}

func (cfg *E2BConfig) applyFile(file *fileE2BConfig) (E2BConfigApplied, error) {
	var applied E2BConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.APIURL != "" {
		cfg.APIURL = file.APIURL
		applied.APIURL = true
	}
	if file.Domain != "" {
		cfg.Domain = file.Domain
		applied.Domain = true
	}
	if file.Template != "" {
		cfg.Template = file.Template
	}
	if file.Workdir != "" {
		cfg.Workdir = file.Workdir
	}
	if file.User != "" {
		cfg.User = file.User
	}
	return applied, nil
}

func (cfg *E2BConfig) applyEnv() (E2BConfigApplied, error) {
	var applied E2BConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_E2B_API_KEY", "E2B_API_KEY"); ok {
		cfg.APIKey = value
		applied.APIKey = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_E2B_API_URL", "E2B_API_URL"); ok {
		cfg.APIURL = value
		applied.APIURL = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_E2B_DOMAIN", "E2B_DOMAIN"); ok {
		cfg.Domain = value
		applied.Domain = true
	}
	cfg.Template = getenv("CRABBOX_E2B_TEMPLATE", cfg.Template)
	cfg.Workdir = getenv("CRABBOX_E2B_WORKDIR", cfg.Workdir)
	cfg.User = getenv("CRABBOX_E2B_USER", cfg.User)
	return applied, nil
}

// E2BConfigFlagValues holds parsed values; only visited flags are applied.
type E2BConfigFlagValues struct {
	APIURL   *string
	Domain   *string
	Template *string
	Workdir  *string
	User     *string
}

// RegisterE2BConfigFlags registers mechanical bindings without selecting a provider.
func RegisterE2BConfigFlags(fs *flag.FlagSet, defaults E2BConfig) E2BConfigFlagValues {
	return E2BConfigFlagValues{
		APIURL:   fs.String("e2b-api-url", defaults.APIURL, "E2B API URL"),
		Domain:   fs.String("e2b-domain", defaults.Domain, "E2B sandbox domain"),
		Template: fs.String("e2b-template", defaults.Template, "E2B sandbox template ID"),
		Workdir:  fs.String("e2b-workdir", defaults.Workdir, "E2B sandbox working directory"),
		User:     fs.String("e2b-user", defaults.User, "E2B sandbox user for command and file ownership"),
	}
}

// E2BConfigVisitedFlags records raw flag visits, independently of application.
type E2BConfigVisitedFlags struct {
	APIURL bool
	Domain bool
}

// E2BConfigFlagPresence reports visits for tracked flag bindings.
func E2BConfigFlagPresence(fs *flag.FlagSet) E2BConfigVisitedFlags {
	return E2BConfigVisitedFlags{
		APIURL: flagWasSet(fs, "e2b-api-url"),
		Domain: flagWasSet(fs, "e2b-domain"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values E2BConfigFlagValues) Apply(cfg *E2BConfig, fs *flag.FlagSet) E2BConfigApplied {
	var applied E2BConfigApplied
	visited := E2BConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.APIURL = true
	}
	if visited.Domain {
		cfg.Domain = *values.Domain
		applied.Domain = true
	}
	if flagWasSet(fs, "e2b-template") {
		cfg.Template = *values.Template
	}
	if flagWasSet(fs, "e2b-workdir") {
		cfg.Workdir = *values.Workdir
	}
	if flagWasSet(fs, "e2b-user") {
		cfg.User = *values.User
	}
	return applied
}
