// Code generated by scripts/configgen from config_superserve.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileSuperserveConfig struct {
	BaseURL         string   `yaml:"baseUrl,omitempty"`
	Template        *string  `yaml:"template,omitempty"`
	Snapshot        *string  `yaml:"snapshot,omitempty"`
	Workdir         *string  `yaml:"workdir,omitempty"`
	TimeoutSecs     *int     `yaml:"timeoutSecs,omitempty"`
	ExecTimeoutSecs *int     `yaml:"execTimeoutSecs,omitempty"`
	NetworkAllowOut []string `yaml:"networkAllowOut,omitempty"`
	NetworkDenyOut  []string `yaml:"networkDenyOut,omitempty"`
	ForgetMissing   *bool    `yaml:"forgetMissing,omitempty"`
}

const SuperserveConfigDefaultBaseURL string = "https://api.superserve.ai"
const SuperserveConfigDefaultTemplate string = "superserve/base"
const SuperserveConfigDefaultWorkdir string = "/workspace/crabbox"
const SuperserveConfigDefaultExecTimeoutSecs int = 600

func defaultSuperserveConfig() SuperserveConfig {
	return SuperserveConfig{
		BaseURL:         SuperserveConfigDefaultBaseURL,
		Template:        SuperserveConfigDefaultTemplate,
		Workdir:         SuperserveConfigDefaultWorkdir,
		ExecTimeoutSecs: SuperserveConfigDefaultExecTimeoutSecs,
	}
}

// SuperserveConfigApplied records accepted assignments during one application.
type SuperserveConfigApplied struct {
	InputAccepted bool
}

func (cfg *SuperserveConfig) applyFile(file *fileSuperserveConfig, trusted bool) (SuperserveConfigApplied, error) {
	var applied SuperserveConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "superserve")
	return applied, err
}

func (cfg *SuperserveConfig) applyEnv() (SuperserveConfigApplied, error) {
	var applied SuperserveConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 9)
	return applied, err
}

// SuperserveConfigFlagValues holds parsed values; only visited flags are applied.
type SuperserveConfigFlagValues struct {
	BaseURL         *string
	Template        *string
	Snapshot        *string
	Workdir         *string
	TimeoutSecs     *int
	ExecTimeoutSecs *int
	NetworkAllowOut *string
	NetworkDenyOut  *string
	ForgetMissing   *bool
}

// RegisterSuperserveConfigFlags registers mechanical bindings without selecting a provider.
func RegisterSuperserveConfigFlags(fs *flag.FlagSet, defaults SuperserveConfig) SuperserveConfigFlagValues {
	var values SuperserveConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values SuperserveConfigFlagValues) Apply(cfg *SuperserveConfig, fs *flag.FlagSet) (SuperserveConfigApplied, error) {
	var applied SuperserveConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
