// Code generated by scripts/configgen from config_fastapi_cloud.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileFastAPICloudConfig struct {
	APIURL string `yaml:"apiUrl,omitempty"`
	AppID  string `yaml:"appId,omitempty"`
	TeamID string `yaml:"teamId,omitempty"`
}

const FastAPICloudConfigDefaultAPIURL string = "https://api.fastapicloud.com/api/v1"

func defaultFastAPICloudConfig() FastAPICloudConfig {
	return FastAPICloudConfig{
		APIURL: FastAPICloudConfigDefaultAPIURL,
	}
}

// FastAPICloudConfigApplied records accepted assignments during one application.
type FastAPICloudConfigApplied struct {
	Token  bool
	APIURL bool
}

func (cfg *FastAPICloudConfig) applyFile(file *fileFastAPICloudConfig) (FastAPICloudConfigApplied, error) {
	var applied FastAPICloudConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.APIURL != "" {
		cfg.APIURL = file.APIURL
		applied.APIURL = true
	}
	if file.AppID != "" {
		cfg.AppID = file.AppID
	}
	if file.TeamID != "" {
		cfg.TeamID = file.TeamID
	}
	return applied, nil
}

func (cfg *FastAPICloudConfig) applyEnv() (FastAPICloudConfigApplied, error) {
	var applied FastAPICloudConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_FASTAPI_CLOUD_TOKEN", "FASTAPI_CLOUD_TOKEN"); ok {
		cfg.Token = value
		applied.Token = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_FASTAPI_CLOUD_API_URL", "FASTAPI_CLOUD_API_URL"); ok {
		cfg.APIURL = value
		applied.APIURL = true
	}
	cfg.AppID = getenv("CRABBOX_FASTAPI_CLOUD_APP_ID", getenv("FASTAPI_CLOUD_APP_ID", cfg.AppID))
	cfg.TeamID = getenv("CRABBOX_FASTAPI_CLOUD_TEAM_ID", getenv("FASTAPI_CLOUD_TEAM_ID", cfg.TeamID))
	return applied, nil
}

// FastAPICloudConfigFlagValues holds parsed values; only visited flags are applied.
type FastAPICloudConfigFlagValues struct {
	APIURL *string
	AppID  *string
	TeamID *string
}

// RegisterFastAPICloudConfigFlags registers mechanical bindings without selecting a provider.
func RegisterFastAPICloudConfigFlags(fs *flag.FlagSet, defaults FastAPICloudConfig) FastAPICloudConfigFlagValues {
	return FastAPICloudConfigFlagValues{
		APIURL: fs.String("fastapi-cloud-url", defaults.APIURL, "FastAPI Cloud API URL"),
		AppID:  fs.String("fastapi-cloud-app-id", defaults.AppID, "FastAPI Cloud app ID"),
		TeamID: fs.String("fastapi-cloud-team-id", defaults.TeamID, "FastAPI Cloud team ID for listing apps"),
	}
}

// FastAPICloudConfigVisitedFlags records raw flag visits, independently of application.
type FastAPICloudConfigVisitedFlags struct {
	APIURL bool
}

// FastAPICloudConfigFlagPresence reports visits for tracked flag bindings.
func FastAPICloudConfigFlagPresence(fs *flag.FlagSet) FastAPICloudConfigVisitedFlags {
	return FastAPICloudConfigVisitedFlags{
		APIURL: flagWasSet(fs, "fastapi-cloud-url"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values FastAPICloudConfigFlagValues) Apply(cfg *FastAPICloudConfig, fs *flag.FlagSet) FastAPICloudConfigApplied {
	var applied FastAPICloudConfigApplied
	visited := FastAPICloudConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.APIURL = true
	}
	if flagWasSet(fs, "fastapi-cloud-app-id") {
		cfg.AppID = *values.AppID
	}
	if flagWasSet(fs, "fastapi-cloud-team-id") {
		cfg.TeamID = *values.TeamID
	}
	return applied
}
