// Code generated by scripts/configgen from config_namespace_instance.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileNamespaceInstanceConfig struct {
	CLIPath     string   `yaml:"cli,omitempty"`
	MachineType string   `yaml:"machineType,omitempty"`
	Duration    string   `yaml:"duration,omitempty"`
	Region      string   `yaml:"region,omitempty"`
	Endpoint    string   `yaml:"endpoint,omitempty"`
	Keychain    string   `yaml:"keychain,omitempty"`
	Volumes     []string `yaml:"volumes,omitempty"`
	WorkRoot    string   `yaml:"workRoot,omitempty"`
	Bare        *bool    `yaml:"bare,omitempty"`
}

const NamespaceInstanceConfigDefaultCLIPath string = "nsc"
const NamespaceInstanceConfigDefaultWorkRoot string = "/work/crabbox"
const NamespaceInstanceConfigDefaultBare bool = true

func defaultNamespaceInstanceConfig() NamespaceInstanceConfig {
	return NamespaceInstanceConfig{
		CLIPath:  NamespaceInstanceConfigDefaultCLIPath,
		WorkRoot: NamespaceInstanceConfigDefaultWorkRoot,
		Bare:     NamespaceInstanceConfigDefaultBare,
	}
}

// NamespaceInstanceConfigApplied records accepted assignments during one application.
type NamespaceInstanceConfigApplied struct {
	InputAccepted bool
	CLIPath       bool
}

func (cfg *NamespaceInstanceConfig) applyFile(file *fileNamespaceInstanceConfig, trusted bool) (NamespaceInstanceConfigApplied, error) {
	var applied NamespaceInstanceConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "namespaceInstance")
	return applied, err
}

func (cfg *NamespaceInstanceConfig) applyEnv() (NamespaceInstanceConfigApplied, error) {
	var applied NamespaceInstanceConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 9)
	return applied, err
}

// NamespaceInstanceConfigFlagValues holds parsed values; only visited flags are applied.
type NamespaceInstanceConfigFlagValues struct {
	CLIPath     *string
	MachineType *string
	Duration    *string
	Region      *string
	Endpoint    *string
	Keychain    *string
	Volumes     *appendTrimmedListFlag
	WorkRoot    *string
	Bare        *bool
}

// RegisterNamespaceInstanceConfigFlags registers mechanical bindings without selecting a provider.
func RegisterNamespaceInstanceConfigFlags(fs *flag.FlagSet, defaults NamespaceInstanceConfig) NamespaceInstanceConfigFlagValues {
	var values NamespaceInstanceConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// NamespaceInstanceConfigVisitedFlags records raw flag visits, independently of application.
type NamespaceInstanceConfigVisitedFlags struct {
	CLIPath bool
}

// NamespaceInstanceConfigFlagPresence reports visits for tracked flag bindings.
func NamespaceInstanceConfigFlagPresence(fs *flag.FlagSet) NamespaceInstanceConfigVisitedFlags {
	var visited NamespaceInstanceConfigVisitedFlags
	recordConfigFlagVisits[NamespaceInstanceConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values NamespaceInstanceConfigFlagValues) Apply(cfg *NamespaceInstanceConfig, fs *flag.FlagSet) (NamespaceInstanceConfigApplied, error) {
	var applied NamespaceInstanceConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
