// Code generated by scripts/configgen from config_scaleway.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileScalewayConfig struct {
	Region         string   `yaml:"region,omitempty"`
	Zone           string   `yaml:"zone,omitempty"`
	Image          string   `yaml:"image,omitempty"`
	Type           string   `yaml:"type,omitempty"`
	ProjectID      string   `yaml:"projectId,omitempty"`
	OrganizationID string   `yaml:"organizationId,omitempty"`
	SecurityGroup  string   `yaml:"securityGroup,omitempty"`
	SSHCIDRs       []string `yaml:"sshCIDRs,omitempty"`
}

const ScalewayConfigDefaultRegion string = "fr-par"
const ScalewayConfigDefaultZone string = "fr-par-1"
const ScalewayConfigDefaultImage string = "ubuntu_noble"
const ScalewayConfigDefaultType string = "DEV1-S"

func defaultScalewayConfig() ScalewayConfig {
	return ScalewayConfig{
		Region: ScalewayConfigDefaultRegion,
		Zone:   ScalewayConfigDefaultZone,
		Image:  ScalewayConfigDefaultImage,
		Type:   ScalewayConfigDefaultType,
	}
}

// ScalewayConfigApplied records accepted assignments during one application.
type ScalewayConfigApplied struct {
	InputAccepted bool
	Region        bool
	Zone          bool
	Image         bool
	Type          bool
}

func (cfg *ScalewayConfig) applyFile(file *fileScalewayConfig) (ScalewayConfigApplied, error) {
	var applied ScalewayConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "scaleway")
	return applied, err
}

func (cfg *ScalewayConfig) applyEnv() (ScalewayConfigApplied, error) {
	var applied ScalewayConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 8)
	return applied, err
}

// ScalewayConfigFlagValues holds parsed values; only visited flags are applied.
type ScalewayConfigFlagValues struct {
	Region         *string
	Zone           *string
	Image          *string
	Type           *string
	ProjectID      *string
	OrganizationID *string
	SecurityGroup  *string
	SSHCIDRs       *string
}

// RegisterScalewayConfigFlags registers mechanical bindings without selecting a provider.
func RegisterScalewayConfigFlags(fs *flag.FlagSet, defaults ScalewayConfig) ScalewayConfigFlagValues {
	var values ScalewayConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// ScalewayConfigVisitedFlags records raw flag visits, independently of application.
type ScalewayConfigVisitedFlags struct {
	Region bool
	Zone   bool
	Image  bool
	Type   bool
}

// ScalewayConfigFlagPresence reports visits for tracked flag bindings.
func ScalewayConfigFlagPresence(fs *flag.FlagSet) ScalewayConfigVisitedFlags {
	var visited ScalewayConfigVisitedFlags
	recordConfigFlagVisits[ScalewayConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values ScalewayConfigFlagValues) Apply(cfg *ScalewayConfig, fs *flag.FlagSet) (ScalewayConfigApplied, error) {
	var applied ScalewayConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
