// Code generated by scripts/configgen from config_anthropic_sandbox_runtime.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileAnthropicSRTConfig struct {
	CLIPath  string  `yaml:"cliPath,omitempty"`
	Settings *string `yaml:"settings,omitempty"`
	Debug    *bool   `yaml:"debug,omitempty"`
}

const AnthropicSRTConfigDefaultCLIPath string = "srt"

func defaultAnthropicSRTConfig() AnthropicSRTConfig {
	return AnthropicSRTConfig{
		CLIPath: AnthropicSRTConfigDefaultCLIPath,
	}
}

func (cfg *AnthropicSRTConfig) applyFile(file *fileAnthropicSRTConfig) error {
	if file == nil {
		return nil
	}
	if file.CLIPath != "" {
		cfg.CLIPath = file.CLIPath
	}
	if file.Settings != nil {
		cfg.Settings = *file.Settings
	}
	if file.Debug != nil {
		cfg.Debug = *file.Debug
	}
	return nil
}

func (cfg *AnthropicSRTConfig) applyEnv() error {
	cfg.CLIPath = getenv("CRABBOX_ANTHROPIC_SANDBOX_RUNTIME_CLI", cfg.CLIPath)
	cfg.Settings = getenv("CRABBOX_ANTHROPIC_SANDBOX_RUNTIME_SETTINGS", cfg.Settings)
	if value, ok := getenvBool("CRABBOX_ANTHROPIC_SANDBOX_RUNTIME_DEBUG"); ok {
		cfg.Debug = value
	}
	return nil
}

// AnthropicSRTConfigFlagValues holds parsed values; only visited flags are applied.
type AnthropicSRTConfigFlagValues struct {
	CLIPath  *string
	Settings *string
	Debug    *bool
}

// RegisterAnthropicSRTConfigFlags registers mechanical bindings without selecting a provider.
func RegisterAnthropicSRTConfigFlags(fs *flag.FlagSet, defaults AnthropicSRTConfig) AnthropicSRTConfigFlagValues {
	return AnthropicSRTConfigFlagValues{
		CLIPath:  fs.String("anthropic-sandbox-runtime-cli", defaults.CLIPath, "path to the srt CLI binary"),
		Settings: fs.String("anthropic-sandbox-runtime-settings", defaults.Settings, "path to an Anthropic Sandbox Runtime settings JSON file; empty uses srt defaults"),
		Debug:    fs.Bool("anthropic-sandbox-runtime-debug", defaults.Debug, "pass --debug to the srt CLI"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values AnthropicSRTConfigFlagValues) Apply(cfg *AnthropicSRTConfig, fs *flag.FlagSet) {
	if flagWasSet(fs, "anthropic-sandbox-runtime-cli") {
		cfg.CLIPath = *values.CLIPath
	}
	if flagWasSet(fs, "anthropic-sandbox-runtime-settings") {
		cfg.Settings = *values.Settings
	}
	if flagWasSet(fs, "anthropic-sandbox-runtime-debug") {
		cfg.Debug = *values.Debug
	}
}
