// Code generated by scripts/configgen from config_orgo.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileOrgoConfig struct {
	APIKey      string `yaml:"apiKey,omitempty"`
	APIBase     string `yaml:"apiBase,omitempty"`
	WorkspaceID string `yaml:"workspaceID,omitempty"`
	RAMGB       int    `yaml:"ramGB,omitempty"`
	CPUs        int    `yaml:"cpus,omitempty"`
	DiskGB      int    `yaml:"diskGB,omitempty"`
	Resolution  string `yaml:"resolution,omitempty"`
}

const OrgoConfigDefaultAPIBase string = "https://www.orgo.ai/api"
const OrgoConfigDefaultRAMGB int = 4
const OrgoConfigDefaultCPUs int = 1
const OrgoConfigDefaultDiskGB int = 8
const OrgoConfigDefaultResolution string = "1280x720x24"

func defaultOrgoConfig() OrgoConfig {
	return OrgoConfig{
		APIBase:    OrgoConfigDefaultAPIBase,
		RAMGB:      OrgoConfigDefaultRAMGB,
		CPUs:       OrgoConfigDefaultCPUs,
		DiskGB:     OrgoConfigDefaultDiskGB,
		Resolution: OrgoConfigDefaultResolution,
	}
}

// OrgoConfigApplied records accepted assignments during one application.
type OrgoConfigApplied struct {
	APIKey  bool
	APIBase bool
}

func (cfg *OrgoConfig) applyFile(file *fileOrgoConfig, trusted bool) (OrgoConfigApplied, error) {
	var applied OrgoConfigApplied
	if file == nil {
		return applied, nil
	}
	if trusted && file.APIKey != "" {
		cfg.APIKey = file.APIKey
		applied.APIKey = true
	}
	if file.APIBase != "" {
		cfg.APIBase = file.APIBase
		applied.APIBase = true
	}
	if file.WorkspaceID != "" {
		cfg.WorkspaceID = file.WorkspaceID
	}
	if file.RAMGB > 0 {
		cfg.RAMGB = file.RAMGB
	}
	if file.CPUs > 0 {
		cfg.CPUs = file.CPUs
	}
	if file.DiskGB > 0 {
		cfg.DiskGB = file.DiskGB
	}
	if file.Resolution != "" {
		cfg.Resolution = file.Resolution
	}
	return applied, nil
}

func (cfg *OrgoConfig) applyEnv() (OrgoConfigApplied, error) {
	var applied OrgoConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_ORGO_API_KEY"); ok {
		cfg.APIKey = value
		applied.APIKey = true
	} else if cfg.APIKey == "" {
		if value, ok := firstNonEmptyEnv("ORGO_API_KEY"); ok {
			cfg.APIKey = value
			applied.APIKey = true
		}
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_ORGO_API_BASE", "ORGO_API_BASE_URL"); ok {
		cfg.APIBase = value
		applied.APIBase = true
	}
	cfg.WorkspaceID = getenv("CRABBOX_ORGO_WORKSPACE_ID", getenv("ORGO_WORKSPACE_ID", cfg.WorkspaceID))
	cfg.RAMGB = getenvInt("CRABBOX_ORGO_RAM_GB", cfg.RAMGB)
	cfg.CPUs = getenvInt("CRABBOX_ORGO_CPUS", cfg.CPUs)
	cfg.DiskGB = getenvInt("CRABBOX_ORGO_DISK_GB", cfg.DiskGB)
	cfg.Resolution = getenv("CRABBOX_ORGO_RESOLUTION", cfg.Resolution)
	return applied, nil
}

// OrgoConfigFlagValues holds parsed values; only visited flags are applied.
type OrgoConfigFlagValues struct {
	APIBase     *string
	WorkspaceID *string
	RAMGB       *int
	CPUs        *int
	DiskGB      *int
	Resolution  *string
}

// RegisterOrgoConfigFlags registers mechanical bindings without selecting a provider.
func RegisterOrgoConfigFlags(fs *flag.FlagSet, defaults OrgoConfig) OrgoConfigFlagValues {
	return OrgoConfigFlagValues{
		APIBase:     fs.String("orgo-api-base", defaults.APIBase, "Orgo API base URL"),
		WorkspaceID: fs.String("orgo-workspace-id", defaults.WorkspaceID, "Existing Orgo workspace ID to create computers in"),
		RAMGB:       fs.Int("orgo-ram", defaults.RAMGB, "Orgo computer RAM in GB"),
		CPUs:        fs.Int("orgo-cpu", defaults.CPUs, "Orgo computer CPU count"),
		DiskGB:      fs.Int("orgo-disk", defaults.DiskGB, "Orgo computer disk size in GB"),
		Resolution:  fs.String("orgo-resolution", defaults.Resolution, "Orgo desktop resolution, for example 1280x720x24"),
	}
}

// OrgoConfigVisitedFlags records raw flag visits, independently of application.
type OrgoConfigVisitedFlags struct {
	APIBase bool
}

// OrgoConfigFlagPresence reports visits for tracked flag bindings.
func OrgoConfigFlagPresence(fs *flag.FlagSet) OrgoConfigVisitedFlags {
	return OrgoConfigVisitedFlags{
		APIBase: flagWasSet(fs, "orgo-api-base"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values OrgoConfigFlagValues) Apply(cfg *OrgoConfig, fs *flag.FlagSet) OrgoConfigApplied {
	var applied OrgoConfigApplied
	visited := OrgoConfigFlagPresence(fs)
	if visited.APIBase {
		cfg.APIBase = *values.APIBase
		applied.APIBase = true
	}
	if flagWasSet(fs, "orgo-workspace-id") {
		cfg.WorkspaceID = *values.WorkspaceID
	}
	if flagWasSet(fs, "orgo-ram") {
		cfg.RAMGB = *values.RAMGB
	}
	if flagWasSet(fs, "orgo-cpu") {
		cfg.CPUs = *values.CPUs
	}
	if flagWasSet(fs, "orgo-disk") {
		cfg.DiskGB = *values.DiskGB
	}
	if flagWasSet(fs, "orgo-resolution") {
		cfg.Resolution = *values.Resolution
	}
	return applied
}
