// Code generated by scripts/configgen from config_vultr.go; DO NOT EDIT.

package cli

type fileVultrConfig struct {
	Region        string   `yaml:"region,omitempty"`
	OS            string   `yaml:"os,omitempty"`
	Image         string   `yaml:"image,omitempty"`
	Snapshot      string   `yaml:"snapshot,omitempty"`
	FirewallGroup string   `yaml:"firewallGroup,omitempty"`
	VPCIDs        []string `yaml:"vpcIds,omitempty"`
	SSHCIDRs      []string `yaml:"sshCIDRs,omitempty"`
	UserScheme    string   `yaml:"userScheme,omitempty"`
}

func defaultVultrConfig() VultrConfig {
	return VultrConfig{}
}

// VultrConfigApplied records accepted assignments during one application.
type VultrConfigApplied struct {
	InputAccepted bool
}

func (cfg *VultrConfig) applyFile(file *fileVultrConfig) (VultrConfigApplied, error) {
	var applied VultrConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "vultr")
	return applied, err
}

func (cfg *VultrConfig) applyEnv() (VultrConfigApplied, error) {
	var applied VultrConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 8)
	return applied, err
}
