// Code generated by scripts/configgen from config_boxd.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileBoxdConfig struct {
	APIURL          string `yaml:"apiUrl,omitempty"`
	GRPCURL         string `yaml:"grpcUrl,omitempty"`
	Org             string `yaml:"org,omitempty"`
	WorkRoot        string `yaml:"workRoot,omitempty"`
	DeleteOnRelease *bool  `yaml:"deleteOnRelease,omitempty"`
}

const BoxdConfigDefaultAPIURL string = "https://app.boxd.sh"
const BoxdConfigDefaultGRPCURL string = "boxd.sh:9443"
const BoxdConfigDefaultWorkRoot string = "/home/boxd/crabbox"
const BoxdConfigDefaultDeleteOnRelease bool = true

func defaultBoxdConfig() BoxdConfig {
	return BoxdConfig{
		APIURL:          BoxdConfigDefaultAPIURL,
		GRPCURL:         BoxdConfigDefaultGRPCURL,
		WorkRoot:        BoxdConfigDefaultWorkRoot,
		DeleteOnRelease: BoxdConfigDefaultDeleteOnRelease,
	}
}

// BoxdConfigApplied records accepted assignments during one application.
type BoxdConfigApplied struct {
	InputAccepted   bool
	WorkRoot        bool
	DeleteOnRelease bool
}

func (cfg *BoxdConfig) applyFile(file *fileBoxdConfig, trusted bool) (BoxdConfigApplied, error) {
	var applied BoxdConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "boxd")
	return applied, err
}

func (cfg *BoxdConfig) applyEnv() (BoxdConfigApplied, error) {
	var applied BoxdConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// BoxdConfigFlagValues holds parsed values; only visited flags are applied.
type BoxdConfigFlagValues struct {
	APIURL          *string
	GRPCURL         *string
	Org             *string
	WorkRoot        *string
	DeleteOnRelease *bool
}

// RegisterBoxdConfigFlags registers mechanical bindings without selecting a provider.
func RegisterBoxdConfigFlags(fs *flag.FlagSet, defaults BoxdConfig) BoxdConfigFlagValues {
	var values BoxdConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// BoxdConfigVisitedFlags records raw flag visits, independently of application.
type BoxdConfigVisitedFlags struct {
	WorkRoot        bool
	DeleteOnRelease bool
}

// BoxdConfigFlagPresence reports visits for tracked flag bindings.
func BoxdConfigFlagPresence(fs *flag.FlagSet) BoxdConfigVisitedFlags {
	var visited BoxdConfigVisitedFlags
	recordConfigFlagVisits[BoxdConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values BoxdConfigFlagValues) Apply(cfg *BoxdConfig, fs *flag.FlagSet) (BoxdConfigApplied, error) {
	var applied BoxdConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
