// Code generated by scripts/configgen from config_proxmox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileProxmoxConfig struct {
	APIURL      string `yaml:"apiUrl,omitempty"`
	TokenID     string `yaml:"tokenId,omitempty"`
	TokenSecret string `yaml:"tokenSecret,omitempty"`
	Node        string `yaml:"node,omitempty"`
	TemplateID  int    `yaml:"templateId,omitempty"`
	Storage     string `yaml:"storage,omitempty"`
	Pool        string `yaml:"pool,omitempty"`
	Bridge      string `yaml:"bridge,omitempty"`
	User        string `yaml:"user,omitempty"`
	WorkRoot    string `yaml:"workRoot,omitempty"`
	FullClone   *bool  `yaml:"fullClone,omitempty"`
	InsecureTLS *bool  `yaml:"insecureTLS,omitempty"`
}

const ProxmoxConfigDefaultUser string = "crabbox"
const ProxmoxConfigDefaultFullClone bool = true

func defaultProxmoxConfig() ProxmoxConfig {
	return ProxmoxConfig{
		User:      ProxmoxConfigDefaultUser,
		FullClone: ProxmoxConfigDefaultFullClone,
	}
}

// ProxmoxConfigApplied records accepted assignments during one application.
type ProxmoxConfigApplied struct {
	InputAccepted bool
	APIURL        bool
	TokenID       bool
	TokenSecret   bool
	User          bool
	WorkRoot      bool
	InsecureTLS   bool
}

func (cfg *ProxmoxConfig) applyFile(file *fileProxmoxConfig) (ProxmoxConfigApplied, error) {
	var applied ProxmoxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "proxmox")
	return applied, err
}

func (cfg *ProxmoxConfig) applyEnv() (ProxmoxConfigApplied, error) {
	var applied ProxmoxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 12)
	return applied, err
}

// ProxmoxConfigFlagValues holds parsed values; only visited flags are applied.
type ProxmoxConfigFlagValues struct {
	APIURL      *string
	Node        *string
	TemplateID  *int
	Storage     *string
	Pool        *string
	Bridge      *string
	User        *string
	WorkRoot    *string
	FullClone   *bool
	InsecureTLS *bool
}

// RegisterProxmoxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterProxmoxConfigFlags(fs *flag.FlagSet, defaults ProxmoxConfig) ProxmoxConfigFlagValues {
	var values ProxmoxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// ProxmoxConfigVisitedFlags records raw flag visits, independently of application.
type ProxmoxConfigVisitedFlags struct {
	APIURL      bool
	User        bool
	WorkRoot    bool
	InsecureTLS bool
}

// ProxmoxConfigFlagPresence reports visits for tracked flag bindings.
func ProxmoxConfigFlagPresence(fs *flag.FlagSet) ProxmoxConfigVisitedFlags {
	var visited ProxmoxConfigVisitedFlags
	recordConfigFlagVisits[ProxmoxConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values ProxmoxConfigFlagValues) Apply(cfg *ProxmoxConfig, fs *flag.FlagSet) (ProxmoxConfigApplied, error) {
	var applied ProxmoxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
