// Code generated by scripts/configgen from config_opencomputer.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileOpenComputerConfig struct {
	Workdir         string `yaml:"workdir,omitempty"`
	CPU             *int   `yaml:"cpu,omitempty"`
	MemoryMB        *int   `yaml:"memoryMB,omitempty"`
	TimeoutSecs     *int   `yaml:"timeoutSecs,omitempty"`
	ExecTimeoutSecs *int   `yaml:"execTimeoutSecs,omitempty"`
	Burst           *bool  `yaml:"burst,omitempty"`
}

const OpenComputerConfigDefaultWorkdir string = "/workspace/crabbox"
const OpenComputerConfigDefaultExecTimeoutSecs int = 3600

func defaultOpenComputerConfig() OpenComputerConfig {
	return OpenComputerConfig{
		Workdir:         OpenComputerConfigDefaultWorkdir,
		ExecTimeoutSecs: OpenComputerConfigDefaultExecTimeoutSecs,
	}
}

// OpenComputerConfigApplied records accepted assignments during one application.
type OpenComputerConfigApplied struct {
	InputAccepted bool
}

func (cfg *OpenComputerConfig) applyFile(file *fileOpenComputerConfig) (OpenComputerConfigApplied, error) {
	var applied OpenComputerConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "opencomputer")
	return applied, err
}

func (cfg *OpenComputerConfig) applyEnv() (OpenComputerConfigApplied, error) {
	var applied OpenComputerConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 8)
	return applied, err
}

// OpenComputerConfigFlagValues holds parsed values; only visited flags are applied.
type OpenComputerConfigFlagValues struct {
	APIURL          *string
	Workdir         *string
	CPU             *int
	MemoryMB        *int
	TimeoutSecs     *int
	ExecTimeoutSecs *int
	Burst           *bool
	ForgetMissing   *bool
}

// RegisterOpenComputerConfigFlags registers mechanical bindings without selecting a provider.
func RegisterOpenComputerConfigFlags(fs *flag.FlagSet, defaults OpenComputerConfig) OpenComputerConfigFlagValues {
	var values OpenComputerConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values OpenComputerConfigFlagValues) Apply(cfg *OpenComputerConfig, fs *flag.FlagSet) (OpenComputerConfigApplied, error) {
	var applied OpenComputerConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
