// Code generated by scripts/configgen from config_namespace.go; DO NOT EDIT.

package cli

import (
	"flag"
	"time"
)

type fileNamespaceConfig struct {
	Image               string `yaml:"image,omitempty"`
	Size                string `yaml:"size,omitempty"`
	Repository          string `yaml:"repository,omitempty"`
	Site                string `yaml:"site,omitempty"`
	VolumeSizeGB        int    `yaml:"volumeSizeGB,omitempty"`
	AutoStopIdleTimeout string `yaml:"autoStopIdleTimeout,omitempty"`
	WorkRoot            string `yaml:"workRoot,omitempty"`
	DeleteOnRelease     *bool  `yaml:"deleteOnRelease,omitempty"`
}

const NamespaceConfigDefaultImage string = "builtin:base"
const NamespaceConfigDefaultAutoStopIdleTimeout time.Duration = 1800 * time.Second
const NamespaceConfigDefaultWorkRoot string = "/workspaces/crabbox"

func defaultNamespaceConfig() NamespaceConfig {
	return NamespaceConfig{
		Image:               NamespaceConfigDefaultImage,
		AutoStopIdleTimeout: NamespaceConfigDefaultAutoStopIdleTimeout,
		WorkRoot:            NamespaceConfigDefaultWorkRoot,
	}
}

// NamespaceConfigApplied records accepted assignments during one application.
type NamespaceConfigApplied struct {
	InputAccepted   bool
	Size            bool
	WorkRoot        bool
	DeleteOnRelease bool
}

func (cfg *NamespaceConfig) applyFile(file *fileNamespaceConfig) (NamespaceConfigApplied, error) {
	var applied NamespaceConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "namespace")
	return applied, err
}

func (cfg *NamespaceConfig) applyEnv() (NamespaceConfigApplied, error) {
	var applied NamespaceConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 8)
	return applied, err
}

// NamespaceConfigFlagValues holds parsed values; only visited flags are applied.
type NamespaceConfigFlagValues struct {
	Image               *string
	Size                *string
	Repository          *string
	Site                *string
	VolumeSizeGB        *int
	AutoStopIdleTimeout *string
	WorkRoot            *string
	DeleteOnRelease     *bool
}

// RegisterNamespaceConfigFlags registers mechanical bindings without selecting a provider.
func RegisterNamespaceConfigFlags(fs *flag.FlagSet, defaults NamespaceConfig) NamespaceConfigFlagValues {
	var values NamespaceConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// NamespaceConfigVisitedFlags records raw flag visits, independently of application.
type NamespaceConfigVisitedFlags struct {
	Size            bool
	WorkRoot        bool
	DeleteOnRelease bool
}

// NamespaceConfigFlagPresence reports visits for tracked flag bindings.
func NamespaceConfigFlagPresence(fs *flag.FlagSet) NamespaceConfigVisitedFlags {
	var visited NamespaceConfigVisitedFlags
	recordConfigFlagVisits[NamespaceConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values NamespaceConfigFlagValues) Apply(cfg *NamespaceConfig, fs *flag.FlagSet) (NamespaceConfigApplied, error) {
	var applied NamespaceConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
