// Code generated by scripts/configgen from config_linode.go; DO NOT EDIT.

package cli

type fileLinodeConfig struct {
	Region     string   `yaml:"region,omitempty"`
	Image      string   `yaml:"image,omitempty"`
	Type       string   `yaml:"type,omitempty"`
	FirewallID string   `yaml:"firewall,omitempty"`
	SSHCIDRs   []string `yaml:"sshCIDRs,omitempty"`
}

func defaultLinodeConfig() LinodeConfig {
	return LinodeConfig{}
}

// LinodeConfigApplied records accepted assignments during one application.
type LinodeConfigApplied struct {
	InputAccepted bool
	Image         bool
	Type          bool
}

func (cfg *LinodeConfig) applyFile(file *fileLinodeConfig) (LinodeConfigApplied, error) {
	var applied LinodeConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "linode")
	return applied, err
}

func (cfg *LinodeConfig) applyEnv() (LinodeConfigApplied, error) {
	var applied LinodeConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}
