// Code generated by scripts/configgen from config_sprites.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileSpritesConfig struct {
	APIURL   string `yaml:"apiUrl,omitempty"`
	WorkRoot string `yaml:"workRoot,omitempty"`
}

const SpritesConfigDefaultAPIURL string = "https://api.sprites.dev"
const SpritesConfigDefaultWorkRoot string = "/home/sprite/crabbox"

func defaultSpritesConfig() SpritesConfig {
	return SpritesConfig{
		APIURL:   SpritesConfigDefaultAPIURL,
		WorkRoot: SpritesConfigDefaultWorkRoot,
	}
}

// SpritesConfigApplied records accepted assignments during one application.
type SpritesConfigApplied struct {
	InputAccepted bool
	Token         bool
	APIURL        bool
}

func (cfg *SpritesConfig) applyFile(file *fileSpritesConfig) (SpritesConfigApplied, error) {
	var applied SpritesConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "sprites")
	return applied, err
}

func (cfg *SpritesConfig) applyEnv() (SpritesConfigApplied, error) {
	var applied SpritesConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 3)
	return applied, err
}

// SpritesConfigFlagValues holds parsed values; only visited flags are applied.
type SpritesConfigFlagValues struct {
	APIURL   *string
	WorkRoot *string
}

// RegisterSpritesConfigFlags registers mechanical bindings without selecting a provider.
func RegisterSpritesConfigFlags(fs *flag.FlagSet, defaults SpritesConfig) SpritesConfigFlagValues {
	var values SpritesConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// SpritesConfigVisitedFlags records raw flag visits, independently of application.
type SpritesConfigVisitedFlags struct {
	APIURL bool
}

// SpritesConfigFlagPresence reports visits for tracked flag bindings.
func SpritesConfigFlagPresence(fs *flag.FlagSet) SpritesConfigVisitedFlags {
	var visited SpritesConfigVisitedFlags
	recordConfigFlagVisits[SpritesConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values SpritesConfigFlagValues) Apply(cfg *SpritesConfig, fs *flag.FlagSet) (SpritesConfigApplied, error) {
	var applied SpritesConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
