// Code generated by scripts/configgen from config_unikraft_cloud.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileUnikraftCloudConfig struct {
	APIKey   string `yaml:"apiKey,omitempty"`
	APIURL   string `yaml:"apiUrl,omitempty"`
	Metro    string `yaml:"metro,omitempty"`
	Image    string `yaml:"image,omitempty"`
	MemoryMB int    `yaml:"memoryMB,omitempty"`
}

const UnikraftCloudConfigDefaultMetro string = "fra"

func defaultUnikraftCloudConfig() UnikraftCloudConfig {
	return UnikraftCloudConfig{
		Metro: UnikraftCloudConfigDefaultMetro,
	}
}

// UnikraftCloudConfigApplied records accepted assignments during one application.
type UnikraftCloudConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	APIURL        bool
}

func (cfg *UnikraftCloudConfig) applyFile(file *fileUnikraftCloudConfig) (UnikraftCloudConfigApplied, error) {
	var applied UnikraftCloudConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "unikraft-cloud")
	return applied, err
}

func (cfg *UnikraftCloudConfig) applyEnv() (UnikraftCloudConfigApplied, error) {
	var applied UnikraftCloudConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 5)
	return applied, err
}

// UnikraftCloudConfigFlagValues holds parsed values; only visited flags are applied.
type UnikraftCloudConfigFlagValues struct {
	APIURL   *string
	Metro    *string
	Image    *string
	MemoryMB *int
}

// RegisterUnikraftCloudConfigFlags registers mechanical bindings without selecting a provider.
func RegisterUnikraftCloudConfigFlags(fs *flag.FlagSet, defaults UnikraftCloudConfig) UnikraftCloudConfigFlagValues {
	var values UnikraftCloudConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// UnikraftCloudConfigVisitedFlags records raw flag visits, independently of application.
type UnikraftCloudConfigVisitedFlags struct {
	APIURL bool
}

// UnikraftCloudConfigFlagPresence reports visits for tracked flag bindings.
func UnikraftCloudConfigFlagPresence(fs *flag.FlagSet) UnikraftCloudConfigVisitedFlags {
	var visited UnikraftCloudConfigVisitedFlags
	recordConfigFlagVisits[UnikraftCloudConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values UnikraftCloudConfigFlagValues) Apply(cfg *UnikraftCloudConfig, fs *flag.FlagSet) (UnikraftCloudConfigApplied, error) {
	var applied UnikraftCloudConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
