// Code generated by scripts/configgen from config_e2b.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileE2BConfig struct {
	APIURL   string `yaml:"apiUrl,omitempty"`
	Domain   string `yaml:"domain,omitempty"`
	Template string `yaml:"template,omitempty"`
	Workdir  string `yaml:"workdir,omitempty"`
	User     string `yaml:"user,omitempty"`
}

const E2BConfigDefaultAPIURL string = "https://api.e2b.app"
const E2BConfigDefaultDomain string = "e2b.app"
const E2BConfigDefaultTemplate string = "base"
const E2BConfigDefaultWorkdir string = "crabbox"

func defaultE2BConfig() E2BConfig {
	return E2BConfig{
		APIURL:   E2BConfigDefaultAPIURL,
		Domain:   E2BConfigDefaultDomain,
		Template: E2BConfigDefaultTemplate,
		Workdir:  E2BConfigDefaultWorkdir,
	}
}

// E2BConfigApplied records accepted assignments during one application.
type E2BConfigApplied struct {
	InputAccepted bool
	APIKey        bool
	APIURL        bool
	Domain        bool
}

func (cfg *E2BConfig) applyFile(file *fileE2BConfig) (E2BConfigApplied, error) {
	var applied E2BConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "e2b")
	return applied, err
}

func (cfg *E2BConfig) applyEnv() (E2BConfigApplied, error) {
	var applied E2BConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// E2BConfigFlagValues holds parsed values; only visited flags are applied.
type E2BConfigFlagValues struct {
	APIURL   *string
	Domain   *string
	Template *string
	Workdir  *string
	User     *string
}

// RegisterE2BConfigFlags registers mechanical bindings without selecting a provider.
func RegisterE2BConfigFlags(fs *flag.FlagSet, defaults E2BConfig) E2BConfigFlagValues {
	var values E2BConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// E2BConfigVisitedFlags records raw flag visits, independently of application.
type E2BConfigVisitedFlags struct {
	APIURL bool
	Domain bool
}

// E2BConfigFlagPresence reports visits for tracked flag bindings.
func E2BConfigFlagPresence(fs *flag.FlagSet) E2BConfigVisitedFlags {
	var visited E2BConfigVisitedFlags
	recordConfigFlagVisits[E2BConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values E2BConfigFlagValues) Apply(cfg *E2BConfig, fs *flag.FlagSet) (E2BConfigApplied, error) {
	var applied E2BConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
