// Code generated by scripts/configgen from config_cloudflare.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCloudflareConfig struct {
	APIURL  string `yaml:"apiUrl,omitempty"`
	Token   string `yaml:"token,omitempty"`
	Workdir string `yaml:"workdir,omitempty"`
}

const CloudflareConfigDefaultWorkdir string = "/workspace/crabbox"

func defaultCloudflareConfig() CloudflareConfig {
	return CloudflareConfig{
		Workdir: CloudflareConfigDefaultWorkdir,
	}
}

// CloudflareConfigApplied records accepted assignments during one application.
type CloudflareConfigApplied struct {
	InputAccepted bool
	APIURL        bool
	Token         bool
}

func (cfg *CloudflareConfig) applyFile(file *fileCloudflareConfig) (CloudflareConfigApplied, error) {
	var applied CloudflareConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "cloudflare")
	return applied, err
}

func (cfg *CloudflareConfig) applyEnv() (CloudflareConfigApplied, error) {
	var applied CloudflareConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 3)
	return applied, err
}

// CloudflareConfigFlagValues holds parsed values; only visited flags are applied.
type CloudflareConfigFlagValues struct {
	APIURL  *string
	Workdir *string
}

// RegisterCloudflareConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCloudflareConfigFlags(fs *flag.FlagSet, defaults CloudflareConfig) CloudflareConfigFlagValues {
	var values CloudflareConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// CloudflareConfigVisitedFlags records raw flag visits, independently of application.
type CloudflareConfigVisitedFlags struct {
	APIURL bool
}

// CloudflareConfigFlagPresence reports visits for tracked flag bindings.
func CloudflareConfigFlagPresence(fs *flag.FlagSet) CloudflareConfigVisitedFlags {
	var visited CloudflareConfigVisitedFlags
	recordConfigFlagVisits[CloudflareConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CloudflareConfigFlagValues) Apply(cfg *CloudflareConfig, fs *flag.FlagSet) (CloudflareConfigApplied, error) {
	var applied CloudflareConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
