// Code generated by scripts/configgen from config_exe_dev.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileExeDevConfig struct {
	ControlHost string `yaml:"controlHost,omitempty"`
	Image       string `yaml:"image,omitempty"`
	CPUs        int    `yaml:"cpus,omitempty"`
	Memory      string `yaml:"memory,omitempty"`
	Disk        string `yaml:"disk,omitempty"`
	Command     string `yaml:"command,omitempty"`
	User        string `yaml:"user,omitempty"`
	WorkRoot    string `yaml:"workRoot,omitempty"`
	NoEmail     *bool  `yaml:"noEmail,omitempty"`
}

const ExeDevConfigDefaultControlHost string = "exe.dev"
const ExeDevConfigDefaultCPUs int = 2
const ExeDevConfigDefaultMemory string = "4GB"
const ExeDevConfigDefaultDisk string = "10GB"
const ExeDevConfigDefaultNoEmail bool = true

func defaultExeDevConfig() ExeDevConfig {
	return ExeDevConfig{
		ControlHost: ExeDevConfigDefaultControlHost,
		CPUs:        ExeDevConfigDefaultCPUs,
		Memory:      ExeDevConfigDefaultMemory,
		Disk:        ExeDevConfigDefaultDisk,
		NoEmail:     ExeDevConfigDefaultNoEmail,
	}
}

// ExeDevConfigApplied records accepted assignments during one application.
type ExeDevConfigApplied struct {
	InputAccepted bool
	ControlHost   bool
}

func (cfg *ExeDevConfig) applyFile(file *fileExeDevConfig) (ExeDevConfigApplied, error) {
	var applied ExeDevConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "exe-dev")
	return applied, err
}

func (cfg *ExeDevConfig) applyEnv() (ExeDevConfigApplied, error) {
	var applied ExeDevConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 9)
	return applied, err
}

// ExeDevConfigFlagValues holds parsed values; only visited flags are applied.
type ExeDevConfigFlagValues struct {
	ControlHost *string
	Image       *string
	CPUs        *int
	Memory      *string
	Disk        *string
	Command     *string
	User        *string
	WorkRoot    *string
	NoEmail     *bool
}

// RegisterExeDevConfigFlags registers mechanical bindings without selecting a provider.
func RegisterExeDevConfigFlags(fs *flag.FlagSet, defaults ExeDevConfig) ExeDevConfigFlagValues {
	var values ExeDevConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// ExeDevConfigVisitedFlags records raw flag visits, independently of application.
type ExeDevConfigVisitedFlags struct {
	ControlHost bool
}

// ExeDevConfigFlagPresence reports visits for tracked flag bindings.
func ExeDevConfigFlagPresence(fs *flag.FlagSet) ExeDevConfigVisitedFlags {
	var visited ExeDevConfigVisitedFlags
	recordConfigFlagVisits[ExeDevConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values ExeDevConfigFlagValues) Apply(cfg *ExeDevConfig, fs *flag.FlagSet) (ExeDevConfigApplied, error) {
	var applied ExeDevConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
