// Code generated by scripts/configgen from config_cloud_run_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCloudRunSandboxConfig struct {
	CLIPath     string `yaml:"cliPath,omitempty"`
	Workdir     string `yaml:"workdir,omitempty"`
	AllowEgress *bool  `yaml:"allowEgress,omitempty"`
	Write       *bool  `yaml:"write,omitempty"`
	Rootfs      string `yaml:"rootfs,omitempty"`
}

const CloudRunSandboxConfigDefaultCLIPath string = "/usr/local/gcp/bin/sandbox"
const CloudRunSandboxConfigDefaultWorkdir string = "/tmp/crabbox"
const CloudRunSandboxConfigDefaultWrite bool = true
const CloudRunSandboxConfigDefaultRootfs string = "/"

func defaultCloudRunSandboxConfig() CloudRunSandboxConfig {
	return CloudRunSandboxConfig{
		CLIPath: CloudRunSandboxConfigDefaultCLIPath,
		Workdir: CloudRunSandboxConfigDefaultWorkdir,
		Write:   CloudRunSandboxConfigDefaultWrite,
		Rootfs:  CloudRunSandboxConfigDefaultRootfs,
	}
}

// CloudRunSandboxConfigApplied records accepted assignments during one application.
type CloudRunSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *CloudRunSandboxConfig) applyFile(file *fileCloudRunSandboxConfig) (CloudRunSandboxConfigApplied, error) {
	var applied CloudRunSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "cloud-run-sandbox")
	return applied, err
}

func (cfg *CloudRunSandboxConfig) applyEnv() (CloudRunSandboxConfigApplied, error) {
	var applied CloudRunSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 6)
	return applied, err
}

// CloudRunSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type CloudRunSandboxConfigFlagValues struct {
	GatewayURL  *string
	CLIPath     *string
	Workdir     *string
	AllowEgress *bool
	Write       *bool
	Rootfs      *string
}

// RegisterCloudRunSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCloudRunSandboxConfigFlags(fs *flag.FlagSet, defaults CloudRunSandboxConfig) CloudRunSandboxConfigFlagValues {
	var values CloudRunSandboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CloudRunSandboxConfigFlagValues) Apply(cfg *CloudRunSandboxConfig, fs *flag.FlagSet) (CloudRunSandboxConfigApplied, error) {
	var applied CloudRunSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
