// Code generated by scripts/configgen from config_nebius.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileNebiusConfig struct {
	CLI              string   `yaml:"cli,omitempty"`
	Profile          string   `yaml:"profile,omitempty"`
	ParentID         string   `yaml:"parentId,omitempty"`
	SubnetID         string   `yaml:"subnetId,omitempty"`
	Platform         string   `yaml:"platform,omitempty"`
	Preset           string   `yaml:"preset,omitempty"`
	ImageFamily      string   `yaml:"imageFamily,omitempty"`
	DiskType         string   `yaml:"diskType,omitempty"`
	DiskSizeGiB      int      `yaml:"diskSizeGiB,omitempty"`
	User             string   `yaml:"user,omitempty"`
	PublicIP         string   `yaml:"publicIP,omitempty"`
	SecurityGroupIDs []string `yaml:"securityGroupIds,omitempty"`
	ServiceAccountID string   `yaml:"serviceAccountId,omitempty"`
	RecoveryPolicy   string   `yaml:"recoveryPolicy,omitempty"`
}

const NebiusConfigDefaultCLI string = "nebius"
const NebiusConfigDefaultPlatform string = "cpu-d3"
const NebiusConfigDefaultPreset string = "4vcpu-16gb"
const NebiusConfigDefaultImageFamily string = "ubuntu24.04-driverless"
const NebiusConfigDefaultDiskType string = "network_ssd"
const NebiusConfigDefaultDiskSizeGiB int = 50
const NebiusConfigDefaultUser string = "crabbox"
const NebiusConfigDefaultPublicIP string = "dynamic"
const NebiusConfigDefaultRecoveryPolicy string = "fail"

func defaultNebiusConfig() NebiusConfig {
	return NebiusConfig{
		CLI:            NebiusConfigDefaultCLI,
		Platform:       NebiusConfigDefaultPlatform,
		Preset:         NebiusConfigDefaultPreset,
		ImageFamily:    NebiusConfigDefaultImageFamily,
		DiskType:       NebiusConfigDefaultDiskType,
		DiskSizeGiB:    NebiusConfigDefaultDiskSizeGiB,
		User:           NebiusConfigDefaultUser,
		PublicIP:       NebiusConfigDefaultPublicIP,
		RecoveryPolicy: NebiusConfigDefaultRecoveryPolicy,
	}
}

// NebiusConfigApplied records accepted assignments during one application.
type NebiusConfigApplied struct {
	InputAccepted bool
}

func (cfg *NebiusConfig) applyFile(file *fileNebiusConfig, trusted bool) (NebiusConfigApplied, error) {
	var applied NebiusConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "nebius")
	return applied, err
}

func (cfg *NebiusConfig) applyEnv() (NebiusConfigApplied, error) {
	var applied NebiusConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 14)
	return applied, err
}

// NebiusConfigFlagValues holds parsed values; only visited flags are applied.
type NebiusConfigFlagValues struct {
	CLI              *string
	Profile          *string
	ParentID         *string
	SubnetID         *string
	Platform         *string
	Preset           *string
	ImageFamily      *string
	DiskType         *string
	DiskSizeGiB      *int
	User             *string
	PublicIP         *string
	SecurityGroupIDs *string
	ServiceAccountID *string
	RecoveryPolicy   *string
}

// RegisterNebiusConfigFlags registers mechanical bindings without selecting a provider.
func RegisterNebiusConfigFlags(fs *flag.FlagSet, defaults NebiusConfig) NebiusConfigFlagValues {
	var values NebiusConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values NebiusConfigFlagValues) Apply(cfg *NebiusConfig, fs *flag.FlagSet) (NebiusConfigApplied, error) {
	var applied NebiusConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
