// Code generated by scripts/configgen from config_hostinger.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileHostingerConfig struct {
	APIToken        string `yaml:"apiToken,omitempty"`
	APIURL          string `yaml:"apiUrl,omitempty"`
	ItemID          string `yaml:"itemId,omitempty"`
	PaymentMethodID string `yaml:"paymentMethodId,omitempty"`
	TemplateID      string `yaml:"templateId,omitempty"`
	DataCenterID    string `yaml:"dataCenterId,omitempty"`
	HostnamePrefix  string `yaml:"hostnamePrefix,omitempty"`
	User            string `yaml:"user,omitempty"`
	WorkRoot        string `yaml:"workRoot,omitempty"`
	AllowPurchase   *bool  `yaml:"allowPurchase,omitempty"`
	ReleaseAction   string `yaml:"releaseAction,omitempty"`
}

const HostingerConfigDefaultAPIURL string = "https://developers.hostinger.com"
const HostingerConfigDefaultHostnamePrefix string = "crabbox"
const HostingerConfigDefaultUser string = "root"
const HostingerConfigDefaultReleaseAction string = "stop"

func defaultHostingerConfig() HostingerConfig {
	return HostingerConfig{
		APIURL:         HostingerConfigDefaultAPIURL,
		HostnamePrefix: HostingerConfigDefaultHostnamePrefix,
		User:           HostingerConfigDefaultUser,
		ReleaseAction:  HostingerConfigDefaultReleaseAction,
	}
}

// HostingerConfigApplied records accepted assignments during one application.
type HostingerConfigApplied struct {
	InputAccepted bool
	User          bool
	WorkRoot      bool
}

func (cfg *HostingerConfig) applyFile(file *fileHostingerConfig, trusted bool) (HostingerConfigApplied, error) {
	var applied HostingerConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "hostinger")
	return applied, err
}

func (cfg *HostingerConfig) applyEnv() (HostingerConfigApplied, error) {
	var applied HostingerConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 11)
	return applied, err
}

// HostingerConfigFlagValues holds parsed values; only visited flags are applied.
type HostingerConfigFlagValues struct {
	APIURL          *string
	ItemID          *string
	PaymentMethodID *string
	TemplateID      *string
	DataCenterID    *string
	HostnamePrefix  *string
	User            *string
	WorkRoot        *string
	AllowPurchase   *bool
	ReleaseAction   *string
}

// RegisterHostingerConfigFlags registers mechanical bindings without selecting a provider.
func RegisterHostingerConfigFlags(fs *flag.FlagSet, defaults HostingerConfig) HostingerConfigFlagValues {
	var values HostingerConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// HostingerConfigVisitedFlags records raw flag visits, independently of application.
type HostingerConfigVisitedFlags struct {
	User     bool
	WorkRoot bool
}

// HostingerConfigFlagPresence reports visits for tracked flag bindings.
func HostingerConfigFlagPresence(fs *flag.FlagSet) HostingerConfigVisitedFlags {
	var visited HostingerConfigVisitedFlags
	recordConfigFlagVisits[HostingerConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values HostingerConfigFlagValues) Apply(cfg *HostingerConfig, fs *flag.FlagSet) (HostingerConfigApplied, error) {
	var applied HostingerConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
