// Code generated by scripts/configgen from config_vast.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileVastConfig struct {
	APIURL         string   `yaml:"apiUrl,omitempty"`
	InstanceType   string   `yaml:"instanceType,omitempty"`
	GPUName        string   `yaml:"gpuName,omitempty"`
	GPUCount       int      `yaml:"gpuCount,omitempty"`
	Image          string   `yaml:"image,omitempty"`
	TemplateID     string   `yaml:"templateId,omitempty"`
	Runtype        string   `yaml:"runtype,omitempty"`
	DiskGB         int      `yaml:"diskGB,omitempty"`
	MaxDphTotal    *float64 `yaml:"maxDphTotal,omitempty"`
	MinReliability *float64 `yaml:"minReliability,omitempty"`
	Order          string   `yaml:"order,omitempty"`
	User           string   `yaml:"user,omitempty"`
	WorkRoot       string   `yaml:"workRoot,omitempty"`
	ReleaseAction  string   `yaml:"releaseAction,omitempty"`
}

const VastConfigDefaultAPIURL string = "https://console.vast.ai/api/v0"
const VastConfigDefaultInstanceType string = "ondemand"
const VastConfigDefaultImage string = "nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04"
const VastConfigDefaultRuntype string = "ssh_direct"
const VastConfigDefaultDiskGB int = 20
const VastConfigDefaultOrder string = "dlperf_per_dphtotal desc"
const VastConfigDefaultUser string = "root"
const VastConfigDefaultWorkRoot string = "/work/crabbox"
const VastConfigDefaultReleaseAction string = "destroy"

func defaultVastConfig() VastConfig {
	return VastConfig{
		APIURL:        VastConfigDefaultAPIURL,
		InstanceType:  VastConfigDefaultInstanceType,
		Image:         VastConfigDefaultImage,
		Runtype:       VastConfigDefaultRuntype,
		DiskGB:        VastConfigDefaultDiskGB,
		Order:         VastConfigDefaultOrder,
		User:          VastConfigDefaultUser,
		WorkRoot:      VastConfigDefaultWorkRoot,
		ReleaseAction: VastConfigDefaultReleaseAction,
	}
}

// VastConfigApplied records accepted assignments during one application.
type VastConfigApplied struct {
	APIKey        bool
	APIURL        bool
	InstanceType  bool
	WorkRoot      bool
	ReleaseAction bool
}

func (cfg *VastConfig) applyFile(file *fileVastConfig) (VastConfigApplied, error) {
	var applied VastConfigApplied
	if file == nil {
		return applied, nil
	}
	if file.APIURL != "" {
		cfg.APIURL = file.APIURL
		applied.APIURL = true
	}
	if file.InstanceType != "" {
		cfg.InstanceType = file.InstanceType
		applied.InstanceType = true
	}
	if file.GPUName != "" {
		cfg.GPUName = file.GPUName
	}
	if file.GPUCount != 0 {
		cfg.GPUCount = file.GPUCount
	}
	if file.Image != "" {
		cfg.Image = file.Image
	}
	if file.TemplateID != "" {
		cfg.TemplateID = file.TemplateID
	}
	if file.Runtype != "" {
		cfg.Runtype = file.Runtype
	}
	if file.DiskGB != 0 {
		cfg.DiskGB = file.DiskGB
	}
	if file.MaxDphTotal != nil {
		cfg.MaxDphTotal = *file.MaxDphTotal
	}
	if file.MinReliability != nil {
		cfg.MinReliability = *file.MinReliability
	}
	if file.Order != "" {
		cfg.Order = file.Order
	}
	if file.User != "" {
		cfg.User = file.User
	}
	if file.WorkRoot != "" {
		cfg.WorkRoot = file.WorkRoot
		applied.WorkRoot = true
	}
	if file.ReleaseAction != "" {
		cfg.ReleaseAction = file.ReleaseAction
		applied.ReleaseAction = true
	}
	return applied, nil
}

func (cfg *VastConfig) applyEnv() (VastConfigApplied, error) {
	var applied VastConfigApplied
	if value, ok := firstNonEmptyEnv("CRABBOX_VAST_API_KEY", "VAST_API_KEY"); ok {
		cfg.APIKey = value
		applied.APIKey = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VAST_API_URL", "VAST_API_URL"); ok {
		cfg.APIURL = value
		applied.APIURL = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VAST_INSTANCE_TYPE"); ok {
		cfg.InstanceType = value
		applied.InstanceType = true
	}
	cfg.GPUName = getenv("CRABBOX_VAST_GPU_NAME", cfg.GPUName)
	cfg.GPUCount = getenvInt("CRABBOX_VAST_GPU_COUNT", cfg.GPUCount)
	cfg.Image = getenv("CRABBOX_VAST_IMAGE", cfg.Image)
	cfg.TemplateID = getenv("CRABBOX_VAST_TEMPLATE_ID", cfg.TemplateID)
	cfg.Runtype = getenv("CRABBOX_VAST_RUNTYPE", cfg.Runtype)
	cfg.DiskGB = getenvInt("CRABBOX_VAST_DISK_GB", cfg.DiskGB)
	cfg.MaxDphTotal = getenvFloat("CRABBOX_VAST_MAX_DPH_TOTAL", cfg.MaxDphTotal)
	cfg.MinReliability = getenvFloat("CRABBOX_VAST_MIN_RELIABILITY", cfg.MinReliability)
	cfg.Order = getenv("CRABBOX_VAST_ORDER", cfg.Order)
	cfg.User = getenv("CRABBOX_VAST_USER", cfg.User)
	if value, ok := firstNonEmptyEnv("CRABBOX_VAST_WORK_ROOT"); ok {
		cfg.WorkRoot = value
		applied.WorkRoot = true
	}
	if value, ok := firstNonEmptyEnv("CRABBOX_VAST_RELEASE_ACTION"); ok {
		cfg.ReleaseAction = value
		applied.ReleaseAction = true
	}
	return applied, nil
}

// VastConfigFlagValues holds parsed values; only visited flags are applied.
type VastConfigFlagValues struct {
	APIURL         *string
	InstanceType   *string
	GPUName        *string
	GPUCount       *int
	Image          *string
	TemplateID     *string
	Runtype        *string
	DiskGB         *int
	MaxDphTotal    *float64
	MinReliability *float64
	Order          *string
	User           *string
	WorkRoot       *string
	ReleaseAction  *string
}

// RegisterVastConfigFlags registers mechanical bindings without selecting a provider.
func RegisterVastConfigFlags(fs *flag.FlagSet, defaults VastConfig) VastConfigFlagValues {
	return VastConfigFlagValues{
		APIURL:         fs.String("vast-api-url", defaults.APIURL, "Vast.ai REST API URL"),
		InstanceType:   fs.String("vast-instance-type", defaults.InstanceType, "Vast.ai offer type: ondemand or interruptible"),
		GPUName:        fs.String("vast-gpu-name", defaults.GPUName, "Vast.ai GPU name selector"),
		GPUCount:       fs.Int("vast-gpu-count", defaults.GPUCount, "Vast.ai minimum GPU count"),
		Image:          fs.String("vast-image", defaults.Image, "Docker image to deploy on the instance"),
		TemplateID:     fs.String("vast-template-id", defaults.TemplateID, "Optional Vast.ai template ID"),
		Runtype:        fs.String("vast-runtype", defaults.Runtype, "Vast.ai runtime type: ssh_direct"),
		DiskGB:         fs.Int("vast-disk-gb", defaults.DiskGB, "Instance disk size in GB"),
		MaxDphTotal:    fs.Float64("vast-max-dph-total", defaults.MaxDphTotal, "Maximum total dollars per hour"),
		MinReliability: fs.Float64("vast-min-reliability", defaults.MinReliability, "Minimum reliability score from 0 to 1"),
		Order:          fs.String("vast-order", defaults.Order, "Vast.ai offer ordering expression"),
		User:           fs.String("vast-user", defaults.User, "SSH user for Vast.ai instances"),
		WorkRoot:       fs.String("vast-work-root", defaults.WorkRoot, "remote Crabbox work root on Vast.ai instances"),
		ReleaseAction:  fs.String("vast-release-action", defaults.ReleaseAction, "Vast.ai release action: destroy, stop, or keep"),
	}
}

// VastConfigVisitedFlags records raw flag visits, independently of application.
type VastConfigVisitedFlags struct {
	APIURL        bool
	InstanceType  bool
	WorkRoot      bool
	ReleaseAction bool
}

// VastConfigFlagPresence reports visits for tracked flag bindings.
func VastConfigFlagPresence(fs *flag.FlagSet) VastConfigVisitedFlags {
	return VastConfigVisitedFlags{
		APIURL:        flagWasSet(fs, "vast-api-url"),
		InstanceType:  flagWasSet(fs, "vast-instance-type"),
		WorkRoot:      flagWasSet(fs, "vast-work-root"),
		ReleaseAction: flagWasSet(fs, "vast-release-action"),
	}
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values VastConfigFlagValues) Apply(cfg *VastConfig, fs *flag.FlagSet) VastConfigApplied {
	var applied VastConfigApplied
	visited := VastConfigFlagPresence(fs)
	if visited.APIURL {
		cfg.APIURL = *values.APIURL
		applied.APIURL = true
	}
	if visited.InstanceType {
		cfg.InstanceType = *values.InstanceType
		applied.InstanceType = true
	}
	if flagWasSet(fs, "vast-gpu-name") {
		cfg.GPUName = *values.GPUName
	}
	if flagWasSet(fs, "vast-gpu-count") {
		cfg.GPUCount = *values.GPUCount
	}
	if flagWasSet(fs, "vast-image") {
		cfg.Image = *values.Image
	}
	if flagWasSet(fs, "vast-template-id") {
		cfg.TemplateID = *values.TemplateID
	}
	if flagWasSet(fs, "vast-runtype") {
		cfg.Runtype = *values.Runtype
	}
	if flagWasSet(fs, "vast-disk-gb") {
		cfg.DiskGB = *values.DiskGB
	}
	if flagWasSet(fs, "vast-max-dph-total") {
		cfg.MaxDphTotal = *values.MaxDphTotal
	}
	if flagWasSet(fs, "vast-min-reliability") {
		cfg.MinReliability = *values.MinReliability
	}
	if flagWasSet(fs, "vast-order") {
		cfg.Order = *values.Order
	}
	if flagWasSet(fs, "vast-user") {
		cfg.User = *values.User
	}
	if visited.WorkRoot {
		cfg.WorkRoot = *values.WorkRoot
		applied.WorkRoot = true
	}
	if visited.ReleaseAction {
		cfg.ReleaseAction = *values.ReleaseAction
		applied.ReleaseAction = true
	}
	return applied
}
