// Code generated by scripts/configgen from config_coder.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileCoderConfig struct {
	CLIPath              string   `yaml:"cliPath,omitempty"`
	Template             string   `yaml:"template,omitempty"`
	Preset               string   `yaml:"preset,omitempty"`
	WorkspacePrefix      string   `yaml:"workspacePrefix,omitempty"`
	WorkRoot             string   `yaml:"workRoot,omitempty"`
	DeleteOnRelease      *bool    `yaml:"deleteOnRelease,omitempty"`
	Wait                 string   `yaml:"wait,omitempty"`
	UseParameterDefaults *bool    `yaml:"useParameterDefaults,omitempty"`
	Parameters           []string `yaml:"parameters,omitempty"`
	RichParameterFile    string   `yaml:"richParameterFile,omitempty"`
}

const CoderConfigDefaultCLIPath string = "coder"
const CoderConfigDefaultWorkspacePrefix string = "crabbox-"
const CoderConfigDefaultWorkRoot string = "/home/coder/crabbox"
const CoderConfigDefaultWait string = "yes"

func defaultCoderConfig() CoderConfig {
	return CoderConfig{
		CLIPath:         CoderConfigDefaultCLIPath,
		WorkspacePrefix: CoderConfigDefaultWorkspacePrefix,
		WorkRoot:        CoderConfigDefaultWorkRoot,
		Wait:            CoderConfigDefaultWait,
	}
}

// CoderConfigApplied records accepted assignments during one application.
type CoderConfigApplied struct {
	InputAccepted     bool
	CLIPath           bool
	WorkRoot          bool
	RichParameterFile bool
}

func (cfg *CoderConfig) applyFile(file *fileCoderConfig) (CoderConfigApplied, error) {
	var applied CoderConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, true, "coder")
	return applied, err
}

func (cfg *CoderConfig) applyEnv() (CoderConfigApplied, error) {
	var applied CoderConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 10)
	return applied, err
}

// CoderConfigFlagValues holds parsed values; only visited flags are applied.
type CoderConfigFlagValues struct {
	CLIPath              *string
	Template             *string
	Preset               *string
	WorkspacePrefix      *string
	WorkRoot             *string
	DeleteOnRelease      *bool
	Wait                 *string
	UseParameterDefaults *bool
	Parameters           *string
	RichParameterFile    *string
}

// RegisterCoderConfigFlags registers mechanical bindings without selecting a provider.
func RegisterCoderConfigFlags(fs *flag.FlagSet, defaults CoderConfig) CoderConfigFlagValues {
	var values CoderConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// CoderConfigVisitedFlags records raw flag visits, independently of application.
type CoderConfigVisitedFlags struct {
	CLIPath           bool
	WorkRoot          bool
	RichParameterFile bool
}

// CoderConfigFlagPresence reports visits for tracked flag bindings.
func CoderConfigFlagPresence(fs *flag.FlagSet) CoderConfigVisitedFlags {
	var visited CoderConfigVisitedFlags
	recordConfigFlagVisits[CoderConfig](fs, &visited)
	return visited
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values CoderConfigFlagValues) Apply(cfg *CoderConfig, fs *flag.FlagSet) (CoderConfigApplied, error) {
	var applied CoderConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
